### ISSUE TITLE
onwriteend callback not called

### ISSUE THREAD

**Issue by mgiulio** [eligrey/FileSaver.js#1]
Hello, I am planning  to use HTML5(where supported) as an alternative to [Downloadify](https://github.com/dcneiner/Downloadify) in the [custom download builder](http://christianv.github.com/jquery-lifestream/download/) for the [jQuery Lifestream plugin](https://github.com/christianv/jquery-lifestream). So, because I am still new to the various File APIs I started to use your script.

I need to monitor the download completion. I followed your relative code snippet example:

``` JavaScript
var filesaver = saveAs(blob, "secret stuff that you won't send to a server.truecrypt");
filesaver.onwriteend = function() {
    // file saved, do something here
};
```

but the callback was never called because the event is fired before its registration.

I patched the script in this way:

```
diff --git a/download/js/FileSaver.js b/download/js/FileSaver.js
index 445c0ae..c2eeeaf 100644
--- a/download/js/FileSaver.js
+++ b/download/js/FileSaver.js
@@ -68,7 +68,8 @@ var saveAs = saveAs || (function(view) {
                }
            }
        }
-       , FileSaver = function(blob, name) {
+       , FileSaver = function(blob, name, afterDownload) {
+      this.onwriteend = afterDownload;
            // First try a.download, then web filesystem, then object URLs
            var
                  filesaver = this
@@ -186,8 +187,8 @@ var saveAs = saveAs || (function(view) {
            }), fs_error);
        }
        , FS_proto = FileSaver.prototype
-       , saveAs = function(blob, name) {
-           return new FileSaver(blob, name);
+       , saveAs = function(blob, name, afterDownload) {
+        return new FileSaver(blob, name,afterDownload);
        }
    ;
    FS_proto.abort = function() {
```

Is there a better/proper way to do this?

Thanks in advance.

**Comment by jimmywarting** [comment]
Old issue, I know... But [StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js) is able to do this. Will only work in chrome atm

```javascript
const fileStream = streamSaver.createWriteStream('filename.txt')
const blobStream = streamSaver.createBlobReader(blob)

blobStream.pipeTo(fileStream).then(() => {
  console.log("done")
})
```

**Comment by bes1002t** [comment]
is there any progress made over the years? Perhaps some new Browser features which allow this now?

**Comment by jimmywarting** [comment]
Filesaver is sync so no there is none and never will be included in this lib. 

However, this might help you do async wires and do progress monitor
- https://github.com/jimmywarting/StreamSaver.js
- https://github.com/jimmywarting/native-file-system-adapter
- https://wicg.github.io/native-file-system/
