### ISSUE TITLE
Export few columns to xls

### ISSUE THREAD

**Issue by arepalli-praveenkumar** [eligrey/FileSaver.js#116]
here is sample data 

<div id="tableData">
<table>
<th>ID</th>
<th>Name</th>
<th>Email</th>
<th>Actions</th>
<tr>
<td>1</td>
<td>Praveen</td>
<td>ex@gmail.com</td>
<td>Edit|Delete</td>
</tr>
</table>
</div> 

When is saveAs();
I am getting innerHTML by using ID

var blob = new Blob([document.getElementById('tableData').innerHTML], {
            type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
        });
        saveAs(blob, "List.xls");

Its working fine.
I am expecting only 3 columns those are 
ID ,Name and Email not Actions in XLS file

<table>
<th>ID</th>
<th>Name</th>
<th>Email</th>
<tr>
<td>1</td>
<td>Praveen</td>
<td>ex@gmail.com</td>
</tr>
</table>

How to achieve this ?
or 
I have 
var data = [{"ID" : "1","Name":"Praveen","Email":"ex@gmail.com"}];
can pass above "data" directly ?
Please help me in this

**Comment by zh-wowtv** [comment]
How to create Blob object from a JsonObject? Thanks
