### ISSUE TITLE
Export .xls with image

### ISSUE THREAD

**Issue by YanBlochSergata** [eligrey/FileSaver.js#121]
Hey,

I'm using FileSaver to save table data as .xls file,
I would like to know if there is a way to save an image on the .xls file?

**Comment by eligrey** [comment]
I know nothing about rendering xls to an image. Please try asking this on [StackOverflow](https://stackoverflow.com/). This is an issue tracker, not a user forum.

**Comment by YanBlochSergata** [comment]
It's OK, I found that if you use an IMG with a SRC from the web, the IMG will be rendered to the XLS.

Example:
<img src="http://carambo.la/images/logo-carambola_rev.png" alt="" />
