### ISSUE TITLE
It does not work on android browser

### ISSUE THREAD

**Issue by aahedi** [eligrey/FileSaver.js#124]
When I tried http://eligrey.com/demos/FileSaver.js/ in android it does not work and canvas image does not support touch screen.

**Comment by rubensayshi** [comment]
as of android 5.0 the default (and only) browser is now chrome, which works perfectly

but android 4.x and lower comes with the old stock android browser, which does not work :(

**Comment by rubensayshi** [comment]
@eligrey would it be something desireable to add a function that returns true/false wether or not your browser supports downloading?

**Comment by v-python** [comment]
Firefox also exists on Android, @rubensayshi

**Comment by arunxavy** [comment]
On saving just a black image is shown on Samsung Galaxy tab(GT-P3100), chrome 50.0.2661.89 , Android 4.1.2 , but image is not corrupted I think. Why might be this ?

**Comment by aahedi** [comment]
I think filesaver.js is part of the future of javascript. I hope eventually it will work fine in all browsers. May all browsers will support filesaver.js

**Comment by jimmywarting** [comment]
What Android OS/Browser version do you have problem with saving?
canvas could be solved with touch support.

**Comment by Zeroxk** [comment]
Using the demo site on android 4.3 stock browser gives a "webpage not available: The webpage at filesystem:https://eligrey.com/temporary/saved/a_rich_document.xhtml.download..." same error message on all 3 download types

Android 4.4.2 stock browser via bluestacks emulator gives "download failed" with a log error like "W/DownloadManager( 2059): Aborting request for download 50: java.net.UnknownHost
Exception: Unable to resolve host "blob": No address associated with hostname"

**Comment by jimmywarting** [comment]
hmm, the demo use a old version, the filesystem has been wiped out and isn't used anymore.

@eligrey could you updating the demo?

**Comment by slowWriting** [comment]
Using Android 6.0.1 with Android Stock Brower, when I try to save attachment I get message "Only http or https Web addresses can be downloaded." But on Chrome it works okay.

Additionally on Chrome download link is starting with "blob:http://localhost/<filename>", but in IE it's just "blob:<filename>"

**Comment by slowWriting** [comment]
I have debugged library and on Android Browser it is creating url 
"blob:http%3A//10.76.37.68/064e82b5-ce86-4962-a226-fa60f7a0e332"
and on normal browser it's:
"blob:http://localhost/e155f4a6-7357-4753-902b-6bded6568e18"


_object_url = get_URL().createObjectURL(blob);
console.log(object_url); //debug line_

**Comment by yavorskiy-web** [comment]
@slowWriting do you find solution of this problem?

**Comment by slowWriting** [comment]
We have removed the browser from supported web browsers on Android. It 
seems it was a problem in browser api. As far as I know it should work 
on newer versions.

------ Wiadomość oryginalna ------
Od: "Oleg" <notifications@github.com>
Do: "eligrey/FileSaver.js" <FileSaver.js@noreply.github.com>
DW: "slowWriting" <regulski.maciej@gmail.com>; "Mention" 
<mention@noreply.github.com>
Data: 07/06/2017 16:52:39
Temat: Re: [eligrey/FileSaver.js] It does not work on android browser 
(#124)

**Comment by Ruffio** [comment]
Is this still an issue?

**Comment by shikelong** [comment]
+1. Is Anyone know how to fix it?

**Comment by Ruffio** [comment]
Can this be closed?
