### ISSUE TITLE
Event Handlers in Chrome

### ISSUE THREAD

**Issue by AChusuei** [eligrey/FileSaver.js#125]
This is more of a question than an issue per se, but I was wondering if FileSaver's event handlers were working? I tried setting those up, but the onwriteend event trigger didn't not run anything when the file finished downloading.

**Comment by eligrey** [comment]
Unfortunately `onwriteend` can not be implemented in the `<a download>`-based code, as the DOM provides no method to tell when a file has finished downloading. Sorry.

`onwriteend` does work with the web filesystem code, but that code also uses more disk space and memory, so the more efficient code is attempted first.
