### ISSUE TITLE
Check if file was saved and not aborted

### ISSUE THREAD

**Issue by Z3roCoder** [eligrey/FileSaver.js#126]
Is there a current way to check if the user really DID save the file and not click cancel after the saveAs window opened?

**Comment by Kestutis** [comment]
any news on this one?

**Comment by jimmywarting** [comment]
It's not possible atm

**Comment by chancesmith** [comment]
Is there a way to create a promise on completion?

**Comment by jimmywarting** [comment]
Still not possible - it's only going to be possible with [StreamSaver](https://github.com/jimmywarting/StreamSaver.js)

**Comment by Ruffio** [comment]
If this is still not possible (after 2 years) it should be considered to close this issue, as it can't be implemented.
