### ISSUE TITLE
Bower invalid (missing?) metadata

### ISSUE THREAD

**Issue by rpavlik** [eligrey/FileSaver.js#127]
FileSaver is in the Bower package repository, but I get these messages when running `bower install FileSaver`:

```
bower not-cached    git://github.com/eligrey/FileSaver.js.git#*
bower resolve       git://github.com/eligrey/FileSaver.js.git#*
bower checkout      FileSaver#master
bower invalid-meta  FileSaver is missing "main" entry in bower.json
bower invalid-meta  FileSaver is missing "ignore" entry in bower.json
bower resolved      git://github.com/eligrey/FileSaver.js.git#24b303f492
bower install       FileSaver#24b303f492
```

I'm not anywhere near an expert in the matter, but I think you could add a `bower.json` file to the repository to fix this. As is, I have to add this to my `bower.json` file for `grunt-bower-tasks` to install it correctly:

```json
    "FileSaver": {
      "js": "*.js"
    }
```

**Comment by nkint** [comment]
+1

**Comment by devinivy** [comment]
+1!

**Comment by nandinga** [comment]
+1
eligrey/FileSaver.js#109

The thing is that bower requires the use of semantic versioning. Maybe "2014.11.29" could be a solution that satisfies all?

**Comment by laurafg** [comment]
+1!

**Comment by grempe** [comment]
I have created a pull request for the bower.json file along with instructions for each step needed for @eligrey to make a release with a git tag and to complete the registration with bower.io.

I set the version number at the first semver version which is 0.0.1.

Note this also needs to be done for the Blob repo.

**Comment by jimmywarting** [comment]
git tag and bower has been added
