### ISSUE TITLE
problem saving images

### ISSUE THREAD

**Issue by fattynoparents** [eligrey/FileSaver.js#128]
I was trying to save data as .xhtml like this:

var myDiv = jQuery('#divToSave');
var blob = new Blob([xml_serializer.serializeToString(myDiv[0])], {type: "application/xhtml+xml;charset=" + document.characterSet});	
saveAs(blob, document.title + ".xhtml");

Since there are also images in my data, I expected them to be displayed after opening the saved file, but instead I get this: 
![1](https://cloud.githubusercontent.com/assets/1287637/6144258/22a5b626-b1e6-11e4-9ffb-9347db5e7087.PNG)

The link is not broken though, and if I click on the picture it is displayed in a new window. But still there's no preview.
I asked stackoverflow about this matter http://stackoverflow.com/questions/28449751/how-to-save-images-and-text-with-filesaver-js , but got no reply. 
Maybe there's a way to deal with this problem? 
Thanks.

**Comment by cattleyavns** [comment]
Try my code with browser Scratchpad (Firefox, save a image file):

http://pastebin.com/8FXWZM6S

Run this code on "THIS PAGE", I use your avatar as target image.

**Comment by jimmywarting** [comment]
Close this
