### ISSUE TITLE
Please Tag a Release

### ISSUE THREAD

**Issue by jamesward** [eligrey/FileSaver.js#130]
Thanks!

**Comment by jivinivan** [comment]
:+1:

**Comment by lunarcloud** [comment]
:+1:

**Comment by eligrey** [comment]
It's a static API with the [date on the master branch](https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L3) being the current version. I've never made any breaking changes so you don't need any tags atm.

**Comment by lunarcloud** [comment]
No, it's a pain in the butt writing out the SOUP (software of unknown providence, basically third-party) forms for FDA using the sha1 of the commit I grabbed master from as the version number. I'd rather use a real version number and regulatory isn't going to accept your solution.

**Comment by eligrey** [comment]
You can fork and tag the current release as `1.0.20150304`.
