### ISSUE TITLE
Code readability

### ISSUE THREAD

**Issue by lyschoening** [eligrey/FileSaver.js#132]
I do not want to sound pedantic — a lot of work has clearly gone into making this work with different browsers and I very much appreciate what has been done. 

The thing is, the code is not very readable. All the multi-line vars, `||` concatenations, and shorthand variable names make the code very hard to interpret (and with very little gain, given that you ship a minified version). The code should be refactored.

**Comment by eligrey** [comment]
Ok, create a PR.
