### ISSUE TITLE
Xlsx file save issue

### ISSUE THREAD

**Issue by ivanVeremeychuk** [eligrey/FileSaver.js#133]
Hello, I am using this code 
```javascript
var octetStreamMime = "application/octet-stream";
var filename = title + '.xlsx';

var blob = new Blob([data], { type: octetStreamMime  });
saveAs(blob, filename);
```
In safari 5.1.7 for windows, it don't work.
data - its a binary data from server;

Could you explain me what I am doing wrong?

**Comment by hanssnabilie** [comment]
Hi Ivan,

Just a heads up; safari for windows has not been updated since 2012 and apple has dropped support in 2013. Perhaps you should do the same?
