### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by checkhavoc** [eligrey/FileSaver.js#135]
After running: npm install browser-filesaver

Then running my app, I'm running into the following error in ../node_modules/browser-filesaver/FileSaver.js:28

doc = view.document
		            ^
TypeError: Cannot read property 'document' of undefined

Is anyone else having this issue? Or knows how to resolve it? My app isn't actually executing saveAs just yet, all I am doing is loading up my app after the install and that is when I run into the error (saveAs will not have a document yet, because I'm not trying to save anything just yet).

Any help would be appreciated, thanks!

**Comment by checkhavoc** [comment]
Resolved: I just added a condition before the var attempts to be set:

if (view === undefined)
return;

Thanks

**Comment by chip** [comment]
I'm also having this issue, but haven't found a fix for it yet.

**Comment by eligrey** [comment]
In the same environment that you are getting this issue, what is the value of `self`?

**Comment by HorzaGobuchul** [comment]
Just for the record, in case someone faces the same issue while writing a firefox extension.

The problem does, indeed, come from *self*. Removing all references to it corrected the issue.

**Comment by checkhavoc** [comment]
Yes removing all references corrected the issue, thanks.
