### ISSUE TITLE
Problem saving in chrome Version 42.0.2311.90 m with FileSaver 2015-03-04

### ISSUE THREAD

**Issue by siva3378** [eligrey/FileSaver.js#143]
Im trying to save ms word file using FileSaver. But I'm getting following error at "get_URL().createObjectURL"

<code>
Error: [ABC] get_URL(...).createObjectURL is not a function
TypeError: get_URL(...).createObjectURL is not a function
    at new FileSaver (http://localhost:8080/web/src/js/libs/file-saver-saveas-js/FileSaver.js:129:28)
    at saveAs (http://localhost:8080/web/src/js/libs/file-saver-saveas-js/FileSaver.js:211:11)
    at http://localhost:8080/web/src/app/igl-services/igl.compilation.service.js:112:65
    at http://localhost:8080/web/src/js/libs/angular/angular.js:9369:11
    at processQueue (http://localhost:8080/web/src/js/libs/angular/angular.js:13189:27)
    at http://localhost:8080/web/src/js/libs/angular/angular.js:13205:27
    at Scope.$get.Scope.$eval (http://localhost:8080/web/src/js/libs/angular/angular.js:14401:28)
    at Scope.$get.Scope.$digest (http://localhost:8080/web/src/js/libs/angular/angular.js:14217:31)
    at Scope.$get.Scope.$apply (http://localhost:8080/web/src/js/libs/angular/angular.js:14506:24)
    at done (http://localhost:8080/web/src/js/libs/angular/angular.js:9659:47) undefined
</code>

I'm able to download in IE11 but not in chrome. After I try to get the window.url object in chrome console, I found in the normal browser window.URL.createObjectURL is avaliable but in my page(using angularJS) window.URL do not have createObjectURL method.

Means, FileSaver may not work with AngularJS apps. Please correct me If am I wrong.

**Comment by siva3378** [comment]
It happend because, My app has a global object "URL" which is actually overwriting window.URL object.

**Comment by tanmayrp** [comment]
Siva...I've run into the same issue. 
I don't have any global objects "URL" but I do use the URL method for ajax calls. Do you think that would have this behavior as well?

**Comment by eligrey** [comment]
This is a problem with AngularJS redefining `URL`. I cannot stop other libraries from breaking core functionality of my library, so it's up to AngularJS to fix it.

Please [file an issue for AngularJS](https://github.com/angular/angular.js/issues/new) if you want it fixed. Make sure to mention `eligrey/FileSaver.js#143` in your issue report.

**Comment by siva3378** [comment]
@tanmayrp I dont think it is a problem with AngularJS or any other library. It our own code overriding the URL object. What do you mean by "url method for ajax calls"?
Following code, watches exactly which code is overriding the main URL object. Keep this code in before all the script tags and run your app in browser, Check logs, I hope you can find the answer

    (function () {
        var _createObjectURL = window.URL.createObjectURL;
                Object.defineProperty(window.URL, 'createObjectURL', {
                set: function (value) {
                console.trace('set createObjectURL')
                        _createObjectURL = value;
                },
                        get: function () {
                        console.trace('get createObjectURL')
                                return _createObjectURL;
                        }
                })
                })();
                (function () {
                var _URL = window.URL;
                        Object.defineProperty(window, 'URL', {
                        set: function (value) {
                        console.trace('set URL')
                                _URL = value;
                        },
                                get: function () {
                                console.trace('get URL')
                                        return _URL;
                                }
                        })
                        })();

**Comment by tanmayrp** [comment]
Thanks for your help siva...
I meant the URL property for the Jquery Ajax function. That's the only explicit 'URL' in the code. 
I've added the code to execute before all the scripts. What is the expected behavior? 
I see several instances of:
get URLObject.defineProperty.get @ localhost/:34
and
set URLObject.defineProperty.set @ localhost/:29
in the browser's console window.

**Comment by tanmayrp** [comment]
Woo hoo! Fixed...There was an external file reference that did have a global object named URL.
Thanks Siva!!

**Comment by mukesh3521** [comment]
For me its working in I.E but nor in Google chrome , Because I have a Ajax Call in which I am setting the URL ..How to rectify this issue. As i am quite new to this technology .. So please suggest the Way out  .
