### ISSUE TITLE
File origin says blob: instead of the domain in Firefox

### ISSUE THREAD

**Issue by filipkral** [eligrey/FileSaver.js#145]
In Firefox (37.0.2 on Windows 7) the file save dialogue that comes up says "blob:" in the "from" field. This happens in the demo pages too http://eligrey.com/demos/FileSaver.js/ 
Minor issue but it would be nice to fix so users don't get confused.

**Comment by cy** [comment]
+1
<img width="461" alt="screen shot 2015-07-31 at 11 01 02 am" src="https://cloud.githubusercontent.com/assets/1314446/9011140/59b51846-3779-11e5-950a-4355d84da282.png">

**Comment by AndresLavasoft** [comment]
I have the same issue, is there any way to change the "from" value?

**Comment by jimmywarting** [comment]
Should be reported to bugzilla, nothing we can control
