### ISSUE TITLE
Large images save as blank pngs in Chrome

### ISSUE THREAD

**Issue by jonroberts** [eligrey/FileSaver.js#155]
I have an odd situation that's mystifying me. When I save a large canvas in Chrome I get a blank .png.

This is different from the previous ticket with similar details (https://github.com/eligrey/FileSaver.js/issues/54)

• smaller images still save out. Basically if the final .png is under 8.4Mb it saves. Specifically, if I shrink the dimensions of the canvas incrementally, it goes from saving a blank .png to saving the image as expected.
• the save works just fine in Firefox (38.0.5), and the output is an 8.5Mb png with dimensions 4200 × 2050

I'm using the standard canvas save functionality:

    c.toBlob(function(blob) {
	    saveAs(blob, "map_"+mapID+".png");
	});

The canvas is populated using common and garden javascript. The images in the canvas are loaded from a separate fileserver, but with the proper CORS permissions - and I don't think that can be the issue given that a slightly smaller version of the same export works fine.

I'm using 43.0.2357.130 (64-bit) on a MacBook Pro.

What can I do to help chase this down? Is there a Chrome timeout or something that's killing the export?  It's mystifying me.

**Comment by tdeo** [comment]
Hi,

I have the same issue there. I'm basically concatenating several images from Google Maps to create an HD map of a part of the world. When I increase progressively the number of images in my canvas to get higher quality, at one time, the downloaded file appear as a blank PNG. 
The limit is at ~200Mo with chrome, but I can go further with Firefox.

I'm using Chrome 46.0.2490.86 64-bit on a MacBook Pro too.

**Comment by jimmywarting** [comment]
Given the time that has passed I think we can close this. This is more of a canvas/browser limitation rather then having anything to do with FileSaver. FileSaver is well compilable of saving large files.

What would happen if you try to render the canvas in a `<img>` tag? do you still see the picture? I guess not. 
Any code to reproduce it like a jsfiddle would help if you want us to help you
