### ISSUE TITLE
Can we save it to sever ?

### ISSUE THREAD

**Issue by dhavalkakkad** [eligrey/FileSaver.js#158]
Hi there,

I just used this, looks cool. All I need is want to save it on my server so I can process it further. Is it possible?

**Comment by Londran** [comment]
Well... you would not need FIleSaver.js for that I guess. Use AJAX or https://developer.mozilla.org/de/docs/Web/API/XMLHttpRequest would be more what you want, I guess.

Best regards,
Londran.
