### ISSUE TITLE
Can I save as UTF-8 Without BOM?

### ISSUE THREAD

**Issue by rhyous** [eligrey/FileSaver.js#160]
I am using the example:

var blob = new Blob(["Hello, world!"], {type: "text/plain;charset=utf-8"});
saveAs(blob, "hello world.txt");

I am replicating a historical system in a modern system. This downloaded as UTF-8. The Xml generated via the historical system saves as UTF-8 without BOM. I need it to be exactly the same encoding as the Xml I am trying to replicate.

**Comment by eligrey** [comment]
Yeah, I just added a `no_auto_bom` argument to saveAs. Use `saveAs(blob, name, true)` to turn off the auto-BOM stuff.

**Comment by rhyous** [comment]
Thank you so much. I didn't realize the legacy system needed UTF-8 without BOM until the Xml didn't work and we scrambled to find the difference between the new system and the legacy system.

**Comment by eligrey** [comment]
Glad I could help.

**Comment by rhyous** [comment]
By the way. I tested it and can verify that it works. Notepad++ now shows the downloaded file encoding as UTF-8 without BOM.

**Comment by eForce90** [comment]
Thanks a lot!

**Comment by v2tran** [comment]
in case as export with chinese languages you will have problem about font.
