### ISSUE TITLE
supporting Edge

### ISSUE THREAD

**Issue by v-python** [eligrey/FileSaver.js#162]
I asked a Win-10-preview-edition friend to test FileSaver.js on Edge, and the demo worked. Edge is not in the browser list.

I'm curious if it works due to IE compatibility? some other browser compatibility? HTML5 support?

But anyway, it works.  

The User Agent string in Edge seems to claim compatibility with everything except IE to attempt to convince sniffers it is a "good guy" it would seem... groan. A new round of sniffers will have to be written, carefully. Hence, my wonder about if it works due to some other browser compatibility.

**Comment by jimmywarting** [comment]
It's in the list now.
It works thanks to `a[download]` or `msSaveOrOpenBlob()`. It's not due to IE compatibility.
