### ISSUE TITLE
Save Blob as SVG file inserts 3 strange bytes of unknown origin into file

### ISSUE THREAD

**Issue by katzlbt** [eligrey/FileSaver.js#164]
When I save a blob to an SVG file with the following code ... 
3 extra bytes ("ï»¿") appear in the file at position 0..3 (jEdit encoding UTF-8). When the chars are deleted the file works.

Where do these bytes come from?! (tested with Chrome and Firefox)

    var data = document.getElementById('scale').innerHTML;
    // Data is correct here: data.substring(0,5) ... "<svg "  
    var blob = new Blob([ data ], {type: "image/svg+xml;charset=utf-8"});
    saveAs(blob, "arrow.svg");

**Comment by dinglioutlook** [comment]
These three bytes are UTF-8 bom head;

**Comment by katzlbt** [comment]
There is no such thing as a UTF-8 BOM. Only UTF-16 and UTF-32 can have a BOM. Where did you find that UTF-8 should have a BOM?

http://unicode.org/faq/utf_bom.html#gen6

**Comment by tmedwards** [comment]
A UTF-8 file or stream can contain the BOM sequence (from the same FAQ you linked: [Can a UTF-8 data stream contain the BOM character (in UTF-8 form)?](http://unicode.org/faq/utf_bom.html#bom5 "http://unicode.org/faq/utf_bom.html#bom5")).

You are correct that the BOM has no intrinsic meaning within UTF-8.  When it occurs, its only purpose is to act as a signature, indicating that the file/stream is UTF-8 encoded.  As you've noticed, however, that usage is problematic as it can interfere with software which doesn't expect the signature.

It's use in UTF-8 files/streams is largely a Microsoft-ism.

**Comment by katzlbt** [comment]
Maybe FileSaver should get a OO interface, my suggestion would be:

    var fileSaver = new FileSaver(dataString, "image/svg+xml;charset=utf-8", "file.txt");
    fileSaver.setData(dataString, "image/svg+xml;charset=utf-8");
    fileSaver.setFilename("file.svg");
    fileSaver.addUTFByteOrderMarkerBE();
    fileSaver.save();

    var fileSaver = new FileSaver();
    fileSaver.setBlob(blob);
    fileSaver.setFilename("file.gif");
    fileSaver.addUTFByteOrderMarkerLE();
    fileSaver.save();

    var fileSaver = new FileSaver(dataStringOrBlob, "file.svg" [, "image/svg+xml;charset=utf-8"]);
    fileSaver.save();

**Comment by eligrey** [comment]
Use `saveAs(blob, name, true)` to turn off the auto-BOM stuff. It's a dirty hack, but what else can I do when browsers are completely dropping the charset information from blogs?

I realize that I should probably have documented this in the readme for all of you, so I will be doing that now.

**Comment by vigneshksaithal** [comment]
I tried `saveAs(blob, 'filename.svg', true)` but the file isn't saved as SVG.
