### ISSUE TITLE
Saving multiple files

### ISSUE THREAD

**Issue by yehudahkay** [eligrey/FileSaver.js#165]
Hi,

I tried saving multiple files in Chrome with 
```
for (i = 0; i < files.length; i++) {
var blob = new Blob([files[i].data])
saveAs(blob, files[i].fileName)
}
```
however it downloads the first file multiple times.

Doing this worked fine
```
for (i = 0; i < files.length; i++) {
var blob = new Blob([files[i].data])
if (navigator.appVersion.toString().indexOf('.NET') > 0)
                    window.navigator.msSaveBlob(blob, fileName)
else {
var a = document.createElement("a")
document.body.appendChild(a)
a.style = "display: none"
a.href = window.URL.createObjectURL(blob)
a.download = files[i].fileName
a.click()
}
}

Any solution? Thanks!

**Comment by melnikaite** [comment]
+1

**Comment by Hypercubed** [comment]
Yes, I just discovered this.  If you try to download multiple files it will only download one.  I think it's because the setTimeout here https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L146 reuses the save_link element.
.

**Comment by melnikaite** [comment]
No, it's because of old issue in chromium https://code.google.com/p/chromium/issues/detail?id=162212

**Comment by Hypercubed** [comment]
@melnikaite That may be a separate issue.  The code @yehudahkay posted (and the code I tested) loops over several blobs and calls `saveAs` on each.  If you look here: https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L146 you will see that the `href` and `download` attributes for the `save_link` element is set then `setTimeout` is called.  By the time the `setTimeout` callback is invoked  `href` and `download` have been overwritten multiple times and only the last file is downloaded.

The patch submitted (https://github.com/Hypercubed/FileSaver.js/commit/04f232f658b0d70cad0a2bebf5a514de2deab40a) fixes this issue by moving the setting `href` and `download` into the `setTimeout` callback.  See here: http://plnkr.co/edit/rVuId9?p=info (saveAs is used indirectly).

**Comment by Hypercubed** [comment]
Also notice that @yehudahkay working example doesn't use `setTimeout`.

**Comment by endavid** [comment]
This works in Chrome, but it's still not working in Safari. It only downloads the last file. Tested on Safari 12.0.3 (14606.4.5).
