### ISSUE TITLE
FileSaver with mdg:camera 

### ISSUE THREAD

**Issue by YouSour** [eligrey/FileSaver.js#170]
hi , i want to use FileSaver with mdg:camera package , is it possible or not ? and i don't know how to save image by using FileSaver js ? i hope you can help me .

**Comment by jimmywarting** [comment]
in the [callback(error, data)](https://github.com/meteor/mobile-packages/tree/master/packages/mdg:camera#callbackerror-data) you will get back a base64-encoded data URI for the image taken by the camera

So what you would have to do is to convert it to a blob first before trying to save it.

Something like

```javascript
MeteorCamera.getPicture([options], function(error, base64){
	saveAs(b64toBlob(base64), 'image.jpg')
})


function b64toBlob(b64Data, contentType, sliceSize) {
	contentType = contentType || ''
	sliceSize = sliceSize || 512
	
	var byteCharacters = atob(b64Data)
	var byteArrays = []
	
	for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
		var slice = byteCharacters.slice(offset, offset + sliceSize)
		
		var byteNumbers = new Array(slice.length)
		for (var i = 0; i < slice.length; i++) {
			byteNumbers[i] = slice.charCodeAt(i)
		}
		
		var byteArray = new Uint8Array(byteNumbers)
		
		byteArrays.push(byteArray)
	}
	
	return new Blob(byteArrays, {type: contentType})
}
```

There may be alternative methods to get a blob directly
Some mobile browser opens the camera app just from: `<input type="file" accept="image/*" capture="camera">` from there you can listen for change event and get a blob directly from `input.files[0]`
