### ISSUE TITLE
Quality loss

### ISSUE THREAD

**Issue by Nialcen** [eligrey/FileSaver.js#171]
Hello, first of all, great work, this is wonderfull.

However, I have a small Issue : http://www.tree-of-savior.fr/simulateur-de-personnage/

As I click the last " TELECHARGER LA SIGNATURE" the .png result loose quality.

I use : 

function exportSign() { 

		html2canvas(jQuery("#signBack"), {
            onrendered: function(canvas) {
                theCanvas = canvas;

                canvas.toBlob(function(blob) {
                    saveAs(blob, "SignatureFromTOSFrance.png"); 
                });
            }
        });
};

Any idea ?

Best regards

**Comment by jimmywarting** [comment]
I'm pretty sure this has nothing to do with filesaver.js at all... Try using different canvas export params

    canvas.toBlob(function(blob){...}, "image/jpeg", 0.95); // JPEG at 95% quality

**Comment by jimmywarting** [comment]
Think we can close this
