### ISSUE TITLE
Would be useful to have versions on this project

### ISSUE THREAD

**Issue by idautocfator** [eligrey/FileSaver.js#173]
The version on http://eligrey.com/demos/FileSaver.js/ (works with Safari) is different than the latest (does not work with Safari) and I'm having a heck of a time trying to figure out how to get this working in Safari.

**Comment by darkmavis1980** [comment]
Yeah, not having a version is a bit of a (big) problem here

**Comment by silentHoo** [comment]
+1

**Comment by mpmlj** [comment]
+1

**Comment by jimmywarting** [comment]
I have started to create release tags here on github and npm
