### ISSUE TITLE
Question: Isn't it safe to remove filesystem?

### ISSUE THREAD

**Issue by jimmywarting** [eligrey/FileSaver.js#174]
All browser out there that has filesystem api also has download attribute?

**Comment by eligrey** [comment]
Yeah, probably safe now. I'll do it next week, but if you want to do it now please use a pullreq and don't just commit immediately. It's a significant portion of the code and I'll want to review it to make sure we're all good.

**Comment by jimmywarting** [comment]
I can make a pull request on friday or the weekend

**Comment by eligrey** [comment]
Thanks, sounds good :)
