### ISSUE TITLE
Add project to NPM to use it with browserify or webpack

### ISSUE THREAD

**Issue by AmberDeBlack** [eligrey/FileSaver.js#177]

**Comment by marksteve** [comment]
:+1:

**Comment by stbaer** [comment]
:+1:

**Comment by DanlanNZ** [comment]
:+1: [this](https://www.npmjs.com/package/filesaver.js) has been added but it is out of date

**Comment by creage** [comment]
I'd like to see it available at bower as well, please.

**Comment by alexblunck** [comment]
+1

**Comment by xwartz** [comment]
+1

**Comment by stbaer** [comment]
man, it's not so hard so support this

**Comment by felixfbecker** [comment]
```sh
npm init
npm publish
```

**Comment by DanlanNZ** [comment]
I ended up forking and creating an updated package instead https://www.npmjs.com/package/filesaverjs

**Comment by connor4312** [comment]
Please add this :+1:

**Comment by brendannee** [comment]
:+1:

**Comment by eligrey** [comment]
It's MIT licensed so you can easily upload any version to npm, as long as you are willing to maintain the npm metadata for your npm entry. I don't usually include support for specific package managers in my projects.

You can also just use git submodules to easily keep in sync me with me. This is a very useful feature, and I hope you all understand that GitHub itself is a fine package manager for git projects. I'm not stopping any of you from using npm. I just prefer to use GitHub.

**Comment by connor4312** [comment]
This is extremely disappointing.

npm is _the_ package manager for JavaScript -- you don't have to support "specific package managers", only one! It's not an either-or situation when using npm versus GitHub. Every single major npm package (further, I would claim every noteworthy open source JavaScript library) uses GitHub and npm together.

While there is nothing stopping others from publishing a fork to npm, doing so significantly increases the chance of it the package becoming abandoned and makes it more difficult to find. Submodules have long been considered a poor way to manage dependencies.

npm has been the best practice for package management in JavaScript for years now. It's very unfortunate to see a project such as this willfully deny its use.

**Comment by felixfbecker** [comment]
@eligrey When using submodules, you don't have semver. You always have a specific commit in your code. Lets say you release a patch that fixes a bug, no bc breaks. I would not get that patch automatically (unlike npm). I would have to see "oh, there is an update" and then check manually on GitHub changelog if it has bc breaks. At that point it's not better than downloading js files manually.
