### ISSUE TITLE
licence with X11 or MIT

### ISSUE THREAD

**Issue by LeaYeh** [eligrey/FileSaver.js#178]
hi, we are cdnjs team and we want to add your project to that.
but we need licence info clearly, 
i'm confused that https://github.com/eligrey/FileSaver.js/blob/master/LICENSE.md look like `MIT` licence,
but in [this file](https://github.com/eligrey/FileSaver.js/blob/f23c4a66dc9fa1af818322f08eb29a371ccb4ccf/FileSaver.js#L6) it said `X11/MIT`

could you plz tell me which licence this project used? thanks.

**Comment by eligrey** [comment]
Just MIT.

**Comment by LeaYeh** [comment]
thank you :)
