### ISSUE TITLE
FileSaver opens blank tab on Chrome for iOS

### ISSUE THREAD

**Issue by Faison** [eligrey/FileSaver.js#179]
Hi there,

I'm running into an issue while using this on Chrome for iOS: when the FileSaver.js code is called to save the blob from a canvas, a new tab is opened, but it's blank. The code is fairly similar to the project's demo code, except it runs on a 'click' event instead of a 'submit' event.

You can replicate this issue by doing the following:

1. Put the demo code from the project (here: https://github.com/eligrey/FileSaver.js/tree/master/demo) onto a web server (local or other).
2. On an iPhone in Chrome, go to that demo page
3. Tap on the canvas a few times to make some dots
4. Click the "Save" button.

The thing that's strange, though, is that the demo at http://eligrey.com/demos/FileSaver.js/ works for chrome on iOS. So there appears to be something breaking the saving on Chrome for iOS in the version that the demo loads in.

This code is pretty above my head, otherwise I'd help look into this, so I'm hoping you guys can help me figure this out.

Thanks,
Faison

**Comment by alferov** [comment]
I have the similar issue.
I've uploaded example on gh-pages: http://alferov.github.io/filesaver-ios-issue/
It uses the latest code from both Filesaver and Blob projects.

**Comment by Faison** [comment]
Hi @eligrey ,

Understandable. I could take a crack at it, but I'll need some direction. Do you have any initial thoughts of where in the code this issue could stem from? Any starting points would help me greatly.

Thanks,
Faison

**Comment by Hypocrite** [comment]
Any updates to this problem?

Safari is still opening files in a new tab with blob:// in the address bar.

Plain text files are displayed in the tab but for example .xls files show just a blank tab.

**Comment by RedShift1** [comment]
Experiencing the same problem here in both my own code and the supplied demo.

**Comment by arunxavy** [comment]
same issue here, this is what I have done but not the better way.

```
if(!navigator.userAgent.match('CriOS')){
                canvas.toBlob(function (blob) {
                saveAs(blob, "screen.png");

           } );
               
           }else{
               //for chrome in apple devices
                   var a = document.createElement('a');
                   a.href = canvas.toDataURL();
                   a.download = 'screen.png';
                   a.target='blank';
                   a.click();   
           }
```

**Comment by ph4r05** [comment]
Notes from my debugging:
 - Chrome iOS (CriOS) does not support opening ObjectUrls. It gives empty page.
 - This was already discussed on [Google Forums](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-html5/RKQ0ZJIj7c4) without success, just workaround
 - Workaround was published on [Stack Overlow](http://stackoverflow.com/questions/24485077/how-to-open-blob-url-on-chrome-ios). Here is slightly modified version that worked for me. It uses datalinks.

```javascript
var reader = new FileReader();
var blob = new Blob(['Hello world'], {type: 'plain/text'});
reader.onload = function(e){
  var bdata = btoa(reader.result);
  window.location.href = 'data:' + blob.type + ';base64,' + bdata;
}
reader.readAsDataURL(blob);
```

 - It is still a workaround, Chrome iOS does not download the file. It opens it in the tab.
 - `data:attachment/file` did not work for me. CriOS shown file for download, but with download error. After pressing download again button, error again.
 - `data:application/octet-stream` worked even if real type was `image/png`, image was still shown.
 - This workaround may have problems with big files. Even files slightly over 1MB take some time to load in the tab.
 - I've submitted a pull request #240

**Comment by jimmywarting** [comment]
@ph4r05 nice research

**Comment by koop4** [comment]
I still face the problem on IOS for pdf file, has it actually been solved?

**Comment by Ruffio** [comment]
@koop4 If you read the README.md then you will know the answear to your question:
![image](https://user-images.githubusercontent.com/1877612/53642356-e71cd000-3c31-11e9-826c-689b5484e404.png)

**Comment by Timoostrich** [comment]
Looks like there is still no good workaround for this, isn't it?

**Comment by nhs047** [comment]
We are facing the same issue. Is there any update at FileSaver for CrIOS (Chrome IOS - IPAD)?
