### ISSUE TITLE
Setting MIME type to "application/json" just ends up setting the MIME type to "application/octet-stream"

### ISSUE THREAD

**Issue by soops** [eligrey/FileSaver.js#180]
I'm attempting to create a save/load feature for my webapp, and to hash data I'm using JSON.

```javascript
save = new Blob [JSON.stringify(jsonObject)], {type: "application/json;charset=utf-8"}
saveAs save, $("#title").val() + ".esma"
```

When opening the file, the MIME type is always `application/octet-stream`. Why is this?

**Comment by eligrey** [comment]
In what browser?

**Comment by soops** [comment]
Chrome

**Comment by eligrey** [comment]
Sorry forgot to ask, and what operating system as well?

**Comment by soops** [comment]
Windows 10

**Comment by eligrey** [comment]
Neither NTFS, exFAT, or FAT32 (the filesystems Windows supports) store MIME media types. Windows relies entirely on filename extensions for opener associations. The only file systems that store MIME media types are: f2fs (Linux), ext3/ext4 (Linux), HFS+ (OS X), ZFS (Linux & OS X), and a many other less-popular filesystems (none of which are supported by Windows). Windows discards MIME media types prior to saving.

If you want to view your JSON output directly in your browser on Windows, you should rename the filename extension to `.json`.
