### ISSUE TITLE
Can't open pdf after saveAs

### ISSUE THREAD

**Issue by DevQueen** [eligrey/FileSaver.js#186]
I am trying to use FileSaver to create a pdf of my View using Angular.  It seems to work until I attempt to open the generated pdf at which time I am told that the file is corrupt.  Here is my code:

 $scope.export = function (format) {
        debugger;
        switch (format) {
            case '0':
                
  var blob = new Blob([document.getElementById('exportable').innerHTML], {
                type: "application/pdf"
            });
        saveAs(blob, "Report.pdf");
                
                break;
            case '1':
                 var blob = new Blob([document.getElementById('exportable').innerHTML], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
        });
        saveAs(blob, "Report.xls");
                break;

        };
    };

The Excel export works beautifullly.  It looks EXACTLY like it does in the view.

**Comment by jimmywarting** [comment]
Seems related to #183

**Comment by DevQueen** [comment]
When I try to use the code you suggested, I get the error "toPdf is undefined".

**Comment by jimmywarting** [comment]
That's because it is... you have to make sure it's in a pdf format yourself. convert it from one type to another. i don't know what your data looks like.

**Comment by DevQueen** [comment]
My data looks like this:

<div class="panel panel-primary">
    <div class="panel-body">
        <div id="exportable">
             
                    <table id="myTable" style="width:100%">
                        <thead>
                            <tr style="background-color:#003A5d; color:white">
                                <th colspan="4">Scoring Set</th>
                            </tr>
                        </thead>
                        <tbody style="font-size:12px">
                            <tr style="font-size:13px; background-color:#e0f4fd">
                                <td colspan="4">
                                    {{::scoredetails.vchScoringSetName}}
                                </td>
                            </tr>
                            <tr style="background-color:#cfe7f1; font-size:12px; text-align:center">
                                <td>Total Score</td>
                                <td>Max Score</td>
                                <td>Rank</td>
                                <td>Overridden</td>
                            </tr>
                            <tr style="text-align:center">
                                <td>{{scoredetails.intNumericalScore}}</td>
                                <td>{{scoredetails.intMaxPossibleScore}}</td>
                                <td style="color:white" ng-style="{'background-color': set.vchCurrentRankingColor}">{{scoredetails.vchCurrentOperatorRanking}}</td>
                                <td>{{scoredetails.Overridden || 'false'}}</td>
                            </tr>
                        </tbody>
                    </table>
               
                <br />
           
                    <table id="myTable2" style="width:100%">
                        <thead>
                            <tr style="background-color:#003A5d; color:white">
                                <th colspan="4">Scoring Grid</th>
                            </tr>
                        </thead>
                        <tbody style="font-size:12px">
                            <tr style="font-size:13px; background-color:#e0f4fd">
                                <td colspan="4">
                                    The grid below contains this contractor's scores for each scoring item in this scoring set.
                                </td>
                            </tr>
                            <tr style="background-color:#cfe7f1; font-size:12px; text-align:center">
                                <td>Score Awarded</td>
                                <td>Scoring Item Description</td>
                                <td>Date Scored</td>
                                <td>Contractor Answer</td>
                            </tr>
                            <tr style="text-align:center" ng-repeat="result in scoreresults">
                                <td>{{result.intScore}}</td>
                                <td>{{result.vchDescription}}</td>
                                <td>{{result.dteDateCalculated}}</td>
                                <td>{{result.vchQuestionAnswer}}</td>
                            </tr>

                        </tbody>
                    </table>
               
        </div>
    </div>
</div>

I guess I'm confused because I thought that FileSaver would convert the file to PDF just like it did to Excel.  So basically, you're saying that I have to find something else to convert the file to a PDF and FileSaver will just save it.

**Comment by jimmywarting** [comment]
Correct, FileSaver just saves a file.
FileSaver dosen't alter the content

**Comment by DevQueen** [comment]
Okay, thanks for your speedy reply.  It's back to the drawing board for me.

**Comment by evilaliv3** [comment]
related to https://github.com/eligrey/FileSaver.js/issues/219

**Comment by eligrey** [comment]
FileSaver will not automatically convert your HTML to PDF. Use [jsPDF](https://github.com/MrRio/jsPDF) for PDF creation in JavaScript.
