### ISSUE TITLE
Accents with weird caracters (Solved)

### ISSUE THREAD

**Issue by fretelweb** [eligrey/FileSaver.js#188]
I use 
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8
the page is also UTF-8 but when I save the table it show weird caracters instead of accents also ñ letter 

---
Fixed with
<pre>
Excel.$inject = [];
function Excel( ) {
   var header = '&lt;meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8"&gt;';
   return {
      tableToBlob: function (tableId) {
         // REQUIRE FILESAVER 1.1 GITHUB
         var blob = new Blob([header + document.getElementById(tableId).innerHTML], {
            type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
         });
         saveAs(blob, "reporte.xls");
      }
   };
}
</pre>

**Comment by Cdvalencia** [comment]
you must to use the next lines:

`var header = '<meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8">';
var blob = new Blob([header + document.getElementById('table2excel').innerHTML], {
    type: "data:application/vnd.ms-excel;charset=UTF-8"});
saveAs(blob, nombreExcel+".xls");`

**Comment by miguel4ngelc** [comment]
Great! it was helpful for me! thanks!
