### ISSUE TITLE
Not work with lumia!

### ISSUE THREAD

**Issue by laltroweb** [eligrey/FileSaver.js#193]
Hi,
i've integrated here: https://laltroweb.it/tools/password-generator/
## (is a pure javascript form - no php, so - filesaver is a good script for save string)

work with all my browser: chrome, firefox, ie and edge on windows 10, but not in lumia browser (is a ie mobile).

help or bugfix is must appreciated :)

regards,
S.N.

**Comment by jimmywarting** [comment]
Don't know anyone that has lumia/windows phone, so it would be hard.

**Comment by jimmywarting** [comment]
Found out that lumia browser has `msSaveOrOpenBlob()` with alert's but it doesn't do anything.
I couldn't see any console log

Seems related: https://stackoverflow.com/questions/29143660/view-a-javascript-blob-in-ie11-windows-phone-8-1

**Comment by laltroweb** [comment]
Ok, thank's for time on this!
Anyway, i think is a small percentage. Work as expected on desktop ;)

Kind regards,
S.N.

**Comment by zikicm** [comment]
I had the same problem, this module does not work on windows mobile + with using msSaveBlob I couldn't get any action. Does anyone has a clue what is happening?

**Comment by jimmywarting** [comment]
It's bad that they have msSaveBlob but it doesn't do anything. A exception would at least be useful... it's like calling `function noop(){}` and expect it to work!

**Comment by srihariv** [comment]
any update on the above, we are also kind of stuck trying to use msSaveBlob and the windows mobile would not respond.

or any alternative to the above solution.

**Comment by jimmywarting** [comment]
No solution yet. Streamsaver.js is a other method but it requires service worker which lumia don't support

**Comment by MartinHlavna** [comment]
Hello, I have created workaround for this problem, which degrades to use of `<a download>`.

**Comment by acmoles** [comment]
@MartinHlavna This issue is also present on Windows Mobile 8.1 IE 11, would it be possible to update the fix to include this user agent?

**Comment by Kukulkano** [comment]
I have this issue on Lumia, too (Windows Phone 8.1 and 10). Maybe the fix of MartinHlavna is available soon? Would be great :-)

**Comment by MartinHlavna** [comment]
@acmoles I have checked http://caniuse.com and it shows that IE 11 does not support download attribute on`<a>`. So I cannot use fallback that I did for Windows Phone 10. As i don't have device I cannot confirm it.

**Comment by Kukulkano** [comment]
Hi Martin, this is bad new. So there is currently no way to download a BLOB file from JS using the default webbrowser (IE) on Lumia? So sad :-(

**Comment by usecode** [comment]
My Solution for Windows Phone Ie Edge 15
```
      if (navigator.userAgent.match(/Windows Phone/i)) {
        let a = document.createElement("a");
        document.body.appendChild(a);

        a.href = window.URL.createObjectURL(blob);
        a.download = fileName;
        a.innerHTML = fileName;
        a.target = '_blank';
        a.click();
      } else {
        FileSaver.saveAs(blob, fileName);
      }
```

Tested on Windows Phone 10 Lumia 640 XL
Microsoft Edge 40.15063.414.0
Microsoft EdgeHTML 15.15063

**Comment by Ruffio** [comment]
@eligrey should support for Windows Phone be implemented? As I recall it there will be no more Windows Phones as MS has stopped production, so I guess that Windows Phone shouldn't be supported. Please consider to close this issue as a solution has been found.

**Comment by eligrey** [comment]
I'll merge a well-written PR, even though Windows Phone is out of support for Microsoft.

**Comment by Ruffio** [comment]
@usecode , @laltroweb do one of you care to create a PR or this? Else I think that the issue should be closed as the device is unsupported by MS and the market share is close to zero...

**Comment by Ruffio** [comment]
@eligrey I think this issue has expired. The market share for Windows Phone is non existent and there have been no response since June 2017...
