### ISSUE TITLE
File saves "unknown" name in Safari MAC.

### ISSUE THREAD

**Issue by vnod-ideas2it** [eligrey/FileSaver.js#194]
I have using Mozilla pdf viewer if user clicks downloads in safari It doesn't save pdf file.

But saves unknown name as text document.
I think this is bug.
Is there any ways to fix it?

**Comment by romain67** [comment]
Hello,
I have the same problem. Have you found any fix?

**Comment by eligrey** [comment]
No fix is possible. All you can do is [ask Apple to support the download attribute](https://bugs.webkit.org/show_bug.cgi?id=102914#add_comment).

**Comment by rodrigomurta** [comment]
Same problem here using Safari. Any clue on how to solve it?
