### ISSUE TITLE
running FileSaver in PhantomJs fails

### ISSUE THREAD

**Issue by yleviel** [eligrey/FileSaver.js#195]
Running saveAs

ERROR [phantomjs.launcher]: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/6044259D-89C8-4116-889C-6AE74FC166BA.dmp

ERROR [launcher]: PhantomJS crashed.

**Comment by ardi-n** [comment]
I had a similar issue while trying to use saveAs for dynamically generated CSV files in PhantomJS 1.9.x. PNG and SVG files I generated, on the other hand, were correctly opened by PhantomJS in new windows as old Safari did. 
However, after updating to 2.1.1, CSV download no longer crashes. Instead, PhantomJS throws an error on `new MouseEvent("click")` that is being discussed here: ariya/phantomjs#11289.

**Comment by dwightdegroff** [comment]
Curious on the status of this. The phantomJS issue reference was closed briefly, but the overall issue seems to remain. (I'm currently experiencing the "MouseEventConstructor is not a constructor" error running FileSaver 1.1.3 and PhantomJS 2.1.1).

**Comment by jFranciscov** [comment]
Is there any solution?

**Comment by golimarrrr** [comment]
Same here with FileSaver 1.3.6 and PhantomJs 2.1.1, but I guess it's a PhantomJs issue
