### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by davidchiew** [eligrey/FileSaver.js#197]
Browse to http://eligrey.com/demos/FileSaver.js/

Using Chrome

Url ends up saying https://_/demos/FileSaver.js/
and it says "This web page is not available"

**Comment by blunatic** [comment]
In case anyone else comes across this, it looks like the author commented on his personal site [here](https://eligrey.com/blog/post/saving-generated-files-on-the-client-side/) on 2/22/16:

> I am currently moving my sites to a new host, and some parts will be transferred in the next couple days. Please refer to the GitHub files in the meantime if you need access to the demo files.

**Comment by eligrey** [comment]
Back up
