### ISSUE TITLE
how to include the css style in the exported excel sheet

### ISSUE THREAD

**Issue by digish777** [eligrey/FileSaver.js#198]
how to include the css style in the exported excel sheet

**Comment by jimmywarting** [comment]
The title implies more to be a tutorial "How to do X" then a question. 
What you are asking seems to be to broad to give you acceptable answer. Some code that shows us what you are doing will be helpful.

Best answer i can give is: You have to embed the style into the excel sheet before saving it

**Comment by jimmywarting** [comment]
I figure you may already have found a way around it by now, so i'm going to close this
