### ISSUE TITLE
Img to my filesystem

### ISSUE THREAD

**Issue by davidcm86** [eligrey/FileSaver.js#199]
Hello,

Can I save my blob image into my file system?
Like in php can i copy my tmp image in wherever i want.

Thank you.

**Comment by tinaramsey87** [comment]
Not sure if this helps with what you're asking. Your question doesn't seem to be specific to FileSaver.
http://php.net/manual/en/imagick.writeimage.php

**Comment by davidcm86** [comment]
Maybe you right and the question is confused or isn't relationship with fileserver. I will check your answer. Thxs ;)
