### ISSUE TITLE
Feature detection does not work in some browser.

### ISSUE THREAD

**Issue by wlzla000** [eligrey/FileSaver.js#202]
```javascript
try {var isFileSaverSupported = !!new Blob;} catch (error) {}
```

It seems Android ‘Internet’ application, Kakao in-app web application, and maybe FaceBook in-app web application support `Blob`, but don't support `saveAs()`.

**Comment by jimmywarting** [comment]
If so, then the browser doesn't support a[download], which is the main thing that FileSaver use (along with `msSaveOrOpenBlob()` that's only available in IE, edge)

```javascript
try {
     new Blob;
     var isFileSaverSupported = 'download' in document.createElement('a')
} catch (error) {
    var isFileSaverSupported = false
}
```

**Comment by eligrey** [comment]
@jimmywarting You'll want to use createElementNS("http://www.w3.org/1999/xhtml", "a") to support non-html documents
