### ISSUE TITLE
Issue with pcap file format

### ISSUE THREAD

**Issue by atul-bajpai** [eligrey/FileSaver.js#204]
How to download a pcap file format using fileSaver.
When i am trying to download is getting corrupted.
the original file size is 4 mb but after the download it is 7 mb.

**Comment by jimmywarting** [comment]
Hmm, the file size should be the same when saved, maybe you are looking at it wrong with gzip compression or something like it?

**Comment by jimmywarting** [comment]
Given the age of this issue I'm going to close it, if it's still a issue, then we can reopen it
