### ISSUE TITLE
Doesn't seem to work in Chrome 50 and later

### ISSUE THREAD

**Issue by calebsander** [eligrey/FileSaver.js#205]
When I try to save a file, it fails about 95% of the time and says `Failed - no file`. The download on the left is one where it worked, while the one on the right is one where it failed.
![Error](http://i.imgur.com/3d5PvUF.png)
I see the same issue on the [demo page](https://eligrey.com/demos/FileSaver.js/). Even in the following very simple code (where `FileSaver.js` contains the contents of https://raw.githubusercontent.com/eligrey/FileSaver.js/master/FileSaver.min.js), it fails to work almost all the time:
````html
<html>
	<head>
		<script src = 'file:///[redacted]/FileSaver.js'></script>
		<script>
			if (window.saveAs && window.Blob) saveAs(new Blob(['abc'], {type: 'text/plain'}), 'test.txt');
			else alert('Missing dependencies');
		</script>
	</head>
</html>
````

**Comment by calebsander** [comment]
I just tested it in Chrome 49.0.2623.75 on Ubuntu and it seems to work fine.

**Comment by AndriusKv** [comment]
I am having same issue in Chrome 50.0.2661.11, but it fails about 50% of the time.

**Comment by maclav3** [comment]
Same here.

The separate condition for Chrome is causing problems for me on the current google-chrome-beta (50.0.2661.26):

```javascript
if (view.chrome) {
	revoker();
} else {
	setTimeout(revoker, arbitrary_revoke_timeout);
}
```

https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L55

I admit I haven't delved into the code enough to understand the whole revocation process, but if I remove the condition and use the setTimeout code in Chrome 50, everything seems to be OK.

Also, the setTimeout code seems to be compatible with the current google-chrome stable (49.0.2623.87).

**Comment by yairza** [comment]
@maclav3 I tested your workaround on chrome beta (50.0.2661.37) on OSX 10.11 and it didnt solved it :(

**Comment by maclav3** [comment]
Hello,

I tested the workaround on google-chrome-beta on Linux 64bit, I don't know
about OSX - *maybe* it's OS-dependent. I won't be able to test it on OSX
soon, but I might check another Linux machine tonight and let you know if
it still works.
28.03.2016 2:02 PM "yairza [Masked]"
<FWD-737QTYSMENAIYCQANIQDDYCOEFGCQMB3ACWAIOKCGADFMIDABYQCZZCIFFE3KALYAC4WXQARUB3FQDNTI23GOETC4QGMMCC2DSUFJKAQ5ASOSQ53AHJB2VSJZEM7EEBRAOXC5O2VGUACCKDIFAQHIILGEELCALRACYQS4TAWFAB7QAXYAGIATMIDQZYNEEFAAAQA====@
opayq.com> napisał(a):

**Comment by yairza** [comment]
I deleted my remark,  it works great on osx

**Comment by eligrey** [comment]
If the blob revocation API doesn't get fixed in the next 2 years, remind me to double this value (as I would imagine as time goes on more complicated web apps are going to want to save larger and larger files). Sorry, not much more I can do except specify an arbitrary timeout.

**Comment by MrDefinite** [comment]
Still face the same issue on Windows and Mac Chrome 50.
However it doesn't happen if I simply use data URI like this: http://jsfiddle.net/qm5AG/1621/

**Comment by wangwenming** [comment]
OSX, Chrome 65.0.3325.181, It doesn't work!

**Comment by rajsite** [comment]
Seems like the related Chromium issue was fixed in Chrome 66: https://bugs.chromium.org/p/chromium/issues/detail?id=827932

Was Chrome the only reason to have the workaround?
