### ISSUE TITLE
Evaluate to implement browsertesting on commit of the demo

### ISSUE THREAD

**Issue by evilaliv3** [eligrey/FileSaver.js#206]
Given the hight usage of the library it would be important to start implementing at least browser-testing of commit of the demo.

This would allow to detect defects happening on some specific browser/version and would make all in possibility to collaborate in the fix; e.g. this would help in solving readly https://github.com/eligrey/FileSaver.js/issues/205, https://github.com/eligrey/FileSaver.js/issues/189, https://github.com/eligrey/FileSaver.js/issues/179, https://github.com/eligrey/FileSaver.js/issues/162, https://github.com/eligrey/FileSaver.js/issues/129

Given the fact that still no unit test is in place i think a good choice could integrate [travis.ci](travis-ci.org) + [grunt](http://gruntjs.com/) + [nightwatch](https://github.com/nightwatchjs/nightwatch) + [saucelabs](https://saucelabs.com/), and the minimum viable product would be to have a browsertesting of the basic demo but executed on the new library result of every commit.

It would be great during the testing to integrate Codeclimate in order to keep track of the code maturity and the code coverage of the tests.

All the softwares i'm suggesting are opensource and the cloud services involved are offering a complete free support for opensource projects so that it would be great if start adopting them as they would allow to do something like the following: https://github.com/ghostbar/angular-zxcvbn/issues/12

e.g.: https://github.com/globaleaks/GlobaLeaks
![screenshot from 2016-03-14 20 36 40](https://cloud.githubusercontent.com/assets/217034/13757421/9a540b7e-ea24-11e5-8632-58bef9195fa2.png)

**Comment by jimmywarting** [comment]
Could be hard to test the actually saving part, but could build a mock for that. 
A code coverage would be good, Then we can test stuff like if it's safe to remove filesystem? #174

**Comment by jimmywarting** [comment]
I spoke with the BrowserStack team, they love open source projects and they are willing to offer free access to many browser that we could then test on each pull request.

They have all desktop browsers and a bunch of mobile browsers too like a couple of android phones, iOS and even Lumia that we have a issue for #193 #124
[complete list](https://www.browserstack.com/list-of-browsers-and-platforms?product=live)

I could set up Travis, code coverage, BrowserStack and a few test for you to bring continuous testing if you want @eligrey.
All BrowserStack as for return is that we mention them in the README.md and also on the demo page

**Comment by eligrey** [comment]
How would we actually test this tough?

**Comment by jimmywarting** [comment]
We can not really test the download finished part but what we can build mocks and test is the quality of the code. 

like if it's safari expect it to run this function. if it has msSaveOrOpenBlob expect it to do [that](https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L237-L245)

if the blob needs BOM fix determined of the mimetype expect the blob to be prefixed with a string

I used code coverage to determinate what code wasn't not being executed when i run the test in chrome and i cold see exactly what code was not being used according to this [report](https://dl.dropboxusercontent.com/u/3464804/Chrome%2050.0.2661%20%28Mac%20OS%20X%2010.11.4%29/FileSaver.js/FileSaver.js.html)

We could perhaps built some test that are using blob.js polyfill also?

**Comment by evilaliv3** [comment]
@eligrey on some browsers like firefox it is perfectly doable to test for file downloads using selenium webdriver that is the technology used by both browserstack and saucelabs.

e.g. in GlobaLeaks were we are using FileSaver we are already doing this for rechecking the file download; but obviously on the FileSaver repository the tests could be more fine and cover all the library in its specific functions.
