### ISSUE TITLE
Getting corrupted word document when using FileSaver and Blob in angularjs

### ISSUE THREAD

**Issue by BukicMicko** [eligrey/FileSaver.js#217]
I am using angular-file saver service https://github.com/alferov/angular-file-saver for downloading files. Download is good but when try to open word document I am getting file is corrupted and word cannot open it and if put my api directly in browser file is good when I open it so I suppose blob is doing something for this issue... For .txt files I am not getting corrupted it is good only for .docx and for .jpeg or .png. Below is my short code for downloading files.

          function downloadDocument(fileId, fileName, documentExt) {
             var deferred = $q.defer();

             var id = encodeURIComponent(fileId);
             Restangular.one('download?fileId=' + id).get().then(function(data) {
                var file = new Blob([data]);
                if (documentExt && documentExt !== 'undefined') {
                    FileSaver.saveAs(file, fileName + '.' + documentExt);
                }
                else {
                    FileSaver.saveAs(file, fileName);
                }
            });

            return deferred.promise;
        }

**Comment by evilaliv3** [comment]
related to https://github.com/eligrey/FileSaver.js/issues/219

**Comment by eligrey** [comment]
@evilaliv3 No, related to angular, encodings, or the blob API. He didn't specify a `{type}` in his sample code, so auto-BOM is unrelated.
