### ISSUE TITLE
Can it work with animated GIFs?

### ISSUE THREAD

**Issue by arcticio** [eligrey/FileSaver.js#224]
[gifshot](https://github.com/yahoo/gifshot) generates base64 images, which makes FileSaver error somewhere at .createObjectURL().

Is there a trick?

**Comment by jimmywarting** [comment]
convert the base64 image to a blob and save it, you should never have to use createObjectURL in other to save it

**Comment by jimmywarting** [comment]
See this comment for a solution to convert it to a blob unless gifshot don't already provided a blob for you 

https://github.com/eligrey/FileSaver.js/issues/176#issuecomment-153800018
