### ISSUE TITLE
How to save XML file with UTF-16

### ISSUE THREAD

**Issue by lhf552004** [eligrey/FileSaver.js#225]
Hi ,as the title, how to save the xml file with UTF-16? I want get the XML file with UTF-16 encoding.
Here is my code:
        var blob;
        var type = "text/plain;charset=utf-16";
        var name = "Chinese.XML";
        blob = new Blob([xmlString], {type: type});
        saveAs(blob, name);
But I get the file with UTF-8 encoding.

**Comment by eligrey** [comment]
OS and browser?

**Comment by lhf552004** [comment]
sorry, browser.

**Comment by eligrey** [comment]
What OS and browser are you experiencing the issue in?

**Comment by lhf552004** [comment]
operating system is Windows 7 professional sp1, x64, en. browser is chrome 50.0.2661.102 m

**Comment by lhf552004** [comment]
the XML like below:
<?xml version="1.0" encoding="UTF-16"?>

<Bundle info="Bundle" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Comment>;;----From File .\McCommon\System\Language\ENGLISH_McBase.LGF</Comment>
<Empty/>
<Empty/>
<Comment>menu</Comment>
<Text id="" label="MENUE_SAVE_P_TXT" length="4" OriginalText="Save">Save</Text>
<Text id="" label="MENUE_LOAD_P_TXT" length="4" OriginalText="Load">Load</Text>
<Text id="" label="MENUE_PARA_TXT2" length="9" OriginalText="Parameter">Parameter</Text>
<Text id="" label="MENUE_BACK_TXT" length="4" OriginalText="Back">Back</Text>
<Text id="" label="MENUE_ERRORMSG_TXT" length="8" OriginalText="Messages">Messages</Text>
<Text id="" label="MENUE_LOGIN_TXT" length="14" OriginalText="Administration">Administration</Text>
<Text id="" label="MENUE_FTPSERVER_TXT" length="10" OriginalText="FTP-Server">FTP-Server</Text>
<Text id="" label="MENUE_EXPLORER_TXT" length="8" OriginalText="Explorer">Explorer</Text>
<Empty/>
</Bundle>

**Comment by eligrey** [comment]
Windows does not store MIME media types in file metadata. Only Linux and OSX support this feature, sorry. The `type` you provide is ignored by Windows once the file is saved to your computer. Windows only uses filename externsions (e.g. ".xml") to derive media types, and the derivations do not include character set encodings.

**Comment by lhf552004** [comment]
Oh, I hate Windows. Is there any way to fix the bug?
