### ISSUE TITLE
Issue with UTF-8 Encoding for German Characters

### ISSUE THREAD

**Issue by colfin-96** [eligrey/FileSaver.js#226]
Hi there,

I'm quite new to the encoding world, but I'm trying to create a form where users can insert data and confirm it. Then the data should be taken and an html-file needs to be created and saved. Now I'm saving the html with your FileSaver, but all German characters are coming out like Ã¤Ã¶Ã¼ instead of äöü... I've tried setting the encoding to UTF-8, ISO-8859-1, and others but I'm not getting very lucky... I know it's probably nothing to do with your filesaver itself, but I though somebody here might know the answer :smile: 

Thanks in advance :smile: 

Edit: I've solved it - I hadn't set the encoding type in the generated html file...

**Comment by kairos34** [comment]
I am having similar issue but could not understand how you could solve it. Can you share a code snippet, please?

**Comment by jimmywarting** [comment]
Show your code snippet.
have you tried autobom option?
what browser version/os?

**Comment by kairos34** [comment]
I switched to js-xlsx library, it works fine. If I have time, I will create plunkr.
