### ISSUE TITLE
Error in saving canvas image in jpeg format

### ISSUE THREAD

**Issue by SudarshanRaul** [eligrey/FileSaver.js#228]
The canvas image is saved in jpeg format but its invalid. Error received while opening the image is "Unknown or invalid JPEG marker type is found".

```javascript
function canvas2Image() {
	canvas.toBlob(function (blob) {
		saveAs(blob, imageName+"."+format);
	});
}
```

Also tried adding MIME type and qualityArgument but still no use.

**Comment by jimmywarting** [comment]
when you export the canvas as a blob it will always default to being a png format

So you could as well write:
```
function canvas2Image() {
    canvas.toBlob(function (blob) {
        saveAs(blob, imageName+".png");
    });
}
```

But if you now would like to save it as a JPEG then you would have to do:

function canvas2Image() {
    canvas.toBlob(function (blob) {
        saveAs(blob, imageName+".jpg");
    }, "image/jpeg");
}

**Comment by SudarshanRaul** [comment]
Thanks Jimmy. This worked.
