### ISSUE TITLE
UglifyJS weird BOM minification

### ISSUE THREAD

**Issue by eligrey** [eligrey/FileSaver.js#230]
I'll need to look into a solution so UglifyJS doesn't mess with [`"\xEF\xBB\xBF"`](https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L88). For now we need to manually handle it.

**Comment by eligrey** [comment]
Update: Apparently the new suggested BOM code I switched to doesn't actually work properly anyways (never thoroughly tested it). I'll be reverting the recent BOM changes soon.

**Comment by jimmywarting** [comment]
Dose this also closes #150 ?
