### ISSUE TITLE
Support saving File instance with 1 argument 

### ISSUE THREAD

**Issue by jimmywarting** [eligrey/FileSaver.js#231]
Think this should be possible:

```javascript
let file = new File(['hello world'], 'filename.txt', {type: 'text/plain'})
// or: file = input.files[0]
saveAs(file, [optional name that gets overwritten])
```

The file is a instance of blob so i think we should support saving it as well only difference is that if it has only one argument then use the file's name instead

**Comment by eligrey** [comment]
Good idea. I'll check this out too after I fix some BOM stuff
