### ISSUE TITLE
Don't popup "Save as.." Windows. Save the file in the relative directory.

### ISSUE THREAD

**Issue by zenglzh** [eligrey/FileSaver.js#235]
I don't want a pop-up window, Save the file in the relative directory when I click the save button.

**Comment by jimmywarting** [comment]
Can you elaborate?

**Comment by jimmywarting** [comment]
@zengizh Do you wan't to save the file to a specific folder?

**Comment by ArpithaGMGowda** [comment]
Hi

i don't want to download the file , instead of i need to append the previous data in file (which is already present in local ) 
any solution 

Thank you in advance :)
