### ISSUE TITLE
min js file doesn't save file with correct filename

### ISSUE THREAD

**Issue by mayashavin** [eligrey/FileSaver.js#237]
FileSaver.min.js always saved file with filename as "download" regardless which name you put in name parameter of new File(blob, name, ...);

In case we try to save file with different file type (other than .txt, for example .js), the file saved will be with no type (not .js nor .txt).

In case we try to save file with .txt type, it will be saved as "download.txt".

Normal FileSaver.js is working correctly.

Example used:

```javascript
new File(["hello"], "hello.js", {type: "text/javascript;charset=utf-8"});
```

**Comment by jimmywarting** [comment]
Minified version was not build when releasing 1.3.x
new version coming up in a minute

**Comment by jimmywarting** [comment]
Fixed
