### ISSUE TITLE
Can you construct larger blob in Blink now?

### ISSUE THREAD

**Issue by jimmywarting** [eligrey/FileSaver.js#239]
https://bugs.chromium.org/p/chromium/issues/detail?id=375297
https://www.chromestatus.com/features/4956772716511232

Could maybe be fixed in v51?
In which case we should update the readme.md

Can someone test this?

**Comment by Ruffio** [comment]
Is this still an 'issue'/question? Can a live example be provided so it can be tested?

**Comment by Ruffio** [comment]
@eligrey this issue should be closed. It was created June 2016, I pinged January 2018 but until now no response...
