### ISSUE TITLE
Problem saving in Safari

### ISSUE THREAD

**Issue by jimmywarting** [eligrey/FileSaver.js#242]
Moving this away from #12 @prafulc

> I am using this package to save an excel file. It is working well with mozilla and chrome but it is not downloading file in safari. Here is my code:

    saveAs(new Blob([s2ab(response)],{type:"application/octet-stream"}), fileName)

I'm call this async with meteor.call

**Comment by jimmywarting** [comment]
Didn't want to bother everyone else with useless notification as it's more specific to you. It also didn't bring any useful information how to solve #12

**Comment by prafulc** [comment]
@jimmywarting Do you want to say that if saveAs() is getting called after 1sec its not going to work? But in my case its not possible to call it just after click event. It is going to take response from server.

**Comment by jimmywarting** [comment]
An alternative method would be to get the response from the server, wait until it has finish and then provide them with a save button.

FileSaver is useful for client side generated data. Since your file comes from the server it probably would be best if you could send content-disposition header from the server directly. A server is the only solution where you will be able to specify a filename in Safari.

**Comment by jimmywarting** [comment]
The behavior of the 1 sec rule is that it's not possible to open up a new window with `window.open` unless it's made from a user interaction.

We try `window.open` first of all, but if the window didn't load then we replace the curent window with the response.

**Comment by prafulc** [comment]
In my case it is not possible to get the data first and then call saveAs(). Does it work if I get data synchronously and then call saveAs(). In both cases data will need some time to get collected. Here is my code of asynchronous function:

 ```
Meteor.call( 'exportData',ws ,ref, ( error, response ) => {
		      if ( error ) {
		        // Bert.alert( error.reason, 'warning' );
		      } else {
		        if ( response ) {
		          function s2ab(s) {
		            var buf = new ArrayBuffer(s.length);
		            var view = new Uint8Array(buf);
		            for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
		            return buf;
		          }
		          // the saveAs call downloads a file on the local machine
		          saveAs(new Blob([s2ab(response)],{type:"application/octet-stream"}), fileName)
		        }
		      }
		    });
```

**Comment by prafulc** [comment]
@jimmywarting I have just checked renaming the file and it works perfectly. I just need to change the name of that file. Any suggestions?

**Comment by jimmywarting** [comment]
Sorry, there is no way we can rename the file. It always downloads as `Unknown` for me.
What it essentially comes down to is that safari tries to open 

    data:attachment/file;[base64 response of s2ab(response)]

That is the only way we can trigger safari to download the file but with the cost of not being able specify a filename.

A other decent alternative is just to show the response in a new tab and let the user just hit cmd+s to save the file. But it only works best if it's just plain text where the user knows that it can be saved as .html .js or .txt or whatever. Then they can specify the filename by them self.

If you insist on having a filename, then there is only three things left to do... 
 1. Using flash based [Downloadify](https://github.com/dcneiner/Downloadify) which i hate...
 2. Use a server to force the download to happen while specifying a filename like I talked about
 3. Wait until safari either support download attribute or service worker.

**Comment by RaviTejaKaruturi** [comment]
Hi @jimmywarting ,

In one of the comments, you said
<blockquote>
Since your file comes from the server it probably would be best if you could send content-disposition header from the server directly. A server is the only solution where you will be able to specify a filename in Safari.
</blockquote>

**Comment by jimmywarting** [comment]
Hi @RaviTejaKaruturi 

After you have added the content-disposition header how do you download the file afterwards?
Do you download the file with ajax first? If so, that won't work... You need to navigate to that page/file for it to work

**Comment by RaviTejaKaruturi** [comment]
Currently, I send a ajax call and server returns the file with content-disposition header. Can you please explain 
<blockquote>
 You need to navigate to that page/file for it to work
</blockquote>

**Comment by jimmywarting** [comment]
Instead of doing ajax you should just navigate to the url

    window.location.href = url
