### ISSUE TITLE
How to specify the data inside <td> tag to be exported

### ISSUE THREAD

**Issue by nischaym** [eligrey/FileSaver.js#243]
The code is working fine, but inside <td> {{item.data}}</td> i do not have item.data instead its a text box using which the data can be changed.
example : 

``` html
 <td>
     <input type="text" ng-change="saveOnChange($index)" ng-model="item.data">
 </td>
```

so when i export i get the text box in excel instead of this item.data.
can you please help to achieve this.

**Comment by jimmywarting** [comment]
It was a bit hard to understand the question/problem...

Something along this?

```html
 <td ng-repeat="item in items">
     <input type="text" ng-model="item.data">
     <button ng-click="ctrl.saveFile(item)">save</button>
 </td>
```
```js
  ["$scope", function($scope){
     this.saveFile = function(item){
       var blob = new Blob(item.data)
       saveAs(blob, 'filename.txt')
     }
  }]
```

**Comment by nischaym** [comment]
ok let me explain in detail
this is the existing code 
in the controller
```
$scope.print = print;

        function print() {
            var blob = new Blob([document.getElementById('exp').innerHTML], {
                type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
            });
            saveAs(blob, "Report.xls");

        }
```

and the .html is

```
<table id="exp">
;;;;;;;; some header
<tr ng-repeat = "record in records" >
 <td>
          <input type="text" class="form-control"  ng-model="record.ShipFrom.ShipFromNode">
 </td>
 <td  style="width: 8%;">
         <input type="text" class="form-control"  ng-model="record.ShipTo.ShipToRegion">
 </td>
</tr>
</table>
```
so when a button is
```
                <button ng-click="print()"  type="button" class="btn btn-default pull-right" aria-label="Left Align">
                    <span class="glyphicon glyphicon-print" aria-hidden="true"></span>
                </button>
```

when the print function runs i get empty text boxes as output instead of the actual data. i want the data which is binded using ng-model to be the exported data instead of empty text boxes.
i hope the issue is clear now

**Comment by nischaym** [comment]
here is the screenshot of the excel which gets exported.

![issue](https://cloud.githubusercontent.com/assets/15176160/16338529/5c09449e-39eb-11e6-99eb-ec78325dbf9d.JPG)

**Comment by nischaym** [comment]
Any update on this?

**Comment by aki-84** [comment]
I have used filesaver to export similar table without any issues

One of the alternatives is you keep control and span both inside TD and use no-if to display one based on condition if exporting ..show span ..else show input control..

When you click export button set exporting as true so your spans are injected and the let filesaver do the work 😉

**Comment by Ruffio** [comment]
Can this issue be closed?

**Comment by Ruffio** [comment]
@eligrey please consider to close this question. It was created June 2016, I pinged January 2018, but with no response...
