### ISSUE TITLE
Downloaded file has an incorrect name

### ISSUE THREAD

**Issue by mirsaeedi** [eligrey/FileSaver.js#244]
When i`m using saveAs method on a File, the name of the downloaded file become 'download.txt', and it is ignoring the name i passed to the Constructor. I had not this problem with BLOB.

`var file = new File([JSON.stringify(result)], "Approximation Result.txt", {type: "text/plain;charset=utf-8"});
    saveAs(file);`

**Comment by arunxavy** [comment]
saveAs works like this right?
```

var blob = new Blob(["Hello, world!"], {type: "text/plain;charset=utf-8"});
saveAs(blob, "hello world.txt");
```

**Comment by mirsaeedi** [comment]
yeah! with blobs it works this way. but my issue was about Files. I did as you did in github samples, but i didnt work.: 
`var file = new File(["Hello, world!"], "hello world.txt", {type: "text/plain;charset=utf-8"});
saveAs(file);`

**Comment by eligrey** [comment]
I am unable to reproduce your issue. Please ensure that you are using the latest version of FileSaver.js. The current version is [1.3.2](https://raw.githubusercontent.com/eligrey/FileSaver.js/1.3.2/FileSaver.min.js).
