### ISSUE TITLE
Not saving file on Chrome 52.0.2743.82 m (64-bit)

### ISSUE THREAD

**Issue by teejt** [eligrey/FileSaver.js#245]
Not saving file on Chrome 52.0.2743.82 m (64-bit) on Windows 10 (64 bit)

**Comment by wejr** [comment]
Everything works on Chrome 51.x and after update to Chrome 52.x it stops working. I tried to debug the code, I don't know why but after calling 'click' method on anchor ('<a>') nothing happen. Please help!! (Win7, Chrome 52.0.2743.82 m 32-bit)

**Comment by jimmywarting** [comment]
Are you doing it on user interaction or async?

**Comment by teejt** [comment]
This was done on user interaction. I realized that after updating Chrome, I tried to reboot my laptop and the problem is gone. Looks like I should have reboot my laptop before writing here.
By the way this was the sample - http://paramquery.com/pro/demos/export_local
It is using the Export button. Now it's working. Thanks!

**Comment by wejr** [comment]
Oh, I'm sorry, you are right. After restart computer everything works fine. Thanks!
