### ISSUE TITLE
blob constructor is not consistent across browsers

### ISSUE THREAD

**Issue by gatochuqui** [eligrey/FileSaver.js#246]
The good news very welcome indeed is that it works on all browsers.
Internet Explorer has a SaveAs option which allows the user to save the file where it should be in the first place.
All others dump the file into the downloads folder (beats me why the new file API designers think placing the file in downloads is more secure than putting into the place where the file actually belongs) 
Currently IE (going back several versions) also supports document.execcommand.saveAS which is very easy to use. The bad news is that IE is going away sometime in the future.
It sure would be nice if all browsers reacted consistently to the blob parameters and would let us store our data where we need it.
I am  not sure if all the great work done so far with FileSaver.js can overcome the above obstacles which belong in the WWW consortium. 
Thank for the good work

**Comment by jimmywarting** [comment]
We can't specify which directory we want to save the file in

**Comment by gatochuqui** [comment]
I understand; just wondering why the standards consortium decided the downloads folder is safer than the folder where the user wants the data.  


Get Outlook for Android






On Thu, Jul 28, 2016 at 4:14 AM -0500, "Jimmy Karl Roland Wärting" <notifications@github.com> wrote:












We can't specify which directory we want to save the file in

**Comment by jimmywarting** [comment]
It's actually possible to change it in the browser. I think in chrome the download folder becomes the last saved places.

Other browser have different settings
