### ISSUE TITLE
Don't work on 360 browser

### ISSUE THREAD

**Issue by k1noman** [eligrey/FileSaver.js#251]
Unable to save the file to the 360 browser. For some reason, he thinks that the file size is 0.

**Comment by jimmywarting** [comment]
Never heard of the 360 browser before...

**Comment by k1noman** [comment]
very pity :(
Thanks for the quick response

**Comment by k1noman** [comment]
hmm.. but in Safari same problem

**Comment by jimmywarting** [comment]
Safari has been a long known issue, #12
