### ISSUE TITLE
Add a few line breaks

### ISSUE THREAD

**Issue by 20design** [eligrey/FileSaver.js#255]
Hi all!

Is there any way to put a line brake in the code?

Thank you very much!
Kind regards,
George.

**Comment by jimmywarting** [comment]
There is but a few line breaks in the code already, but yea it could need some few more line breaks for more readability :P

**Comment by 20design** [comment]
Hi!

Thanks for that quick answer! :)
I have found a work around anyway...
Here is my solution:

`var newReceipt = new Blob([orderLinesPrinter + "some txt here \r\n This is line nr.2"], {type: "ANSI"}); `

If you work only in linux "\n" is sufficient but for windows "\r\n" is mandatory to add a line brake.
