### ISSUE TITLE
.bin file generated on android device and emulator

### ISSUE THREAD

**Issue by Bivin21** [eligrey/FileSaver.js#256]
I'm working on a project that deals with the development of hybrid app for one of the client, I'm using JSZip with angularJS and cordova. Even running the example code provided on [JSZip](https://stuk.github.io/jszip/) doesn't produce proper zip file, but created a bin file with a hash name. Works like a charm on desktop browsers but fails on mobile browsers.
Please help.

**Comment by jimmywarting** [comment]
This is more likely a problem with JSZip and how it generates the blob.
FileSaver never dose anything to alter the file it only saves it.

Dose the mobile have typed array supports and all that JSZip wants?
What mobile + browser are you testing this in? And can the browser construct a blob? `new Blob(['test'])`

**Comment by Bivin21** [comment]
I'm using Crosswalk that integrates chrome browser on the mobile. yes the browser can create a Blob object also checked the browser using JSZip.support and the output is :--
Object {base64: true, array: true, string: true, arraybuffer: true, nodebuffer: false…}
array : true
arraybuffer : true
base64  : true
blob : true
nodebuffer : false
nodestream : false
string : true
uint8array: true

**Comment by mnjrupp** [comment]
Bivin21, can you give the snippet of code that you are using when calling saveAs? I am also trying to use FleSaver js using Crosswalk. I'm not making progress either.
Thanks

**Comment by Ruffio** [comment]
@Bivin21 anything new?

**Comment by Ruffio** [comment]
@Bivin21 aything new on this or should the issue be closed?
