### ISSUE TITLE
Problem in Firefox 

### ISSUE THREAD

**Issue by ALWESHAHI** [eligrey/FileSaver.js#261]
when i am trying to save as my file it gives me in firefox file like 
"fileName.txt" but with default application winrar 
when i am save this file i found the file is corrupted
but in chrome it works fine

**Comment by jimmywarting** [comment]
Eh? Think you need to show us some code.
Don't understand what winrar should have to do with .txt files...

FileSaver don't alter the content that is being saved.

**Comment by turkus** [comment]
@weshahi look at this: https://stackoverflow.com/a/50875615/6734406 . Probably you have to add/change type of a file.
