### ISSUE TITLE
change the resolution of the take

### ISSUE THREAD

**Issue by fabikopa** [eligrey/FileSaver.js#264]
Hi, I was wondering if we can up the resolution of the snapshot.
I mean if the canvas is reduced but when we use saveAs we can choose a resolution or dimensions?
Thank you!
Best Regards
Fabiola

**Comment by jimmywarting** [comment]
This has nothing to do with FileSaver.

When you ask for a UserMedia you can specify the quality with a constraints `{video: {width, height}}`
And when you retrieve it from canvas set the quality parameter to 1
