### ISSUE TITLE
For iOS bookmarked webpage, can't save resulting image.

### ISSUE THREAD

**Issue by jeremyk** [eligrey/FileSaver.js#265]
You can't save an image on a site that is webapp capable (https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html). It opens the resulting image in the same window and long pressing on it does nothing.

I realize this is partly an issue with Apple's implementation but I think if it could open in a new window, that would fix this problem. Is there any change you can add an option to do this?

If you need to test you can try the "download collage" feature of our web app: https://eventshare.co. Just create  new collection, add a few photos, and select download collage from the menu.

**Comment by jimmywarting** [comment]
iOS is much un-compatible of saving a file since it don't have any filesystem. Think even if iOS had a filesystem it would probably still be relevant to #12?

But i'm not an expert i don't own a iOS - Team android here

**Comment by jeremyk** [comment]
If you are in the regular browser (safari, chrome) the image will open in your current tab and you can long press to save it. Not ideal, but it works.

**Comment by whitewhim** [comment]
Has anyone else had any experience with this issue? Homescreen web apps in iOS seem to disable the touch callout that allows normal iOS Safari users to save images by long-pressing. This is avoidable only if the link leading to the file is external (i.e., starts with http://), under which circumstance iOS leaves the fullscreen web app and opens the link in normal Safari - where long pressing works. 

However filesaver.js obviously doesn't produce external links, and therefore the web app just opens up the file / image with no option for saving, navigation backwards or anything. It's a fairly ridiculous situation...
