### ISSUE TITLE
Can't download mp4 video file

### ISSUE THREAD

**Issue by sean-hill** [eligrey/FileSaver.js#266]
Hey there,

I have a video file I'm serving from my express server: 

```js
var video = path.resolve(__dirname, './video.mp4');
res.status(200).sendFile(video);
```

Which I'm then trying to download with `FileSaver.js`:

```js
var video = new Blob([data], { type: 'video/mp4' });
saveAs(video, 'video.mp4');
```

The process works fine, but the downloaded content is no longer a playable video file.

Anyone else have issues with this? Saving a simple `.txt` file works just fine for me as shown in the example.

**Comment by jimmywarting** [comment]
Anything reason why you can't download the file with content disposition?

res.download(path [, filename] [, fn])

**Comment by sean-hill** [comment]
@jimmywarting are you saying to not use `FileSaver.js` but do everything via the server?

**Comment by jimmywarting** [comment]
Yes, that way it will cover more supported browsers also
FileSaver is only good for client side generated stuff and where it needs authentication headers that regular http get request won't work

**Comment by sean-hill** [comment]
Ah gotcha, great thanks!

**Comment by lecong** [comment]
I cannot download mp4 video with url
`saveAs(mp4Url);`
response error: FileSaver.min.js:1 could not download file

Please help me fix this issuse

**Comment by emircanomak** [comment]
I couldn't download it with the url so try like this;
   var blob: Blob = new Blob([data],{type:"video/mp4"});
    FileSaver.saveAs(blob,data)
