### ISSUE TITLE
Download doesn't work on newest safari (v10)

### ISSUE THREAD

**Issue by rd-secretstuff** [eligrey/FileSaver.js#267]
The download doesn't work anymore on the newest safari v10. Most likely because the is_safari test that is done doesn't work for the newer version

`/constructor/i.test(view.HTMLElement)` will return false as of version 10 of safari.

see also http://stackoverflow.com/questions/39120772/how-to-detect-safari-10-browser-in-javascript

**Comment by jimmywarting** [comment]
Dang! Try imagine how many libs got messed up cuz safari normalized one thing that have been used as a hack, lol

**Comment by jimmywarting** [comment]
How about `/constructor/i.test(view.HTMLElement) || window.safari`?

**Comment by solisoft** [comment]
👍

**Comment by rd-secretstuff** [comment]
Doesn't seem to work on mobile safari on iOS 10

**Comment by solisoft** [comment]
Forcing is_safari to true doesn't work neither on safari 10 ... so it's not only related to the check

**Comment by rd-secretstuff** [comment]
for now I reverted back to using version 1.2.1 which works on safari 10 both desktop and ios.

**Comment by solisoft** [comment]
Weird, version 1.2.1 still redirect me to : blob:http://rbook.dev:8080/694113e2-9e45-4c78-b7b5-6180be41efde and display me content inline instead of downloading it !?

**Comment by jimmywarting** [comment]
Might depend on mine type also. Application/octem-stream will force the file to be saved but filename will be unknown

**Comment by SiDChik** [comment]
Hello. I changed is_safari to `is_safari = /constructor/i.test(view.HTMLElement) || view.safari` 
File downloads, but with exception and filename is unknown, without any extension. I can't find any information how to solve this problem. I checked google drive and they already solved this issue, any idea?

**Comment by jimmywarting** [comment]
Google drive don't use any client side method to save the file. They use content disposition header

**Comment by jimmywarting** [comment]
The is_safari test have been fixed for Safari 10. 

Same rules still applies, setting type to: 'Application/octem-stream' will now again force the file to be downloaded, but the filename will still be unknown. So I think the best thing is to still to set a mimetype that safari know of and can still render in a browser tab
