### ISSUE TITLE
The lastest Webkit Nightly has support for <a download>. FileSaver.js creates the download link and attempts to click it, but nothing happens.

### ISSUE THREAD

**Issue by eddieloeffen** [eligrey/FileSaver.js#268]
This is in reference to fixing https://github.com/eligrey/FileSaver.js/issues/12

The webkit team have been working towards implementing support for \<a download\> which you can follow here:
https://bugs.webkit.org/show_bug.cgi?id=156056

I have installed the latest nightly from https://webkit.org/nightly/ to check it out.

This demo page now correctly downloads the image instead of opening it:
http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_a_download

I have also verified that this works with a Blob URL.

Then I came to test FileSaver.js. 

What I can see is that the library correctly detects the new support for \<a download\> and tries to use it.

It creates a link with a download attribute and tries to click it to invoke the download. However at this stage, nothing happens when the click is despatched.

If I append the generated download link to the DOM and click it manually, the generated file is saved as expected.

**Comment by eddieloeffen** [comment]
The Webkit developers have opened and resolved their own bug report for this exact issue here:
https://bugs.webkit.org/show_bug.cgi?id=162788

**Comment by eligrey** [comment]
What version of Safari will this fix be in? I think the compatibility table can be updated now.
