### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by FredericHeem** [eligrey/FileSaver.js#269]
Would it be possible to publish this package to npm ? My client has a constraint that all packages must come from a private repo which proxy to the global npm.

**Comment by eligrey** [comment]
It's open source. You're free to re-host it in private repos, as long as you and your client abide by the MIT license.

**Comment by jimmywarting** [comment]
https://www.npmjs.com/package/file-saver

**Comment by FredericHeem** [comment]
@jimmywarting thanks a lot
