### ISSUE TITLE
Doesn't work on latest Chrome! (v54)

### ISSUE THREAD

**Issue by mefjuu** [eligrey/FileSaver.js#274]
In the latest Chrome there is no effect after clicking 'Save' (https://eligrey.com/demos/FileSaver.js/).

Chrome 54.0.2840.59

**Comment by jimmywarting** [comment]
Just tried it myself in 54.0.2840.59, and it did work just fine

**Comment by mefjuu** [comment]
It's quite strange because restarting Chrome FileReader saves files properly...

**Comment by jimmywarting** [comment]
starting to feel a pattern here...? #250
