### ISSUE TITLE
Saving an UTF-8 Excel blob

### ISSUE THREAD

**Issue by heruan** [eligrey/FileSaver.js#275]
I'm trying to save a `Blob` of an Excel file, but the saved file is large double than the original, and Excel says it's corrupted.
```javascript
var data // = data from AJAX response, 6854 bytes
var type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8";
var blob = new Blob( [ data ], { type: type } );
FileSaver.saveAs(blob, "file.xlsx");
```
Chrome opens the file download modal, but the saved file is 11953 bytes large and Excel says it's corrupted.

**Comment by jimmywarting** [comment]
the default ajax [modifies the response ](Receiving_binary_data_in_older_browsers)
There are a few options
- set the responseType to blob and use that instead
- use `fetch(url).then(res=>res.blob()).then(saveAs(blob, 'filename'))`
- override mimetype and construct it as you are doing (see link)
- don't use jQuery.ajax (it can only handle string & json - not binary like buffer and blob)
- use download attribute instead

or better yet if you have control over the server
- Don't use FileSaver at all use content-disposition attachment header (you will get better support in safari and older browser)

**Comment by heruan** [comment]
I don't think this is my case: I'm passing to the `Blob` constructor a `data` variable which is 6854 bytes long, but the resulting `Blob` is 11953 bytes long. Why so?

**Comment by jimmywarting** [comment]
You need to show the full code of the ajax call

**Comment by jimmywarting** [comment]
`Ä` is a 2 byte character. but the length is still 1

**Comment by heruan** [comment]
Thank you, using the `fetch` API I've got the file saved right!

**Comment by shikhaBasra** [comment]
If the json has complex array structure, then those fields in the exported files are empty if exporeted using file-saver. Can you please help me in this case?

**Comment by bismoy2013** [comment]
@heruan were you able to solve this ?

**Comment by bismoy2013** [comment]
Hope it does because from api I am able to get stream buffer post creation of excel workbook, but once I try saving it with mime type of excel as @heruan , I got downloaded excel file (.xlsx) as corrupt.

**Comment by jimmywarting** [comment]
show your code how you get your binary

**Comment by bismoy2013** [comment]
C# Api : 

        [HttpGet]
        [Route(Routes.ExportExcel)]
        public HttpResponseMessage Export( ) {
              
             var wb = new XLWorkbook(); // ClosedXML
               // worksheets stuffs
               // workbook done & it's coming up fine in the server end

            MemoryStream stream = GetStream(wb);// The method is defined below
            var result = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new ByteArrayContent(stream.GetBuffer())// (stream.ToArray())
            };
            //result.Content = new ByteArrayContent(stream.GetBuffer());
            result.Content.Headers.ContentDisposition =
                new System.Net.Http.Headers.ContentDispositionHeaderValue("attachment")
                {
                    FileName = "samplefile.xlsx"
                };
            result.Content.Headers.ContentType =
                new MediaTypeHeaderValue("application/vnd.openxmlformats- 
                                                                         officedocument.spreadsheetml.sheet");
               return result;

            /*this below snippet is only to check if it's able to convert the stream back to excel file in my local 
               machine.
            byte[] fileBytes = new byte[stream.Length];

            stream.Read(fileBytes, 0, fileBytes.Length);
            Console.WriteLine(stream.Read(fileBytes, 0, fileBytes.Length));
            stream.Close();
            //Begins the process of writing the byte array back to a file

            using (Stream file = File.OpenWrite(@"C:\Desktop\data.xlsx"))
            {
                file.Write(fileBytes, 0, fileBytes.Length);
            }
               
             */
            
           } // end of api snippet


Angular/Typescript (UI code)

[ constants.ts ]
            import { HttpHeaders } from "../../../node_modules/@angular/common/http";
             
            const endpoint = "http://localhost:5000/api";
            export const constants = {
                               getgroupname: `${endpoint}/v1/groups/{name}`,
                               xmlheaders: { headers: new HttpHeaders({ 'Content-Type': 
                                                           'application/vnd.openxmlformats- 
                                                                   officedocument.spreadsheetml.sheet' }), 
                                                           responseType: 'text' as 'text' }
                                   };

            
[ export-service.ts ]

              import { constants } from "../constants";
              import { Injectable } from "../../../../node_modules/@angular/core";
              import { HttpClient, HttpHeaders } from "../../../../node_modules/@angular/common/http";

               @Injectable()
                export class ExportService {
                              constructor(private http: HttpClient) { }
                              exportData(groupname: string) {
                                                     return this.http.get(constants.getgroupname + '/' + 
                                                                         groupname, constants.xmlheaders);
                                           }
                               }


[ component.ts ] snippet

                  exportData() {
                             this.exportService.exportData(this.selectedGroup.toString())
                              .subscribe(data => {
                                           const strlink: string = 'localhost:5000/api/v1/groups/{some-name};
                             
                                //first trial , result : No file getting downloaded
                               window.open(strlink, '_blank');
                                console.log("File exported successfully");
                                 console.log(data);
        

                               //second trial , result : corrupt file
                               var type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                               saveAs(new Blob([data], { type: type }), 'sample-file.xlsx');
                               },
                                        err => {
                                         this.message = ['Couldn't export.'];
                                     console.log(err);
                                     });

                         }

![image](https://user-images.githubusercontent.com/3494709/44298946-65ef9280-a30a-11e8-831b-bd22c7652e6f.png)

**Comment by jimmywarting** [comment]
The problem is that you return the file as text
```ts
// constants.ts
responseType: 'text' as 'text'
```

Set the responseType to blob and don't construct your own blob in component.ts

**Comment by jimmywarting** [comment]
And the way i see it you got control over the server, so why don't you use Content-Disposition  attachment response header to save the file and avoid FileSaver altogether? if i may ask

Also it would be helpful if you could update the wiki about returning a blob with the new Angular codebase (perhaps a ts and a es6 version)

https://github.com/eligrey/FileSaver.js/wiki/Saving-a-remote-file#diffrent-ajax-methods

**Comment by bismoy2013** [comment]
just blob ? I am little confused with syntax here, tried changing , 

    responseType: ResponseType.Blob 

But then it throws error in export-service.ts . Yes you're right , api is cool, struggling only at the UI end, I'll keep trying , thanks for the inputs, hope it works out. Will keep you posted here, once things work out , will update the wiki.

**Comment by bismoy2013** [comment]
also, if possible please do share any working code snippet or link that I can refer to.

**Comment by jimmywarting** [comment]
I'm no expert at typescript or angular 2+ 
but it should be something like this:

```ts
@Injectable()
export class AngularService {

    constructor(private http: Http) {}

    download(model: MyModel) { //get file from service
        this.http.get("http://localhost/a2/pdf.php", {
            responseType: ResponseContentType.Blob,
            headers: new Headers({'Content-Type', 'application/x-www-form-urlencoded'})
        }).subscribe(
            response => { 
                console.log(response) blob should be available here
            },
            error => {}
        );
    }
}
```

**Comment by bismoy2013** [comment]
I think I am getting what you're trying to mean here, basically I need to stay away from creating my own blob. And the headers, should be fine with 
                            
                 application/x-www-form-urlencoded

Shouldn't I be using ? Or you may have added this snippet just for me to understand the flow :) Will try it out, let's see .

                 application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

**Comment by jimmywarting** [comment]
I added a snippet i found at stackoverflow

**Comment by bismoy2013** [comment]
Thanks for that, let me just explore further and try whatever you suggested once.

**Comment by bismoy2013** [comment]
Still unsolved. Made small changes in code, introducing blob(tried with arraybuffer too) as response
type but no help !


              import { Injectable } from "../../../../node_modules/@angular/core";
              import { HttpClient, HttpHeaders } from "../../../../node_modules/@angular/common/http";

              @Injectable()
               export class ExportService {
               constructor(private http: HttpClient) { }
                exportData(groupname: string) {
                           return this.http.get(constants.getgroupname + '/' + 
                                                groupname, {responseType : 'blob'});
                             }
                   }

On F12 I can see the below image .

![image](https://user-images.githubusercontent.com/3494709/44301248-5172c080-a331-11e8-863e-798bb9827c44.png)

Post downloading, if I open, this is what I see.

![image](https://user-images.githubusercontent.com/3494709/44301238-3acc6980-a331-11e8-8612-16c559e5e2a8.png)

**Comment by jimmywarting** [comment]
Sry, don't know how i can help you anymore...
My suggestion is that you don't use angulars http module or FileSaver, just navigate to the url it does not look like you are making a POST request or sending any data to the server, quite frankly i don't know why you send `Contet-Type` header in a get request... have you tried just navigating to the url?

location.href = `constants.getgroupname + '/' + groupname`
perhaps just a link will do.
```html
<a href="constants.getgroupname + '/' + groupname" download="sample-file.xlsx">
  download
</a>
```

if you still can't open it then maybe there is something wrong with the server code delivering wrong data

**Comment by bismoy2013** [comment]
Yeah kinda strange, server seems fine to me. The codes are written keeping user experience in mind, so no url is used in my case, it has to be something like you select something from (dropdown) -> click Export button -> file gets downloaded.

**Comment by bismoy2013** [comment]
anyways thanks for ur responses . I added my question here assuming someone else who is aware of such scenario in angular can respond :)

**Comment by jimmywarting** [comment]
Gfu, I would still just navigate to the file

**Comment by bismoy2013** [comment]
Well agreed, but it's fine I guess. I am actually little surprised that application/vnd.openxmlformats-officedocument.spreadsheetml.sheet didn't help. Gosh, because of these small things, I had to spend so much time , almost giving up lol .

**Comment by bismoy2013** [comment]
This is how my exportservice looks like (pasting it here for people facing similar problem in near future)

            service-method() {
                      return this.http.get("api_url", {responseType : 'arraybuffer'});
              }

**Comment by nguyenhoangnam123** [comment]
@bismoy2013 thanks a lot, you saved my time!

**Comment by bismoy2013** [comment]
Haha cool guys . Glad it helped .

**Comment by lapastina** [comment]
> This is how my exportservice looks like (pasting it here for people facing similar problem in near future)
> 
> ```
>         service-method() {
>                   return this.http.get("api_url", {responseType : 'arraybuffer'});
>           }
> ```

This solution, works for me! Thank you!
