### ISSUE TITLE
Safari opens and immediately closes a blank tab

### ISSUE THREAD

**Issue by SRachamim** [eligrey/FileSaver.js#276]
I use:
```javascript
const blob = new Blob([dataTable], { type: 'data:text/csv;charset=utf-8' });
FileSaver.saveAs(blob, fileName);
```
When `dataTable` is a string of comma-separated values and `fileName` is just `some-file.csv`.
The code is executed inside a click handler (React's onClick).

It works very well on Chrome, Firefox, Opera and Internet Explorer (on Linux, Windows and Android), but not on Safari (7-10).

In Safari, the browser opens a new (blank) tab and immediately closes it.

**Comment by jimmywarting** [comment]
The mime type is wrong... try any of the followings in:

```
{type: 'text/csv;charset=utf-8'}
{type: 'text/csv'}
{type: 'text/text;charset=utf-8'}
{type: 'text/text'}
```

**Comment by SRachamim** [comment]
Thanks.

Now it opens a new tab with the dataTable string. The user should save it manually, and the default name is unknown without the .csv extenstion.

**Comment by jimmywarting** [comment]
Yepp, the naming part is a known issue and there is nothing you can do to fix it apart from using [downloadify](https://github.com/dcneiner/Downloadify) that is based on flash...

Safari is close to supporting download attribute (#12) but they sad that a long time ago so i don't have my hopes up anymore for it being fixed any time soon :(

**Comment by bogdanalexe90** [comment]
@jimmywarting I think Safari just release support for `download` attribute in their latest technology preview. Checkout the release notes: https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by jimmywarting** [comment]
Holy s*** Safari have been holding on for a long time with this major version bump introducing a hole bunch of new stuff like fetch, ReadableStream, es6 and a lot more!

But I would rather want to see a shorter release cycle like Blink and FF, where they makes updates all the time instead of just holding on to one big major release...

Anyhow, going close this since you got it open - already have plenty of safari issues right now the big one being #12

**Comment by pauljoey** [comment]
FYI. From tests we've done, in iOS Safari if you set the mimeType as `text/csv` instead of `text/csv;charset=utf-8` then it will recognize it as a CSV file and show the data in the new tab in a tabular format instead of plain text.
