### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by isergey** [eligrey/FileSaver.js#277]
Type defenitions for TypeScript please!

**Comment by fedorbirjukov** [comment]
_typings.d.ts_
```
declare function saveAs(data: Blob, filename: string, noAutoBOM?: boolean): void;
declare module 'file-saver' {
    export = saveAs;
}
```
_your.ts_
```
import saveAs = require('file-saver');
```

**Comment by marvinscharle** [comment]
Type definitions are available via `@types`, just install `@types/file-saver`

**Comment by Ruffio** [comment]
It looks like this issue has been resolved. Can it be closed?

**Comment by fedorbirjukov** [comment]
Sure, but it is _ridiculous_ to export a module that is supposed to implement a single function. Check out [save-as](https://github.com/noderaider/save-as).

**Comment by Ruffio** [comment]
So it is not resolved? It can be fixed without breaking anything ?
