### ISSUE TITLE
file name parse '/' to '-'

### ISSUE THREAD

**Issue by xxcn8423** [eligrey/FileSaver.js#278]
if I write 
file = new File([info], '00/00/0000-00:00.csv', type: 'text/plain;charset=utf-8')

The out put file name becomes to 00-00-0000-00-00/csv

**Comment by ravenjam** [comment]
Why this is closed? What's solution to this?

**Comment by ravenjam** [comment]
@xxcn8423 Have you figured it out by yourself?
