### ISSUE TITLE
Saving CSV with unique chars using in a different encoding other than UTF-8

### ISSUE THREAD

**Issue by ranabra** [eligrey/FileSaver.js#28]
This is not exactly an issue, rather it is a solution 
( for example a solution to: https://github.com/eligrey/FileSaver.js/issues/25 )

Solution: For all your special character needs, just use UTF-8, but additionally add a BOM to make sure the file is opened correctly.
CSV for example was opened by Office Excel versions prior to Office 2007 with the wrong ANSI 1252 encoding by default.
Adding a BOM will make the file open correctly (in UTF-8) in Office versions since Office 2007 (maybe needs Office SP for Office 2007)

```
var BOM = "\uFEFF";
var    csvData = BOM + csvData;
var blob = new Blob([csvData], { type: "text/csv;charset=utf-8" });
saveAs(blob, "myFile.csv");
```

**Comment by linhyo** [comment]
@ranabra Thank you for your solution (encode in UTF-8 with BOM). It works !

**Comment by b4stien** [comment]
@linhyo FYI, I'm not 100% sure anymore, but last time I checked UTF-8 with (or without BOM) wasn't working on OS X with Office 2011.

**Comment by nehemiekoffi** [comment]
Work for me (encode in UTF-8 with BOM). Many thank!

**Comment by vsile** [comment]
And for me! Thank you!

**Comment by montogeek** [comment]
I LOVE YOU @ranabra

**Comment by ctoro8888** [comment]
Works great. Thanks!!!!

**Comment by zh-wowtv** [comment]
Can you give a example on `csvData`? Thanks.

**Comment by tz5514** [comment]
This issue saves my sleeping time. huge thanks!

**Comment by umihico** [comment]
To zh-wowtv 

Too late but I share for other people as example.

```
var rrows = [
    ["name1", "あいうえお", "some other info"],
    ["name2", "city", "more info"]
];
var csvData = rrows.map(e => e.join(",")).join("\n");
var BOM = "\uFEFF";
var    csvData = BOM + csvData;
var blob = new Blob([csvData], { type: "text/csv;charset=utf-8" });
saveAs(blob, "myFile.csv");
```

**Comment by pumpkindev** [comment]
o , i use Xlsx.js and works okay

**Comment by koonik** [comment]
It also works correctly when saving a file with swedish charset (encoded in iso-8859-2)! (thank you so much for this)

**Comment by gopinadh90** [comment]
How to save CSV file as ASCII?
I tried with type="text/csv;charset=ASCII" but its not working. Could you please help me?

**Comment by kotapeter** [comment]
You can also try this:

``` javascript
saveAs('data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,' + btoa(data), `PARTNER.csv`);
```

`data` is not blob type in this case.

**Comment by david-dasilva** [comment]
Thank you @ranabra you just saved my sanity :+1:

**Comment by gerodf** [comment]
obrigado...

**Comment by alexboisseau** [comment]
> This is not exactly an issue, rather it is a solution ( for example a solution to: #25 )
> 
> Solution: For all your special character needs, just use UTF-8, but additionally add a BOM to make sure the file is opened correctly. CSV for example was opened by Office Excel versions prior to Office 2007 with the wrong ANSI 1252 encoding by default. Adding a BOM will make the file open correctly (in UTF-8) in Office versions since Office 2007 (maybe needs Office SP for Office 2007)
> 
> ```
> var BOM = "\uFEFF";
> var    csvData = BOM + csvData;
> var blob = new Blob([csvData], { type: "text/csv;charset=utf-8" });
> saveAs(blob, "myFile.csv");
> ```

Works for me, thanks !
