### ISSUE TITLE
Require input completion before prepare and download

### ISSUE THREAD

**Issue by diganon** [eligrey/FileSaver.js#280]
Hello, I've been able to implement FileSaver.js without issue. Works great, but I'm curious about something. I've been using it with input fields that dynamically update divs in a separate container on the page. Everything works, but I'm curious if it is possible to require the inputs be completed before the prepared file is available for download. 

I'm thinking something along the lines of: 
```javascript
if($('input.required') === "" || $('input.required') === "placeholder"){
    // console alert box prompted
}else{
    // proceed with prepare and save. 
}
```
I've done some digging through the files and have yet to recognize how to do this if possible. Any input would be appreciated.

**Comment by jimmywarting** [comment]
Don't quite follow...

**Comment by diganon** [comment]
Sorry, let me try and explain it a bit clearer. 

I'm using filesaver.js to download a container of user-defined and predefined information on an intranet setup. When the user enters this specific page they are prompted with 5 or 6 input fields asking for information. As they fill out the input fields requesting information from the user a div container to the right dynamically updates with their input field updates placing them in the proper order with other predefined information (images, addresses, etc.)

Once the user has completed the input fields they click a button that preps the downloadable HTML file containing the div container and then replaces the prep button with a Save button that downloads the HTML file for us. 

Up to this point, everything works wonderfully. 

My question is I noticed that some people were leaving key input fields blank such as name and contact. I would like to make those required. Normally I'd just add "required" to an input field to do so, however, with FileSaver.js since it's not submitting anything in a traditional sense, it doesn't register those required options before prepping and saving out the file. 

My thought was to wrap the hook calling out the prep and save with the following code idea thinking I could force it to confirm any input not filled out with class would first prompt an alert box before allowing the prep and download: 

if($('input.required') === "" || $('input.required') === "placeholder"){
     // console alert box prompted
}else{
     // proceed with prepare and save.
}

But so far I've had no success in doing so and was hoping to get some thoughts.

**Comment by jimmywarting** [comment]
I don't see any problem with using `input[required]` actually only see benefits. You can hijack the submit and preventDefault. user will se a clear "popover" which fields are required and the input will be focused automatically on those which are required and empty

The benefit of using onsumbit also is that the event will only get trigerd once the form is valid

```javascript
$('form').on('submit' evt => {
  evt.preventDefault() // Stop the form from submitting a post request...
  // proceed with prepare and sa
})
```

**Comment by diganon** [comment]
Thanks Jimmy. I will give this a shot a bit later this afternoon and see how things turn out. Either way I'll come back and post with results. Thanks for the thoughtful advice!

**Comment by diganon** [comment]
Hello again Jimmy, 
I've tried implementing your suggestion, but I always seem to be able to save without it respecting the required fields. I've prepared a [JSFiddle](https://jsfiddle.net/jdcutter/qqhtz9gL/8/) for you to see how I'm using the script. Might you be able to shed some light on this for me? 

Thank you in advance.

**Comment by jimmywarting** [comment]
You only need to wrap everything in a `<form>` element

**Comment by jimmywarting** [comment]
Perhaps something like this: https://jsfiddle.net/qqhtz9gL/9/

**Comment by diganon** [comment]
That does indeed prompt the required field, but like a few of my previous attempts, it seems your example isn't able to download either.

**Comment by jimmywarting** [comment]
maybe cuz i didn't included filesaver.js
still an issue?
