### ISSUE TITLE
Safari v10 save XLSX

### ISSUE THREAD

**Issue by davidmir** [eligrey/FileSaver.js#281]
Hi,

Is there any way I can download xlsx files? Placing the content-type as text / csv or octet-strem is not a solution for this case. This stopped working on version 10 of the safari, because it simply opens a new tab and closes again.

Thanks

**Comment by huntingtonb** [comment]
Related? https://github.com/eligrey/FileSaver.js/issues/267

**Comment by shikelong** [comment]
+1 
also can't download xlsx in safari v10.

**Comment by shikelong** [comment]
Your can set the blob type to be 'application/octet-stream'. then will download a file named `Unknown`

**Comment by aralroca** [comment]
@shikelong Thank you for your solution! But there are any way to solve the filename? 😟

**Comment by Ruffio** [comment]
Can a live example in JSBin or similuar be provided? It might be a limitation in Safari...
