### ISSUE TITLE
Safari: Non user-triggered activations of anchors that have a download attribute are ignored.

### ISSUE THREAD

**Issue by steve-ng** [eligrey/FileSaver.js#282]
The way I am using FileSaver in Safari is as below

1. User click on a button
2. Download require file to format into csv
3. use `FileSaver.saveAs`

I am seeing this in the console `Non user-triggered activations of anchors that have a download attribute are ignored.`

The above works in Chrome, Firefox and Edge. Understand that this is a Safari item, but any insights to them? Not sure if the Safari team will be fixing this. 

Reference for the LOC from webkit at https://github.com/WebKit/webkit/blob/master/Source/WebCore/html/HTMLAnchorElement.cpp#L391

**Comment by Narretz** [comment]
Most browsers have require triggering certain actions, such as file downloads or opening windows, from user actions, such as clicks. Maybe something in fileSaver takes so long that it takes Safari over a certain threshold, which makes it consider the event as not user generated? This is also in the readme in the section about ios.

**Comment by steve-ng** [comment]
Yeh @Narretz is right. I did an ajax request when the user click the button before calling FileSaver.

**Comment by jimmywarting** [comment]
Nothing we can do, so i'm closing this
