### ISSUE TITLE
'Pass true for disableAutoBOM' has a wrong charset

### ISSUE THREAD

**Issue by linxdcn** [eligrey/FileSaver.js#283]
When I use the code blow
```
var file = new File([result], 'test.txt', {type: 'text/plain;charset=utf-8'});
saveAs(file,'test.txt', true);
```

it did remove BOM in the charset. But the charset of the file is ANSI instead of UTF-8.

Did I miss something?

**Comment by eligrey** [comment]
If you're on Windows, know that Windows doesn't store media type parameters in the NTFS filesystem. I think Chrome also drops the parameters on all OSes.

It seems like the only way to provide encoding hints in your case is to keep the auto-BOM enabled.
