### ISSUE TITLE
Saving very big files [+2 GB]

### ISSUE THREAD

**Issue by fr0gs** [eligrey/FileSaver.js#285]
Hello,

I stumbled upon this issue: [https://github.com/eligrey/FileSaver.js/issues/163](https://github.com/eligrey/FileSaver.js/issues/163).

I need to call a service via AJAX from the frontend (it needs to be cross-browser compatible), and the endpoint will feed me with a file bigger than 2GB and I need to save it into disk. 
According to the documentation this is not possible but from the previously referenced issue I don't know why it was closed as I don't see potential solutions other than the use of  **download** attribute in HTML5 (but not supported by IE11) or Streams (also not fully supported).

Is there any way of doing this?

**Comment by jimmywarting** [comment]
The only solution you have then is to set `content-disposition` header on the server.

**Comment by fr0gs** [comment]
I have already set that header, but I don't see the relationship. Afaik that header will specify wether or not the file is downloadable and an optional file name.

**Comment by jimmywarting** [comment]
If you are using the header method then you can't use ajax. the user needs to press a link or be redirected to it a iframe will work fine as well

**Comment by fr0gs** [comment]
The problem with the **a download** link is that is not supported by IE11.
I will try the iframe then

**Comment by jimmywarting** [comment]
it doesn't have to be a download attribute if content-disposition header is added

**Comment by jimmywarting** [comment]
Did you solve it?

**Comment by fr0gs** [comment]
Yes, using Content-Type & Content-Disposition headers from the server.
Also there was a very obscure redirection problem with nginx that made the
thing look like it was frontend problem.
