### ISSUE TITLE
Can't use the filesaver into onclick in <button></button>

### ISSUE THREAD

**Issue by pendave** [eligrey/FileSaver.js#286]
I have no idea why I can't use the filesaver into the button I create.

![7fw hr 9p y wt5 h9nq n](https://cloud.githubusercontent.com/assets/1331881/20828078/b994d922-b8b0-11e6-8016-655aa5ed4de8.png)

and if I do not use that myFuncton() I still not trigger the button.
```js
function handleSub(resData){
    var textholder = document.querySelector('section.section-module');
    var lyrics = resData;
    var title = 'aaaaaaaaaaaaa';
    var blob = new Blob([resData], {type: "text/plain;charset=utf-8"});
    console.warn(blob);
    var filesaver = saveAs(blob, title+".srt");
    textholder.innerHTML += '<textarea id="mbar" rows="4" cols="100">' + lyrics + '</textarea>';
    place.innerHTML += '<li><button id="mySave" onclick="fuction(){'+filesaver+'};">Create file</button></li>';
}
```

What can I do? Sorry for my poor skill as I'm a fresh man.

**Comment by pendave** [comment]
Even I put the myFunction() outside, it's not working

![v rn2k4e igb xaurhs8q](https://cloud.githubusercontent.com/assets/1331881/20828944/ceff7dae-b8b4-11e6-9b1c-14eb99833fe7.png)

**Comment by jimmywarting** [comment]
This is how you create code block in github markdown
![skarmavbild 2016-12-02 kl 12 12 15](https://cloud.githubusercontent.com/assets/1148376/20832102/ac1ce0be-b888-11e6-8203-e202147d3e9b.png)

**Comment by jimmywarting** [comment]
https://jsfiddle.net/drrnufp7/

**Comment by pendave** [comment]
Thank you,

I do it in similar way
```document.getElementById('mySave').addEventListener("click", function() {
        saveAs(blob, title+".srt");
    },true);```
