### ISSUE TITLE
FileSaver in Safari 10.0.1

### ISSUE THREAD

**Issue by danielbronder** [eligrey/FileSaver.js#288]
Hello everyone,

I am using this library for saving blob files, but is does not seems to work in Safari 10.0.1 (newest version) I am working with the newest version of macOS Sierra (10.12.1). I am getting this error:

![image](https://cloud.githubusercontent.com/assets/9819957/21004874/d6c0e5be-bd32-11e6-9d8a-f5e0019d64d6.png)

with the following link: 
blob:http://localhost:8080/c735eea0-4ff0-45bd-ac6b-125367953719

This is my code:

![image](https://cloud.githubusercontent.com/assets/9819957/21004916/1211b850-bd33-11e6-858e-c4b542731984.png)

I hope someone knows a fix for this.

**Comment by huntingtonb** [comment]
Related? https://github.com/eligrey/FileSaver.js/issues/267

**Comment by danielbronder** [comment]
It is related. Unfortunately there is not a fix yet for this. I hope there will be a fix soon.

**Comment by enyo** [comment]
I get `Failed to load resource: Frame load interrupted` in Safari 10. Is this the same issue?

**Comment by hanq** [comment]
I get Failed to load resource: Frame load interrupted in Safari 10 too.
after change code
`is_safari = /constructor/i.test(window.HTMLElement) || (function (p) { return p.toString() === "[object SafariRemoteNotification]"; })(!window['safari'] || safari.pushNotification)`
always get the same error.

**Comment by danielbronder** [comment]
I don't think this is still an issue. I solved the problem, I don't remember how I did it. It has been a while.
