### ISSUE TITLE
Can't open if the file was saved as xlsx

### ISSUE THREAD

**Issue by Eivlys** [eligrey/FileSaver.js#290]
hi,
I'm using
```js
var blob = new Blob([exportContent+document.getElementById("taskTable").innerHTML], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
});
saveAs(blob, current+"_export.xlsx");`
```
it can save the file but the excel can't be open properly, there's nothing in it.

if i change to `saveAs(blob, current+"_export.xls");` things would be ok, but how can i save as xlsx?thank you!

**Comment by jimmywarting** [comment]
You are saving html code, you need to convert the data

**Comment by Eivlys** [comment]
what form the data should be?string or object?

**Comment by Eivlys** [comment]
tried
`var blob = new Blob(['test'], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8" }); 
saveAs(blob, "export.xlsx");`

not working... Excel says the file format is invalid

**Comment by jimmywarting** [comment]
FileSaver doesn't modify the data in anyway if you save something like a photoshop file like psd and decide to name it 'dog.png' it won't convert the psd into a png file it will still be a psd file much like the one you are saving with test will just be some plain text.

The only thing FileSaver dose is saving a blob to the disk.
You need something like [SheetJS/js-xlsx](https://github.com/SheetJS/js-xlsx) to export the data binaries you need to get the correct data

**Comment by Eivlys** [comment]
Ok, thanks a lot!

**Comment by Eivlys** [comment]
That works well! Thank you !

**Comment by zh-wowtv** [comment]
@jimmywarting Looked through the document of js-xlsx, there is no example on how xls write work. (I can't make it work based on the document). Any example? Thanks.

**Comment by ak4wrapp** [comment]
@eivlys were you able to export as Xlsx? I am looking for same solution would be great if you could share some way to do it ..I am exporting div.innerHtML

**Comment by Eivlys** [comment]
@ak4wrapp I load shim.js, xlsx.core.min.js, Blob.js, FileSaver.min.js, and export-to-excel.js these 5 files to my project, and put a button in the html to get data from server then export to excel, noticed that the data should be an **array**.

the function of the button:
` var oo = [all,[]]; //all is the data i got from server
  var ranges = oo[1];
  var data = oo[0];
  var ws_name = "SheetJS";
  var wb = new Workbook(), ws = sheet_from_array_of_arrays(data);
  ws['!merges'] = ranges;
  wb.SheetNames.push(ws_name);
  wb.Sheets[ws_name] = ws;
  var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:false, type: 'binary'});
  saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), "allData.xlsx");`
check out this, [https://github.com/SheetJS/js-xlsx] ,it can help.

If you export page directly to xlsx, maybe you should transform what in the page to an array, then export it.

**Comment by acoillo** [comment]
@Eivlys De mucha ayuda tu comentario, gracias
