### ISSUE TITLE
Issue for the file downloading from the API

### ISSUE THREAD

**Issue by LamaBimal** [eligrey/FileSaver.js#291]
API responses the outputStream data and i am failure to convert it to the excel sheet?

**Comment by jimmywarting** [comment]
It's unclear what you are asking. Show us some code. what dose you data look like? what dose the api respond with?

**Comment by LamaBimal** [comment]
00\00\00\00 \00\00\00\00\00\00	 ï¿œ\00\00\00\00\00\00	\00\00ï¿œ\00\00\00\00\00\00\00	 ï¿œ\00\00\00\00\00\00
\00\00ï¿œ\00 ï¿œ\00\00\00\00\00\00
\00\00ï¿œ\00	 ï¿œ\00\00\00\00\00\00	\00\00ï¿œ\00	 ï¿œ\00ï¿œï¿œï¿œ\00ï¿œï¿œï¿œ\00ï¿œï¿œï¿œ\00ï¿œï¿œï¿œ\00\00ï¿œ\00ï¿œï¿œ\00ï¿œï¿œ`\00\00\00ï¿œ\00\00ï¿œ\00\00\00\00\00Reportï¿œ\00\00\00\00ï¿œ\00Z\00\00\00ï¿œR\00\00\00\00\00ï¿œ\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\003\00ï¿œ\00\00\00ï¿œ\00\00\00ï¿œA\00\00ï¿œ@\00\00@\00ï¿œ\00\00\00
\00\00\00\00\00\00ï¿œ\00\00ï¿œ\00\00\00\00\00\00\00\00\00\00\00ï¿œ\00ï¿œ\00\00L\00\00\00\00\00Date\00\00Version\00\00Description\00\00Author\00\00Analysed By\00\00Reviewed By\00\009/23/15 1:58 PM\00\001\00\00SPT DQR\00\00spt\00\009/23/15 3:10 PM\00\009/24/15 1:53 PM\00\0010/9/15 9:58 AM\00\0010/14/15 8:31 AM\00\0010/26/15 6:17 PM\00\0011/5/15 8:31 AM\00\0011/11/15 8:45 AM\00\0011/11/15 9:33 AM\00\0011/20/15 8:39 AM\00\0011/27/15 11:16 AM\00\0012/4/15 11:08 AM\00\0012/14/15 12:23 PM\00\0012/15/15 8:59 AM\00\0012/18/15 7:50 AM\00\0012/18/15 7:54 AM\00\0012/30/15 6:41 AM\00\0012/30/15 7:39 PM\00\001/1/16 6:30 AM\00\001/8/16 8:53 AM\00\001/12/16 2:00 PM\00\001/12/16 2:54 PM\00\001/12/16 3:57 PM\00\001/19/16 11:20 AM\00\002/23/16 11:05 AM\00\002/24/16 9:39 AM\00\002/26/16 10:41 AM\00\003/2/16 9:27 AM\00\003/3/16 10:14 AM\00\003/9/16 1:39 PM\00\003/11/16 10:33 AM\00\003/11/16 12:16 PM\00\003/15/16 3:50 PM\00\003/17/16 7:16 AM\00\003/21/16 12:53 PM\00\003/23/16 1:23 PM\00\003/29/16 9:13 AM\00\003/31/16 11:12 AM\00\004/1/16 8:09 AM\00\004/1/16 8:21 AM\00\004/1/16 8:22 AM\00\004/1/16 8:28 AM\00\004/1/16 8:42 AM\00\004/1/16 8:43 AM\00\004/1/16 9:02 AM\00\004/4/16 8:51 AM\00\004/6/16 2:02 PM\00\004/8/16 1:31 PM\00\004/8/16 2:31 PM\00\004/8/16 2:32 PM\00\004/15/16 2:09 PM\00\004/28/16 12:18 PM\00\005/6/16 12:17 PM\00\005/6/16 1:09 PM\00\005/11/16 11:46 AM\00\005/12/16 6:39 PM\00\006/3/16 1:39 PM\00\007/4/16 6:41 AM\00\007/6/16 6:32 AM\00\007/7/16 7:13 AM\00\007/7/16 7:32 AM\00\007/19/16 2:05 PM\00\007/20/16 3:53 AM\00\007/20/16 7:39 AM\00\008/2/16 5:06 PM\00\008/2/16 5:30 PM\00\008/4/16 10:24 AMï¿œ\00R\00\00W\00\00\00\00\00ï¿œ\00\00f\00\00\00/\00\00ï¿œ\00\00\00ï¿œ\00\00~\00\00Z	\00\00\00\00ï¿œ	\00\00ï¿œ\00\00~
\00\003\00\00\00\00ï¿œ\00\00ï¿œ\00\00I\00\00\00\00ï¿œ\00\00
\00\00\00	\00\00\00ï¿œ
ï¿œï¿œ\00\00\00\00\00\00^\00\00\00\00\00\00\00\00\00\00\00\00\00J\00\00\00\00\00\00\009\00\00-\00\00ï¿œ1\00\00
\00\00\00\00\00d\00\00\00\00\00\00\00\00\00\00ï¿œï¿œï¿œï¿œMbP?_\00\00\00*\00\00\00\00+\00\00\00\00ï¿œ\00\00\00ï¿œ\00\00\00\00\00\00\00\00\00\00%\00\00\00ï¿œ\00ï¿œ\00\00ï¿œ\00\00\00\00\00\00ï¿œ\00\00\00\00ï¿œ\00\00\00\00&\00\00rï¿œqï¿œï¿œ?'\00\00rï¿œqï¿œï¿œ?(\00\00rï¿œqï¿œï¿œ?)\00\00rï¿œqï¿œï¿œ?ï¿œ\00"\00\00d\00\00\00\00\00,,\00\00\00\00\00\00ï¿œ?\00\00\00\00\00\00ï¿œ?\00U\00\00\00}\00\00\00\00\00\00ï¿œ\00\

API responds the content in this format  which the stream of excel file.

And I am doing something like this my js file



```
 var record = new Blob([data],{ type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
                       download(data,"test.xls","attachment; filename='test.xls'");
                        console.log(record);

                    var link=document.createElement('a');
                    link.href=window.URL.createObjectURL(record);
                    link.download="myFileName.xls";
                    link.click();
                        var objectUrl = URL.createObjectURL(record);
                        console.log(objectUrl);
                        window.open(objectUrl
```)

**Comment by jimmywarting** [comment]
Are you using jQuery Ajax?

Try set the responseType to arraybuffer or blob 
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType

**Comment by LamaBimal** [comment]
@jimmywarting  I am using Angularjs using ngResource?, Can we convert the response data to arraybuffer in javascript?

**Comment by jimmywarting** [comment]
```js
var options = { responseType: "blob" }
$resource(url, [paramDefaults], [actions], options);
```

filesaver.js don't modify the binary in any way (it only helps you save it)

**Comment by LamaBimal** [comment]
It means, the binary contents will be saved to the xls file, it doesn't change it to readable form.

**Comment by jimmywarting** [comment]
@LamaBimal still an issue?

**Comment by LamaBimal** [comment]
responseType:'arraybuffer' solves by problem. Thanx #jimmyWarting
