### ISSUE TITLE
Cannot save utf-16 file stream

### ISSUE THREAD

**Issue by bargitta** [eligrey/FileSaver.js#292]
From the ajax call, I get data in utf-16 encoding, but FileSaver cannot save it as utf-16. What I get is a utf-8 encoding file, and cannot be used by end user. Is there a way to change this?

**Comment by jimmywarting** [comment]
How do you do the ajax call?

**Comment by bargitta** [comment]
I use a simple HTTP get request like below
`this.downloadService = function (bhaId, unitSystem, isDraft) {
     var url = '***';
     rturn $http.get(url);
};`
Then I have to call below utf8ToUtf16 to do the conversion.
`
 function utf8ToUtf16(str) {
                    var uArr = new Uint8Array(str.length * 2),
                        view = new DataView(uArr.buffer);
                    str.toString()
                        .split('')
                        .forEach(function (c, i) {
                            view.setUint16(i * 2, c.charCodeAt(0));
                        });
                    return uArr;
                }
`

**Comment by jimmywarting** [comment]
Try getting the response as blob instead of text
 
$http({
        url: "http://localhost:8080/example/teste",
        responseType: "blob"
    })

**Comment by bargitta** [comment]
It works, thanks!
