### ISSUE TITLE
Newlines removed in MS Edge 14

### ISSUE THREAD

**Issue by jamesarosen** [eligrey/FileSaver.js#293]
1. go to the [demo page](https://eligrey.com/demos/FileSaver.js/) in MS Edge v14
 2. enter text with multiple lines into "Saving Text"
 3. enter a filename
 4. slick Save

The saved file has the same contents, but without newlines.

### Example Text
```
1. hello
2. world
3. sømé åçcèñte∂ characters
4. "'quotes' within quotes"
```

**Comment by eligrey** [comment]
I'm unable to reproduce your issue in Edge 38.

**Comment by jamesarosen** [comment]
Edge 14 was released in August 2016 and Edge 15 is in prerelease. What's Edge 38?

**Comment by eligrey** [comment]
EdgeHTML 14 is the current release version of the rendering engine, and Edge 38 is the current release version of the Edge browser.

**Comment by jamesarosen** [comment]
Got it. Thanks :)

I was only able to test in a VM, so I'll trust you that an actual Windows machine is working fine :)
