### ISSUE TITLE
Filename:

### ISSUE THREAD

**Issue by nanihub** [eligrey/FileSaver.js#295]
I am trying to download attachments. 
Files may be in different format .txt,,.pdf or excel.
how to download a file with its own name and extension.
EX:    saveAs(blob, fileName);
if I give filename.txt then it wont support remaining formats.(here i dont want hard code the name and extension.)

**Comment by jimmywarting** [comment]
1. Download the file as a blob with ajax
2. save the blob with a other filename

eg
```js
fetch(url)
.then(res => res.blob())
.then(blob => saveAs(blob, 'custom filename.txt'))
```
