### ISSUE TITLE
save as type 

### ISSUE THREAD

**Issue by spyshow** [eligrey/FileSaver.js#296]
hi 
how can i set the "save as type" drop down to  a specific type so if the user change the name of the file and forgot to put the extension it will be added automatically

**Comment by jimmywarting** [comment]
There is only a "save as" method within this library.
You are responsible for creating the right blob data & filename.

**Comment by wildhart** [comment]
@jimmywarting I am having the same problem as @spyshow.  There is nothing to stop the user from deleting the default filename we provide and then saving the file without a file extension.

We need some API in `FileSaver.saveAs()` to force the "Save as type" to only allow "*.pdf" so if the user deletes the extension it will automatically be added back when the file is saved:

**e.g. If this is our code**
```
FileSaver.saveAs(new Blob([buffer], {type: "application.pdf"}), "filename.pdf")
```

**The user sees this:**

![image](https://user-images.githubusercontent.com/12505024/228791126-56d5296e-bc70-459f-b24d-44b73610af5c.png)

**But can change it to this:**

![image](https://user-images.githubusercontent.com/12505024/228791208-f15829f1-301c-4509-bb8f-80af2491d71d.png)

**Then the user cannot open the file:**

![image](https://user-images.githubusercontent.com/12505024/228791452-4a0421d5-3345-4ac0-97e8-a76945140a06.png)

Would it be possible to add an option to specify the filetype?

**Comment by jimmywarting** [comment]
This is not possible and will never be possible. this is how the web is built and there is nothing you can do to change it.

The only other solution is to use [File system access](https://github.com/WICG/file-system-access) and request read/write permission while asking for a folder with `showDirectoryPicker` and then write a file silently in the background. This is a totally different ball game, it requires unnecessary prompts and more risk for the users and it dose not work in all browser.
