### ISSUE TITLE
Get savepath

### ISSUE THREAD

**Issue by thomae82** [eligrey/FileSaver.js#297]
Hi there

I'm using FileSaver to save a blob to the disk. In my case the blob contains data of a PDF and I would like to  open the file once it has been saved. Therefore I need the full save path. How can I get it?

I tried the following without getting any information about the path choosen by the user: 

`let saver = filesaver.saveAs(blob, fileName);
 saver.onwriteend = function(a: any, b: any, c: any) {
    debugger;
};`

Cheers 

Marc

**Comment by jimmywarting** [comment]
* You can't get that kind of information from within a website due to security stuff
* You already have the pdf as a Blob/File so why do you need to know the path? You can just preview the pdf in the browser... Or do you want to open it with an external program?

**Comment by poberwong** [comment]
Yeah, I need to show a pdf with other program ...... so how to achieve it ?

**Comment by jimmywarting** [comment]
You can't. You need more permission.
