### ISSUE TITLE
can't save in another encoding

### ISSUE THREAD

**Issue by dmitryk1** [eligrey/FileSaver.js#301]
On a demo .xhtml in console try exec code:
```js
saveAs(new window.Blob(['АБВГДабвгд№123234345'], {
  type: "text/plain;charset=CP866"
}),"tf.txt")
```
file will save in "utf-8 no BOM"
Can I save in CP866? (charset=ASCII I'm try)
It need to exec on file "copy tf.txt prn" in DOS console that understand only ASCII.

**Comment by jimmywarting** [comment]
```js
FileSaver saveAs(Blob/File data, optional DOMString filename, optional Boolean disableAutoBOM)
```
With the third parameter you can disable auto BOM...
Try using an arraybuffer or typed array instead of string?
```js
new Blob([arraybuffer])
```

**Comment by dmitryk1** [comment]
I make encoder html2cp866. 
example code in that post:http://javascript.ru/forum/showthread.php?p=442796#post442796

**Comment by Ruffio** [comment]
This issue can be closed, right?
