### ISSUE TITLE
saveAs doesn't work in chrome 55.0.2883.87 m

### ISSUE THREAD

**Issue by pronan** [eligrey/FileSaver.js#302]
i.e. `saveAs(new Blob(['hello'], {type: "text/plain;charset=utf-8"}) , 'hello.txt')`

**Comment by pronan** [comment]
this is chrome's fault.

**Comment by jimmywarting** [comment]
[StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js) to the rescue
