### ISSUE TITLE
Downloading in Safari

### ISSUE THREAD

**Issue by junquera** [eligrey/FileSaver.js#303]
Hi!

I had some problems downloading files in Safari (one of these problems had been commented on other issues: I want it to be downloaded, not just opened), but I think I've found a solution.

Eluding technical concepts: Safari tries to open everything you give it, and if does not know how, rejects the operation. But one of the files type that knows how to open is ZIP (which are automatically deflated in the download folder). If we detect that we are running in Safari, we can zip the file we want to be downloaded (I'm testing with [zip.js](https://github.com/gildas-lormeau/zip.js)) and we'll be able to download any kind of file.

> P.S. I try to do it the better I can, but I'm still Spanish: Sorry for my english!

**Comment by harsharastogi** [comment]
I am facing similar issues, Safari tends to open the file on a new tab, instead of downloading it. How does one stop that, without zipping the file?

**Comment by aralroca** [comment]
Same problem 😫

**Comment by jmaicaaan** [comment]
Status?
