### ISSUE TITLE
How xls export works?

### ISSUE THREAD

**Issue by zh-wowtv** [eligrey/FileSaver.js#304]
I have an json string:

> [{"title":"News","description":"Great News 001","category":"Entertainment","secondCategory":"","tag":""}]

My code:

```js
let str = '[{"title":"News","description":"Great News 001","category":"Entertainment","secondCategory":"","tag":""}]';
let d = JSON.parse(str);
let blob = new Blob(d, {
  type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-16le"
});
FileSaver.saveAs(blob, "test.xls");
```
The result is not what I want.

<img width="238" alt="screen shot 2017-02-02 at 10 26 53 pm" src="https://cloud.githubusercontent.com/assets/18462946/22553293/2447d3fc-e997-11e6-9982-2222818bf667.png">

Any suggestion? Thanks.

**Comment by jimmywarting** [comment]
Did you have to bump so many other threads to ask how to do something?! 

FileSaver don't transform your JSON data in any way. This is just a tool to save Blobs.
You have to make sure your blob has the data in the right format you want to save it in

I recommend you to look at some xls parser/generator lib

**Comment by zh-wowtv** [comment]
@jimmywarting I could not find any document regarding this topic. An answer in stackoverflow mentioned the method I used. But apparently it's not correct. 

Thanks for your reply. That means I have to generate xls by my self and save it by FileSaver.

**Comment by jimmywarting** [comment]
That's correct
