### ISSUE TITLE
FileSaver is not working in Safari+IFRAME

### ISSUE THREAD

**Issue by NoelBroda** [eligrey/FileSaver.js#306]
Hi all!
I have a problem here. I have a button (that download a file) inside an `<iframe>`.

If I open the `src` of this iframe in a new tab, FileSaver is working well, but, if I leave it inside the iframe, FilerSaver is not working.

It's like Safari doesn't allow us to create a file, if the file is being created inside an iframe.

If you want to reproduce it, do it:
* Create a `a.html` with a `<iframe src="b.html">`
* Create a `b.html` file with a button that download a file using FileSaver.
* Open `a.html` in your browser and press the button. FileSaver will not work :(

**Comment by NoelBroda** [comment]
Any update here?

**Comment by Ruffio** [comment]
This could be a security restriction in the Safari browser. Can you provide a live example in JSBin or similuar?
