### ISSUE TITLE
Is IE 10 support really present?

### ISSUE THREAD

**Issue by djds4rce** [eligrey/FileSaver.js#309]
According to the README it says browser with IE10+ support. But 'Can I use' Mentions that blob builder isnt supported on IE 10.

http://caniuse.com/#search=blob

**Comment by unittester57** [comment]
Any update on this?

Even the demo link(saving text) is not working in IE10. Is saving text supported in IE10?

**Comment by Ruffio** [comment]
I just tried the demo site in IE 11 and I can both write text and draw some doodles save them and open the respective files again successfully. 

What is the issue? Have you tried the demosite in IE 11?

**Comment by djds4rce** [comment]
Doesn't IE 10+ imply support for IE 10 and above? That was the doubt. It
obviously works on IE 11
