### ISSUE TITLE
saveAs excel on Chrome installed on Macbook not working.

### ISSUE THREAD

**Issue by aki-84** [eligrey/FileSaver.js#311]
```
var blob = new Blob([document.getElementById('exportable').innerHTML], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"});
            saveAs(blob, "Test Report using FileSaver.xls");
```
I am using above code to export my DIV to xls. This works great on Windows (using Chrome), 
Since Safari support is yet not available I requested my users to install Chrome on their Macs but if they export excel on Macbook (Safari), the result file is all HTML instead of formatted data as on Windows. Any one can help please?

**Comment by aki-84** [comment]
Showing one of the sample
http://jsfiddle.net/TheSharpieOne/XNVj3/1/

<img width="462" alt="screen shot" src="https://cloud.githubusercontent.com/assets/25774879/23098079/de6c5910-f612-11e6-9dc6-967c44363a18.png">

**Comment by ak4wrapp** [comment]
Anyone was able to replicate it?

**Comment by eligrey** [comment]
FileSaver.js does not convert HTML into XLSX for you. Additionally, the mime type for XLS is `application/vnd.ms-excel`, not `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`. That mime type is for XLSX.
