### ISSUE TITLE
Exporting div to xlsx 

### ISSUE THREAD

**Issue by aki-84** [eligrey/FileSaver.js#312]
I am using filesaver.js to export my div (with multiple tables) to excel, I am able to export as XLS using below code

var blob = new Blob([document.getElementById('exportable').innerHTML], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
});
saveAs(blob, "Test Report using FileSaver.xls");
However, I want to export my div to XLSX. Can anyone help? I have tried changing the type to XLSX mime, but didn't help

**Comment by aki-84** [comment]
http://jsfiddle.net/TheSharpieOne/XNVj3/1/

**Comment by Chris3773** [comment]
You will need to create the content of the XLSX file before you call saveAs. The easier way is to create a CSV file as you only need to add the commas, quotes and line breaks.

**Comment by ak4wrapp** [comment]
var blob = new Blob([document.getElementById('exportable').innerHTML], {
type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
});
saveAs(blob, "Test Report using FileSaver.xls");


I already have the content ready and it's working fine to creat XLS file but want to know how can I create a XLSX file instead. Just changing MIME didn't help.

**Comment by Chris3773** [comment]
Change your call from `saveAs(blob, "Test Report using FileSaver.xls");` to `saveAs(blob, "Test Report using FileSaver.xlsx");`

**Comment by aki-84** [comment]
http://jsfiddle.net/XNVj3/2434/

nopes, excel cannot open it because of invalid format

**Comment by Chris3773** [comment]
You need to convert the content to the xlsx spec. Without the data in the correct format it will not open in Excel.

XLSX Spec: @https://msdn.microsoft.com/en-us/library/dd922181(v=office.12).aspx

**Comment by ak4wrapp** [comment]
Yes but that's exactly I am looking to get it through FileSaver.js

**Comment by travispulley** [comment]
I'm achieving this with sheetJS -> https://github.com/SheetJS/js-xlsx

**Comment by Ruffio** [comment]
@aki-84 has this 'issue' been resolved? As I read this 'issue' is about implementation of Excel in javascript and not a bug in FileSaver.js itself. IMHO this issue should be closed.
