### ISSUE TITLE
Livereloading chrome 

### ISSUE THREAD

**Issue by bhauteki** [eligrey/FileSaver.js#316]
In Chrome on MacOS the filesaver saveAs method seems to be break after the page is livereloaded.

The code is executed the same, it just doesn't trigger anything when reaching the line `click(save_link)`. It is solved by reloading the page in a **new tab**, so my guess is it's a Chrome bug.

**Comment by jimmywarting** [comment]
Have heard severals similar bugs when chrome auto updates but just needs to restart to work again

**Comment by Ruffio** [comment]
Can a live example in JSBin or similuar be provided?

**Comment by Shelley** [comment]
I have the same issue, did you solve it ?
