### ISSUE TITLE
Saving file from web worker?

### ISSUE THREAD

**Issue by travispulley** [eligrey/FileSaver.js#318]
Does anyone have some good ideas about using this from within a web worker? I figure it relies on creating a dom node, which isn't exactly possible to do, but could I trick it somehow with a faux replacement function? I'm already doing something like that the enable jquery (ver 2) in a webworker.

In particular, I'd need to emulate this the createElementNS function. Failing that, I figure the best approach is to send a blob through postMessage, but I want to avoid the overhead and potential out-of-memory errors.

**Comment by MoLow** [comment]
you shold use postmessage to send the main thread a Blob to save

**Comment by jimmywarting** [comment]
Sounds like you might want to use [SharedArrayBuffer](https://developer.mozilla.org/sv-SE/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) if you are worried about memory

**Comment by Ruffio** [comment]
This issue should be closed.

**Comment by travispulley** [comment]
Thanks for the advice - left this open way too long! Transferrables / SharedArrayBuffer is definitely the way to go. This tool has been very useful for producing xlsx docs!

**Comment by hoshino111** [comment]
Oh, but SharedArrayBuffer was already disabled in some new version browsers...

**Comment by jimmywarting** [comment]
If you use a service worker then you could make a download link, and save the blob directly from the worker. this is what the [streamSaver](https://github.com/jimmywarting/StreamSaver.js) lib dose
