### ISSUE TITLE
Corrupt File download from Azure Blob Storage

### ISSUE THREAD

**Issue by isaac2004** [eligrey/FileSaver.js#319]
I have a Excel Spreadsheet in Azure that I am exposing using a SAS and after downloading, it says the file is corrupt. Here is the code to save and uri

var result : any= {};
result.fileUri = 
"https://mystorageaccount.blob.core.windows.net/market-files/33b55b3c-8997-405c-af31-33f6f3e79daf?sv=2016-05-31&sr=b&sig=5Xw%2F4UPcdXbXrxd4mIcZUPQX%2FZzVZfDTQoTfr5V6NTY%3D&st=2017-03-16T18%3A00%3A12Z&se=2017-03-17T18%3A05%3A12Z&sp=rw";

```js
this.http.get(result.fileUri).subscribe(
                        (response: any) => {
                            var mediaType = 'application/octet-stream';
                            var blob = new Blob([response._body], { type: mediaType });
                            var filename = 'test.xlsx';
                            saveAs(blob, filename);
                        });

```
File is downloaded with correct filename but when I open it, I get an error in Excel saying the file is corrupt.

**Comment by jimmywarting** [comment]
You should fetch the resource as a blob instead of constructing one on your own.
browsers try to be smart about converting the response

```js
function load_binary_resource(url) {
  var req = new XMLHttpRequest();
  req.open('GET', url, false);
  //XHR binary charset opt by Marcus Granado 2006 [http://mgran.blogspot.com]
  req.overrideMimeType('text\/plain; charset=x-user-defined');
  req.send(null);
  if (req.status != 200) return '';
  return req.responseText;
}
```
> The magic happens in line 5, which overrides the MIME type, forcing the browser to treat it as plain text, using a user-defined character set. This tells the browser not to parse it, and to let the bytes pass through unprocessed. [Sending and Receiving Binary Data - MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data)


Therefore you should use `responseType = blob` or if you are using fetch (new ajax method):
```js
fetch(fileUri).then(res => res.blob()).then(blob => saveAs(blob, filename))
```

**Comment by jimmywarting** [comment]
Better answers would just be to refer you to this: http://stackoverflow.com/a/39690808/1008999

**Comment by isaac2004** [comment]
But what should the type be? Still stream?

**Comment by jimmywarting** [comment]
The type doesn't mather so much.as long as you are getting a blob back

**Comment by isaac2004** [comment]
I am sending a byte[] back from the Api.

**Comment by jimmywarting** [comment]
Ok.

If you have control over the backend then i would recommend you to save the file using only the server and a `content-disposition` attachment header if you can. it's more reliable. 
You won't get good safari support for saving files using FileSaver.

FileSaver is best suited for client side generated content. (Or where a simple GET request won't work)

**Comment by isaac2004** [comment]
how can I do that in Angular 2?

**Comment by jimmywarting** [comment]
You don't do it with Angular 2... You do it on the backend (the server)

See http://stackoverflow.com/questions/9195304/how-to-use-content-disposition-for-force-a-file-to-download-to-the-hard-drive

**Comment by isaac2004** [comment]
How do I make the request then? The api is secure so I need to make some form of get with headers. I can't use html5 download because I cannot change the filename.

**Comment by aebmknrl** [comment]
Hi @jimmywarting can you help me please? https://stackoverflow.com/questions/44336184/download-file-with-angular-and-filesaver-js-not-working
