### ISSUE TITLE
Filesaver not seem to work on safari

### ISSUE THREAD

**Issue by omershelef** [eligrey/FileSaver.js#322]
Get an error "Failed to load resource: Frame load interrupted" when trying to use in 
Safari

**Comment by mgarmash** [comment]
Same problem here.

Safari 9.1.1 (11601.6.17)

**Comment by samuelmatis** [comment]
Same.
Safari 10.0.3 (12602.4.8)

**Comment by chris-malloy-mri** [comment]
Does this work if you disable popup blocking?

**Comment by mir3z** [comment]
What's the status of this issue? Any way to download a blob on safari?

**Comment by zbug** [comment]
Any workarounds for Safari available?
