### ISSUE TITLE
saveAs not working on iOS 10.2.1

### ISSUE THREAD

**Issue by sthuber90** [eligrey/FileSaver.js#324]
I'm retrieving a file - usually `application/pdf` - as blob from a REST service and want to save/open it using `saveAs`. It works fine on IE11, Edge, Firefox, Chrome, but I can't get it to work on Safari and Chrome on iOS. Following happens, when I click the button that triggers the `saveAs` function:

- Chrome: blank tab with `about:blank` opens, but no file
- Safari: nothing happens

Unfortunately I don't have a Mac to look into the safari console on iPhone or iPad to see what actually happens. Tough I was able to make it work on iOS following some of the suggestions made in #12.

My code now looks like this:
```javascript
const saveThatFile = blob => {
        var reader = new FileReader();
        reader.onload = (e) => {
           if (window.navigator && window.navigator.msSaveOrOpenBlob) {
                // works on IE and Edge to save file, would also work on Chrome, Firedox for desktop
                saveAs(blob, attachment.file_name)
           } else {
               // Chrome, Firefox, and Chrome and Safari on iOS
               var dataUrl = reader.result;
               var open = window.open(dataUrl);
               if (open === null || typeof (open) === 'undefined') {
                      var blobUrl = URL.createObjectURL(blob)
                      window.location.href = blobUrl;
               }
           }
           this.setState({ disabled: false })
       }
       reader.readAsDataURL(blob);
}
```
I would much prefer to only call `saveAs` and leave the rest to it.

**Comment by awerlang** [comment]
A note about the snippet above: I'd open the window outside the load (asynchronous) handler. A popup blocker might block if not in direct response to an UI event. Other than that, thanks for this, I think it'll be helpful to me.

**Comment by sthuber90** [comment]
Thanks for the feedback, my actual issue was that I was using [mWater/FileSaver.js](https://github.com/mWater/FileSaver.js) from npm rather than the working one from @eligrey.
