### ISSUE TITLE
All punctuations in filename are converted into dash('-') automatically, how to disable it?

### ISSUE THREAD

**Issue by ravenjam** [eligrey/FileSaver.js#332]
I'm trying to save file with formatted timestamp. E.g.

2017/05/06 18:33 - 2017/05/07 22:14

I am 100% sure that the name passed to saveAs() function is correct, but when file is download, the name becomes:

2017-05-06 18-33 - 2017-05-7 22-14

Please let me know the solution to this problem. What is the intention of this automatic conversion. Thank you.

**Comment by eligrey** [comment]
Your browser and/or operating system did this. FileSaver.js is not involved in this process. Very few filesystems allow the `/` character in file names, as it is normally used in user interfaces as a directory separator.

**Comment by jimmywarting** [comment]
Bad practice to have slash in the filename
