### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [eligrey/FileSaver.js#336]
it is a way for saving a file as a stream of chunks without building all in memory?

stream is saved when is passed.

**Comment by jimmywarting** [comment]
With FileSaver you would need every bit of data before you call the saveAs method.
The only thing it accepts is a Blob/File

If you are looking for some streaming capability then maybe [StreamSaver](https://github.com/jimmywarting/StreamSaver.js) is something for you but it has it limits, atm it only supports Chrome & Opera and you only got like 10 minutes to save something before the service worker forces shutdown and breaks the download

**Comment by publicocean0** [comment]
Very interesting :) thanks a lot :)
