### ISSUE TITLE
FileSaver does not accept styles?

### ISSUE THREAD

**Issue by CarlosTheory** [eligrey/FileSaver.js#337]
Is there any way possible to print an Image as background using FileSaver? I'm trying using a background with css into the canvas, but it is not working.

**Comment by jimmywarting** [comment]
You need to paint the background image onto the canvas if you are trying to save that as an image

**Comment by CarlosTheory** [comment]
@jimmywarting Yess, with drawImage() it works just perfect!!!!!! Thank you :DD

**Comment by themaniac** [comment]
Could you please give an example for doing this? Thanks in advance :)
