### ISSUE TITLE
saveAs doesn't work on microsoft Edge

### ISSUE THREAD

**Issue by pecnik** [eligrey/FileSaver.js#338]
The function saveAs doesn't work in Edge, it throws no error or warning, it's just silent.

Edge info:
Microsoft Edge 40.15063.0.0

```
var fileSaver = require('file-saver');

download (file) {
    const fileModel = this.$model.create('message', 'files');
    fileModel.fetch(file.id).then(function(response){
            let fileObj = new File([response.body], file.filename);
            fileSaver.saveAs(fileObj, file.filename); // Does nothing on edge, works on chrome and other browsers
    });
},
```

**Comment by jimmywarting** [comment]
If the file is coming from the server and you have the possibility to change headers, then i would recommend you to use content-disposition attachment header - it has better browser support

---

The fetch api's `Response.prototype.body` is a ReadableStream not a File, or Blob.
The saveAs method don't accept a stream.

You would have to do: 
```js
fileModel.fetch(url)
  .then(function(response) {
    return response.blob();
  })
  .then(function(blob) {
    fileSaver.saveAs(blob, file.filename);
  })
```

And the reason why it dosn't throw a error is cuz you wrapped it in a promise.
you would have to do `...).catch(console.log)` to see the error
 

---

PS. use arrow fn
```js
fileModel.fetch(url)
  .then(response => response.blob())
  .then(blob => fileSaver.saveAs(blob, file.filename))
```

**Comment by pecnik** [comment]
Works like a charm!
Many thanks, you're a lifesaver :)


I don't know why, but i cant open local domains in Edge. 
Which made the debugging process a nightmare.
