### ISSUE TITLE
Exporting with Multiple Sheets

### ISSUE THREAD

**Issue by HeroSony** [eligrey/FileSaver.js#339]
How to export excel with multiple sheets?

**Comment by jimmywarting** [comment]
Just pass the binary (blob/file) to `saveAs`
this lib won't help you make a excel file, just help you save files

**Comment by HeroSony** [comment]
Hello, jimmywarting
This is my code and it works fine.
`
template = ...;
blob = new Blob([template], {
	    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
	});
saveAs(blob, "test.xls");
`
but I want to make multiple sheets in one file in this case test.xls,  how should I deal with it?
As you said do I need to try another way beside filesaver.js?

Thank for pay attention!

**Comment by jimmywarting** [comment]
You can still use FileSaver.
But you have to format `template` to include multiple sheets in the same file

I don't know how you create/get the template but maybe [SheetJS](https://github.com/SheetJS/js-xls) is something for you?

```js
/* bookType can be any supported output type */
var wopts = { bookType:'xlsx', bookSST:false, type:'binary' };

var wbout = XLSX.write(workbook,wopts);

function s2ab(s) {
  var buf = new ArrayBuffer(s.length);
  var view = new Uint8Array(buf);
  for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
  return buf;
}

/* the saveAs call downloads a file on the local machine */
saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), "test.xlsx");
```

**Comment by Ruffio** [comment]
@HeroSony is this still an issue? As I read it, the 'issue' is not about saving a file usgin FileSaver.js but more a question about an implementation of Excel in javascript. IMHO this issue should be closed...

**Comment by Ruffio** [comment]
@eligrey Consider to close this question. It was created May 2017, I pinged July 2017 but with no response. It is a question about implementation, not an bug/issue.
