### ISSUE TITLE
$http data empty

### ISSUE THREAD

**Issue by ltuttini** [eligrey/FileSaver.js#340]
Hi
I am following the example 

[Downloading/streaming Azure Storage private container blobs to AngularJS through .net WebAPI](http://cmikavac.net/2015/10/18/downloadingstreaming-azure-storage-private-container-blobs-to-angularjs-through-net-webapi/)

but the data receives in $http success always is string empty
If I change the $http header with 

    headers: { Accept: "application/octet-stream" },

then I could receive the file content in data parameter, but it's bigger than the original file, but example if the file in blob storage has 9Mb in the client the saved file has 16Mb.

Do you know, how I have to define header or the response from server side to receive the file correct?

thanks
regards

**Comment by jimmywarting** [comment]
If the file is coming from the server and you have control over the response headers, Then I really recommend you to use content-disposition attachment header to download the file...

**Comment by ltuttini** [comment]
hi @jimmywarting 
thanks for you help

The file is sended from Azure Blob Storage, and use WebApi, the article use the following code to define the response:

        protected IHttpActionResult AzureBlobOk(AzureBlobModel azureBlob)
        {
            var response = Request.CreateResponse(HttpStatusCode.OK);
            response.Content = new StreamContent(azureBlob.Stream);
            response.Content.Headers.ContentType = new MediaTypeHeaderValue(azureBlob.ContentType);
            response.Content.Headers.Add("x-filename", azureBlob.FileName);
            response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");
            response.Content.Headers.ContentDisposition.FileName = azureBlob.FileName;
            response.Content.Headers.ContentDisposition.Size = azureBlob.FileSize;

            return ResponseMessage(response);
        }


I can see in the response the assignment of `content disposition` in the line

      response.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment");


regards

**Comment by jimmywarting** [comment]
If there already is a content disposition header then it should just be to open the url...
