### ISSUE TITLE
Unknown error on android after download

### ISSUE THREAD

**Issue by cordasfilip** [eligrey/FileSaver.js#342]
Document gets downloaded but shows Unknown error at the end when I go to downloads I can open document just fine but the error is there. This is only on chrome on S7, A5 works fine on firefox on same devices. Anyone else experienced this issue?

**Comment by Aequitatem** [comment]
Have this exact issue as well, only in chrome on my Google Pixel. Get 'download failed due to an unknown error' even though the file has downloaded fine. Works fine in firefox.

**Comment by cordasfilip** [comment]
Duplicate of #330
