### ISSUE TITLE
Blank page on Chrome iOS

### ISSUE THREAD

**Issue by rakeshpai** [eligrey/FileSaver.js#343]
I'm using FileSaver along with JSZip. I've looked at #179 and the fix by @ph4r05 in #240, so I was hoping things would just work in Chrome iOS, but I might be doing something wrong, maybe?

While JSZip has an async API ([example](https://stuk.github.io/jszip/)), I've tried doing the async work first without waiting for user input, and simply calling `saveAs` directly from a button click, but that only shows me a blank new tab in Chrome iOS, with a progress bar at the top that seems to indicate that the download is nearly done, but it never finishes.

When I was doing the JSZip recommended async approach, it wouldn't work in iOS Safari either, resulting in the same behavior (blank tab, appears to be downloading, no actual activity). However, with when I made the call sync, it now works in Safari (albeit with the `Unknown` file name). However, making it sync didn't change the behaviour in iOS Chrome.

```
let content;
// prepare the zip file
zip.generateAsync({type:"blob", mimeType: 'application/octet-stream'})
   .then(c => content = c);

const save = () => saveAs(content, 'test.zip');
```

The `save` function above is called directly from a button click event, so even if JSZip is async, the button click is sync.

I would appreciate any help I can get.

**Comment by owenblacker** [comment]
I'm having a similar problem, where I would have expected Chrome on iOS to Just Work™, given it supports Blobs and iOS 11.4 ships with the Files app, which should allow filesystem access.

Our code in this area is pretty simple:

    function save(dataBlob, filesize) {
      saveAs(dataBlob, 'filename.png'); // FileSaver.js function
    }

where `dataBlob` is created from `HTMLCanvasElement.toBlob` and `filesize` can clearly be disregarded.

Does this library straight-up just not work on iOS or is there something different we should be doing here?

**Comment by james2406** [comment]
I'm also running into a similar issue when working with the `text/calendar` type:

```
const reader = new FileReader();
const blob = new Blob([calendarData], { type: 'text/calendar' });
reader.onload = (event) => window.location.href = reader.result;
reader.readAsDataURL(blob);
```

It works completely fine in safari iOS but just loads a blank page on chrome iOS
