### ISSUE TITLE
Cannot create wav file from octet stream

### ISSUE THREAD

**Issue by lararogu** [eligrey/FileSaver.js#344]
I am trying to download a stream from a blob storage and when I save it as a wav file I am unable to reproduce it on my computer
var blob = new Blob(httpResponse, { type: "application/octet-stream" });
saveAs(blob, filename + ".wav");

The httpResponse has the wav audio format:
RIFFD)........WAVEfmt.....................

Any ideas?

**Comment by jimmywarting** [comment]
Must start making a wiki page about this same kind of question

I will make it sort this time.
 - Download the response as blob (using `responseType = 'blob'`)
 - Or if u are using fetch (`res.blob()`)
 - If the file is coming from the server u might as well use `content-disposition` attachment header, it has better cross browser support and don't need any javascript

**Comment by lararogu** [comment]
But the response is not a blob object ,is an array of bytes from a wav file.
The file is created fine but it is corrupted.

**Comment by jimmywarting** [comment]
what do you mean with it's an array?
Can you show me the hole method you use to download the wav file?

**Comment by lararogu** [comment]
The method to get the audio file from the server is as follows:
           string sasBlobToken = cloudBlob.GetSharedAccessSignature(sasConstraints);
            string uri = cloudBlob.Uri + sasBlobToken;
            var stream = await cloudBlob.OpenReadAsync();
            byte[] signal = null;
            MemoryStream m = new MemoryStream();
            if (cloudBlob != null)
            {
                cloudBlob.DownloadToStream(m);
            }
        
            return m.GetBuffer();

Then I call this method in my angular controller:

 auscultationSvc.getWav().success(function (item) {
             var blob = new Blob([item], { type: "audio/x-wav" });
             saveAs(blob, "audio.wav");
}

**Comment by d1820** [comment]
I am having same issue
```
let blob = new Blob([downloadResult.file], {type: downloadResult.contentType});
    FileSaver.saveAs(blob, downloadResult.fileName, true);
```

file gets created but is corrupt

if do a hex diff seems to be thinking its UTF-8 and re-encoding bytes

![image](https://user-images.githubusercontent.com/377631/27978978-91d3c138-6327-11e7-89da-61c1d83ba17c.png)

**Comment by Ruffio** [comment]
@lararogu this issue looks like it has been resolved. Presse close it if resolved.
