### ISSUE TITLE
not work on MS edge and ie11

### ISSUE THREAD

**Issue by aliloubm** [eligrey/FileSaver.js#345]
hi,
I tested on i11 and edge the demonstration.
Can not download a file

 https://eligrey.com/demos/FileSaver.js/

**Comment by LJ2319** [comment]
I am experiencing a similar issue. The Save As dialog pops up but the save gets stuck on 'resuming...' like there is no file.

**Comment by jimmywarting** [comment]
can you try if the download attribute works in edge?

**Comment by Hongbo-Miao** [comment]
Same here, failed at Edge. @jimmywarting what do you mean "download attribute"? I can help try.

**Comment by Hongbo-Miao** [comment]
One thing I found

This code works in Chrome, failed in Edge without any error (Didn't test on Firefox, Safari at that time)

```js
const f = new File([arrayBuffer], file.name, { type: file.contentType });
saveAs(f);
```

This code works in Chrome, Firefox, Safari, and Edge

```js
const b = new Blob([arrayBuffer], { type: file.contentType });
saveAs(b, file.name);
```

Hope it helps.

**Comment by Ruffio** [comment]
Is this still an issue?

**Comment by raldan** [comment]
This is still an issue in version 41.16299.248.0 , when you try to download a file in private mode

**Comment by Ruffio** [comment]
I just tried the Demo site in latest Edge (41.162...).

I can conclude the same as you :-( 
In normal mode you can open and save the file to disk without any issues, but in InPrivate mode the file is never opened/saved to disk and you never get an error message or so about :-( Nothing in console either.

I don't know if this is a limitation in Edge. Anyone?
