### ISSUE TITLE
Opening up in same Tab in Safari on iPhone

### ISSUE THREAD

**Issue by Toterbiber** [eligrey/FileSaver.js#346]
In Safari on my iPhone / iPad the File (PDF) does not open up in a new Window but in the same Window, so I have to navigate back to the Page where I came from.

It should open up in a new Tab as described.

_If you can't confirm this issue I can show you, but I don't want to publish the URL right here._

**Comment by usecode** [comment]
Yes I agree. File should be open in new tab.
iPhone 5 iOS 10.3.2

**Comment by awerlang** [comment]
Here, we explicitly create another window and navigate to it. There's already some provision for this workaround on this module, but line https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L126 needs to exclude iOS.

**Comment by lakefield** [comment]
Same issue with iOS 11.3. Opens in same window.

Anyone find a workaround to trigger a new window/tab?

**Comment by phuczeero** [comment]
Confirmed. I think this issue depends on Safari on iOS.
I've created 2 apps from [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) and [CRA](https://github.com/facebook/create-react-app) with the same implementation.

Import dependencies
```
import { saveAs } from 'file-saver';
import jsdocx from 'jsdocx';
```

and render a button
```
<button onClick={() => {
  const doc = new jsdocx.Document();
  doc
    .addParagraph()
    .addRun()
    .addText('Hello World!');
  doc.generate().then(content => {
    saveAs(content, 'test.docx');
  });
}}>
  Click me
</button>
```

When clicking the CRA button, Safari opens new tab and displays blob data.
But in react-boilerplate, Safari navigate to blob url.

**Comment by Bonfims** [comment]
Still having the issue, blobs only opening in the current tab
