### ISSUE TITLE
Bower registration problem

### ISSUE THREAD

**Issue by mondalaci** [eligrey/FileSaver.js#35]
Tried to register FileSaver with Bower but screwed up the URL: https://github.com/bower/bower/issues/120#issuecomment-20373840

Paul Irish said that "something is busted with the FileSaver package": https://github.com/bower/bower/issues/120#issuecomment-20685958

Whatever the problem is I thought I better open an issue there to track it from there.

**Comment by TuningGuide** [comment]
@eligrey  Hy, why is this ticket closed? I could not find a FileSaver package for bower which is owned by eligrey, only one which is owned by Teleborder. Regards
