### ISSUE TITLE
Error download message on android device

### ISSUE THREAD

**Issue by HarelM** [eligrey/FileSaver.js#350]
I'm not sure if there is a problem with my code or an issue with this library.
I'm using the following code (`data` is binary data I get from my server):
```
        var byteCharacters = atob(data);
        var byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        var byteArray = new Uint8Array(byteNumbers);
        var blobToSave = new Blob([byteArray], { type: "application/octet-stream" });
        saveAs(blobToSave, fileName);
```
The file is saved on my android device but I get an error message from the operating system telling me the download failed although the file is valid and stored on my phone...
Are you aware of such an issue?
Here is the bug I'm tracking on my site:
https://github.com/IsraelHikingMap/Site/issues/398
The screenshots are in Hebrew but the message states there was an error downloading.

If you can guide me to an initial plunker with file-saver I can try and see if I can reproduce it.

**Comment by sdanielspq** [comment]
I'm having the same issue as described above.

**Comment by HarelM** [comment]
Yay! I thought I was the only one :-) any idea how to address this? where to start looking for the issue? I'm quite clueless...

**Comment by sdanielspq** [comment]
I'm still looking into it, but I have only one Android device to test with. It's a Samsung Galaxy S7 using Android Nougat. The phone is using Chrome and not the Samsung browser.

**Comment by HarelM** [comment]
If you have a solution or test code you want me to try out let me know, I can publish it to my site and ask people to test it.

**Comment by dmnsgn** [comment]
Duplicate: https://github.com/eligrey/FileSaver.js/issues/330 ?

**Comment by HarelM** [comment]
Probably, I'll continue the thread there.

**Comment by Ruffio** [comment]
@HarelM if you continue at https://github.com/eligrey/FileSaver.js/issues/330 can this 'issue' then be closed?

**Comment by HarelM** [comment]
Sure, closing. I hope the code suggested there will make it into the library so I can remove the code from my site...
