### ISSUE TITLE
[Question] Is it possible to simply download from a url?

### ISSUE THREAD

**Issue by nealoke** [eligrey/FileSaver.js#351]
I have been trying and searching to simply download a file from a full path. So basically I display a bunch of images and when the user clicks on it it should download that image. I can't seem to get it to work, any ideas?

**Example url**
`http://www.test.com/someimage.png`

**Comment by Ruffio** [comment]
Cross site download from javascript is often not allowed. You can use native javascript or fx. Jquery to download file from own site.
This issue should be closed.
