### ISSUE TITLE
TypeError: Failed to construct 'File': Iterator getter is not callable.

### ISSUE THREAD

**Issue by zymr-keshav** [eligrey/FileSaver.js#357]
Using _macOS Sierra 10.12.5_ and angular **1.6** and FileSaver v **1.3.2** and checking into Chrome 60

I need to download one HTTP response data ( object)  as `inputData`  as a json file and using below approach
     
using file type in **Blob()** and 2 parameters in `saveAs()` is working fine 

```js
var fileData = JSON.stringify(inputData, undefined, 4); // first use JSON.stringify 
var blob = new Blob([fileData], {type: "text/json;charset=utf-8"}); // save as Blob 
var fileName = "Report.json";
saveAs(blob, fileName);  
```
But why this is not working when we setting 3rd parameter as file type in **File()**  and than save this ( as per suggested in README.md)

```js
var file = new File(blob, fileName, {type: "text/json;charset=utf-8"});
saveAs(file);
```
nor even this way ( only write the file type in **File()** )

```js
var saveText = JSON.stringify(inputData);
var file = new File(saveText, fileName, {type: "text/json;charset=utf-8"});
saveAs(file);
```

why we need to write file type in Blob() constructor not in File() constructor?

Kindly provide me some understanding here.

**Comment by jimmywarting** [comment]
http://caniuse.com/#feat=fileapi

You are likely testing this on IE or edge, they only partly support File object, you can get them from file input but not create them yourself

**Comment by zymr-keshav** [comment]
I have checked and it says I can use FileSaver.js in my system. I have added as an array `[saveText]` because I thought it is necessary? isn't it?

**Comment by jimmywarting** [comment]
You can use filesaver, but you can't use the File constructor allways.

If you like you could use this to try and fix the constructor.

```js
 // Fix so you can construct your own File
  try {
    new File([], '')
  } catch (a) {
    window.File = function(b, d, c) {
      const blob = new Blob(b, c)
      const t = c && void 0 !== c.lastModified ? new Date(c.lastModified) : new Date

      Object.defineProperties(blob, {
        name: {
          value: d
        },
        lastModifiedDate: {
          value: t
        },
        lastModified: {
          value: +t
        },
        toString: {
          value() {
            return '[object File]'
          }
        }
      })

      if (window.Symbol && Symbol.toStringTag) {
        Object.defineProperty(blob, Symbol.toStringTag, {
          value: 'File'
        })
      }

      return blob
    }
  }
```

**Comment by Ruffio** [comment]
@zymr-keshav has this issue been resolved and can be closed?

**Comment by jimmywarting** [comment]
I think this will not be anything filesaver will take care of. I provided a polyfill for constructing a File but the safest way is to construct a Blob and send a filename (using both argument)
