### ISSUE TITLE
FileSaver downloading a file that can not be opened

### ISSUE THREAD

**Issue by tahajaha** [eligrey/FileSaver.js#358]
Hello,I am new to angular 2 and I am working on a .net core and angular 2 solution, what I want to do is to download a webpage as a word document, I am getting to download the file .dotx but i cannot open it. 
here's my component : 

   ```
 download() {

        let actionUrl = this.config.Server + 'api/generation/word/';
        this.http.get(actionUrl + this.service.getCV().id).subscribe(console.log, console.log);

        let DownloadContent, popupWin;
        DownloadContent = document.getElementById('templateFrame').innerHTML;
        let byteNumbers = new Uint8Array(DownloadContent.length);
        for (var i = 0; i < DownloadContent.length; i++) {

            byteNumbers[i] = DownloadContent.charCodeAt(i);

        }

        var blob = new Blob([byteNumbers], {
            type: 'text/dotx;charset=utf-8'
        });

        FileSaver.saveAs(blob, "CV.dotx");

        popupWin = window.open('', '_blank', 'top=0,left=0,height=100%,width=100%');
        popupWin.document.open();
        popupWin.document.write(`${DownloadContent}`);
        popupWin.document.close();

    }
```
 any help would be greatly appreciated.

**Comment by Ruffio** [comment]
Please close this 'question'. It is better suited for a forum like stackoverflow or similuar.

**Comment by Ruffio** [comment]
This should be closed

**Comment by jimmywarting** [comment]
Referring you to wiki of how to [Saving a remote file](https://github.com/eligrey/FileSaver.js/wiki/Saving-a-remote-file)

Basically... Try to use [content-disposition attachment header](https://github.com/eligrey/FileSaver.js/wiki/Saving-a-remote-file.#using-http-header) if possible and  it works better cross browser and you will not need filesaver.

If not then try to download the file as a blob and do not construct your own blob. Angular has a way to set the response type to blob
