### ISSUE TITLE
 n().createObjectURL' is not a function issue in Opera 12.16

### ISSUE THREAD

**Issue by arunknair** [eligrey/FileSaver.js#359]
The below error is observed when downloading xls files in angularjs. Works fine with all other browsers. Please guide me with an answer as I am new with the technology

Error: 'n().createObjectURL' is not a function
<anonymous function>([arguments not available])@https://localhost:<>/assets/js/FileSaver.min.js:74
<anonymous function>([arguments not available])@https://localhost:<>/assets/js/FileSaver.min.js:108
<anonymous function>([arguments not available])@https://localhost:<>/assets/js/FileSaver.min.js:113

**Comment by Ruffio** [comment]
Can you provide a live example on JSBin or similuar?

**Comment by jimmywarting** [comment]
opera 12.16 is way over due date. it's 5 years old, just update the browser
