### ISSUE TITLE
how to saveas xls/csv/html

### ISSUE THREAD

**Issue by adityos2003** [eligrey/FileSaver.js#360]
hello jim, i'm get source 
from : 
1. https://github.com/fbrussa/NovixPivotJS
2. https://github.com/juantascon/jquery-handsontable-csv
3. https://github.com/eligrey/FileSaver.js/issues/new

do you help me how to convert save xls/csv/html

![view export3](https://user-images.githubusercontent.com/23629493/29204217-e3a9c10e-7e9f-11e7-8cdc-a57679899312.jpg)

do you choose order by link js above : 
1.demo.js
2.demo.min.js
3.filesaver.js
4.filesaver.min.js
5.jquery-handsontable-csv.js
6.novix.pivot.renderer
7.pivot.js

and then above source novixpivot index.html : 

<body >
	<div class="diagramWrapper">
		<div id="output" class="pane"></div>
	</div>
	<span class="changesOutput" ></span>
<script type="text/javascript">

    $(function () {
	
	
			var renderers = $.extend({},$.pivotUtilities.novix_renderers, $.pivotUtilities.highchart_renderers);
	
			$.getJSON("mps.json", function(mps) {
			
				$("#output").pivotUI(mps, {
					renderers: renderers,
					rows: ["Party","Province"],
					cols: ["Age","Gender"],
					rendererName: "Input Table",
					rendererOptions: {
						onEditValues: function (changes) {
							$(".changesOutput").html(JSON.stringify(changes));
                        },
						onDrawTable: function (htTable) {
                            $(".changesOutput").empty();
                        },
					}
				});
			});

       
    });

</script>

<br>
<form id="html-options">
            <label>Filename: <input type="text" class="filename" id="html-filename" placeholder="a rich document"/>.xhtml</label>
            <input type="submit" value="Save"/>
        </form>

how add the source that run ? and then  convert save xls/csv/html 

thanks in advance jim

**Comment by Ruffio** [comment]
Please close this question. This is for a forum, not an issue tracker...
