### ISSUE TITLE
TypeError: __webpack_require__.i(...) is not a function

### ISSUE THREAD

**Issue by shumjas1** [eligrey/FileSaver.js#363]
I'm a newbie in coding and I'm trying to learn the MEAN stack and in the site I'm building I can upload files just fine with ng2-file-upload and have been trying to use FileSaver to download the files from my server but, I'm getting this error: TypeError: __webpack_require__.i(...) is not a function when it gets to the line 

`SaveAs(blob, filename);`

This is my code on the server side:
```
router.post('/download', (req, res, next) => {
  var file = DIR + "/" + req.body.file
  res.download(file, req.body.file, (err) => {
    if(err) {
      if(res.headersSent) {
        console.log(err)
      } else {
        return res.status(200).json({success: true})
      }
    }
  })
})
```

and on client side:

```
saveFile(file) {
    const headers = new Headers();
    headers.append('Accept', 'text/plain');
    this.http.post('http://localhost:8080/leases/download', {file: file + ".txt"}, { headers: headers })
      .toPromise()
      .then(response => this.saveToFileSystem(response, file));
  }

  private saveToFileSystem(response, file) {
    const filename = file + ".txt";
    const blob = new Blob([response._body], { type: 'text/plain;charset=utf-8' });
    SaveAs(blob, filename);
  }
```

I can't seem to figure out what's causing this issue, any thoughts? Sorry if I'm posting this in the wrong place!

**Comment by eligrey** [comment]
Fixed by #391
