### ISSUE TITLE
in IE 11, FileSaver.js changes file name

### ISSUE THREAD

**Issue by xxjapp** [eligrey/FileSaver.js#366]
For example: 

[VSCodeSetup-x64-1.14.2.exe]
 =>
[VSCodeSetup-x64-1.14.2HTF51L0S.exe]
[VSCodeSetup-x64-1.14.25YNMMARH.exe]
...

**Comment by Ruffio** [comment]
What is the issue here? Can you provide a live example by using JSBin or similar?

**Comment by xxjapp** [comment]
I can't reproduce this problem now.
