### ISSUE TITLE
after exported excel some fields has ambigous  character e.g. "Ù†Ø§Ù… Ù‡Ø´ØªÚ¯  " for less than ten records

### ISSUE THREAD

**Issue by ehsanlotfi** [eligrey/FileSaver.js#369]
export excel not work for less than ten unicode(UTF-8) rows.
please fix it.

**Comment by ehsanlotfi** [comment]
???????

**Comment by ehsanlotfi** [comment]
??!!!??

**Comment by Ruffio** [comment]
Please close this 'question'

**Comment by jimmywarting** [comment]
I think you generate the blob incorrectly, how to you get the blob?
