### ISSUE TITLE
The file format and extension of 'file.xls' dont match.

### ISSUE THREAD

**Issue by Harshagracy** [eligrey/FileSaver.js#372]
Hi 

I am getting this error while trying to open the excel file that is downloaded. is there a way to get rid of this message?

**Comment by Harshagracy** [comment]
The file format and extension of 'file.xls' don't match.

**Comment by isaaccast** [comment]
Hello, 

Any updates on this issue? I am experiencing the same issue on Google Chrome, Mac OS Sierra.

**Comment by jimmywarting** [comment]
are you creating the blob correctly? how do you download/generate the blob?

**Comment by Ruffio** [comment]
@Harshagracy , @isaaccast  have you hot a simple testcase showing the issue?
