### ISSUE TITLE
saving Three.js

### ISSUE THREAD

**Issue by alvinwan** [eligrey/FileSaver.js#373]
Just leaving this here for posterity (or until someone gets a chance to update the README.md)

FileSaver works great for three.js, but you'll need to set `preserveDrawingBuffer` as an option if you use the `WebGLRenderer`.  See https://stackoverflow.com/a/15563621/4855984

**Comment by makc** [comment]
you probably don't need to do that if you render in save button click handler.

**Comment by alvinwan** [comment]
true but I wanted to automate this

**Comment by makc** [comment]
if this setting is off by default, it probably hinders performance or wastes memory. are you really willing to pay that price to save one line of code?

**Comment by alvinwan** [comment]
actually, I misinterpreted what you said. "save button click handler" doesn't work, as the drawing buffer still isn't populated. The stream will simply be empty if you try that. Perhaps I did it incorrectly, but my initial try was spoofed.

**Comment by makc** [comment]
ha, you are right, it does not work with eligrey/canvas-toBlob.js

however, if you convert to blob by hand, it works: https://jsfiddle.net/f2Lommf5/19/
