### ISSUE TITLE
Save as type is incorrect

### ISSUE THREAD

**Issue by piavgh** [eligrey/FileSaver.js#380]
Hi everyone,

I'm working on a project that uses Electron to wrap a web app to desktop app.

In this project, I use FileSaver.js to export canvas content to png/jpg/pdf.

1. canvas is turned into base64 image
2. base64 image is turned into blob
3. blob file is saved using FileSaver.js .

Here is how it looks like when Save dialog appears:
https://prnt.sc/h5bb99

This is what it should look like as normal save as (png file):
https://prnt.sc/h5b7wo

This matters because if the user forgets to insert .png at the end of file name, the file can not be opened normally.

How can I solve this problem?
Thank you very much.

**Comment by Krakownication** [comment]
+1

**Comment by jimmywarting** [comment]
You know you can just drag and drop image into the textarea when writing a new issue?

**Comment by Ruffio** [comment]
@piavgh has this issue been resolved and can be closed?

**Comment by aorozsa** [comment]
@jimmywarting I have a similar issue, except I'm trying to save a JSON-stringified array to a file. I have no problems in a browser, but in Electron, if the user doesn't add .json to the end, the file is saved as an unspecified type.

**Comment by jimmywarting** [comment]
Electron is out of the scope of what we are trying to support, Electron has it own feature/api to save stuff

https://stackoverflow.com/a/57261448/1008999
