### ISSUE TITLE
FileSaver.js is saving corrupt images

### ISSUE THREAD

**Issue by dushyantbangal** [eligrey/FileSaver.js#381]
This was working fine and suddenly stopped working. I'm not sure what exactly changed.

I need to download multiple images via URLs.

I'm using the following code:  
https://plnkr.co/edit/nsxgwmNYUAVBRaXgDYys?p=preview

    $http({
      method:"GET",
      url:"imageurl"
    }).then(function(response){
    
      saveAs(new Blob([response.data]), "image.jpg");
    
    },function(err){
      
    });

The files have different sizes, they are not 0 bytes.

**Comment by jimmywarting** [comment]
Change response type to blob instead of creating it yourself.

 Sice the image is coming from a server, are there any reasons why you can't handle the download part on the backend with http header content-disposition attachment instead?

**Comment by dushyantbangal** [comment]
I have an API that returns with multiple URLs or just filenames. Then I need the browser to download all of those. I dont know much about `content-disposition` but from what I read around it will just be for a single file.

**Comment by dushyantbangal** [comment]
`responseType: "blob"` did the job.

Initially, I had tried `responseType: "blob"` but it didnt work on the plunkr I mentioned in my issue.

But then I tried it in another one and it worked. When I added
`delete $http.defaults.headers.common['X-Requested-With'];`

from my plunkr, it stopped working. Strange.
