### ISSUE TITLE
Unable to dispatch click on Chrome/Safari

### ISSUE THREAD

**Issue by bcardiff** [eligrey/FileSaver.js#382]
I am getting the following error while calling saveAs

```
Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
```

file-saver@^1.3.3
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Safari Version 11.0.1 (12604.3.5.1.1)
OSX Sierra 10.12.6 (16G1036)

It goes away if I revert https://github.com/eligrey/FileSaver.js/pull/152 partially with

```patch
+++      var event = document.createEvent("MouseEvents");
+++      event.initMouseEvent("click", true, true, window, 0, 0, 0, 80, 20, false, false, false, false, 0, null);
---      var event = new MouseEvent("click");

```

I get that [initMouseEvent is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent) but I found no other workaround.

In stackoverflow [someone points](https://stackoverflow.com/a/42064469/30948) points that maybe there are some properties missing with using `MouseEvent` constructor. But, as [somebody else](https://stackoverflow.com/questions/41920266/dispatchevent-causes-error-failed-to-execute-dispatchevent-on-eventtarget-p#comment76691039_42064469), I couldn't solve the issue with those properties.

**Comment by philiply** [comment]
just ran into this issue. any updates?

**Comment by Ruffio** [comment]
@bcardiff can you provide a JSBin or similar testpage demonstrating the issue?
