### ISSUE TITLE
False antivrius report

### ISSUE THREAD

**Issue by stodorovic** [eligrey/FileSaver.js#384]
I've found that some antiviruses recognize this javascript as "trojan script", but it's already confirmed as false positive. One of report is:

https://www.virustotal.com/#/file/86db91d4ec31f22f619b887863877f16394f2e88f6b5e426849e569cd4a8df0d/detection

This script is included in some WP plugins and it's confusion for some users (and it's trouble with automatic scanners on some web hosting). Also, it's too boring to explain it again and again.

By my quick research, it seems that this line is "source":
```js
return new Blob([String.fromCharCode(0xFEFF), blob], {type: blob.type});
```
Simple replacement of `String.fromCharCode(0xFEFF)` with `"\uFEFF"` resolves this issue. Other code which passes is `String.fromCharCode(0xFEFF) + blob` (but I don't know is it good solution).

I'm not JS expert and I know that's better to use `String.fromCharCode(0xFEFF)`. Please help us.

Regards,
Sasa

**Comment by eligrey** [comment]
It's a workaround for a minifier issue. Fortunately it seems none of the popular antiviruses have this false positive. As for NANO-Antivirus, I would contact them and report the false positve.

**Comment by eligrey** [comment]
@stodorovic You can report NANO-Antivirus false positives at <http://www.nanoav.ru/index.php?option=com_content&id=15&Itemid=53&lang=en>.

**Comment by eligrey** [comment]
@stodorovic The vendor has informed me that this should now be fixed.

![NANO Antivirus response](https://user-images.githubusercontent.com/46995/34317652-26d75794-e768-11e7-91aa-5b867e424e9b.PNG)
