### ISSUE TITLE
After a file download all a links downloads?

### ISSUE THREAD

**Issue by Manmade** [eligrey/FileSaver.js#385]
Im using the filesaver.js to download a file and it works as it should, it downloads the file. But the problem I have is that ones you have downloaded a file then it downloads all a links that has target=_blank.

So I wonder if it is possible to make it only download on links with a specific class instead ?

In the filesaver.js file there is this line, and that somehow makes all a links to download.
```js
save_link = doc.createElementNS("http://www.w3.org/1999/xhtml", "a")
```
Any input appreciated, thanks a lot!

**Comment by jimmywarting** [comment]
filesaver only saves one file.
You are probably calling saveAs meány times?

Can you show us some context on what you are doing?

**Comment by Manmade** [comment]
Thanks Jimmy. I use another framework and it was that, that was the problem, I got it solved. Thanks!
