### ISSUE TITLE
[Help Wanted] to mock 'saveAs' with jasmine when using FileSaver

### ISSUE THREAD

**Issue by ramtech123** [eligrey/FileSaver.js#388]
Hi All,

I'm novice to to javascript, trying to work with Angular4. I was able to use 'file-saver' to download the files via my angular application.

However, I'm not able to write unit test for the method in which I'm calling 'saveAs' function as I couldn't mock/spy it.

I tried below different approaches, but none of these were successful. 

Trial#1

```js
// Arrange
// ...
saveSpy = spyOn(saveAs.prototype, 'constructor');

// Act
// ...

// Assert
expect(saveSpy).toHaveBeenCalled();
```

Result failed with message:
`Expected spy constructor to have been called.`

Trial#2
```js
// Arrange
// ...
spyOn(window, 'saveAs');

// Act
// ...

// Assert
expect(window.saveAs).toHaveBeenCalled();
```
Result failed with message:
`Property 'saveAs' does not exist on type 'Window'.`

Trial#3
```js
// Arrange
// ...
spyOn(saveAs, 'saveAs');

// Act
// ...

// Assert
expect(saveAs.saveAs).toHaveBeenCalled();
```
Result failed with message:
`Error: saveAs() method does not exist.`

I'm not able to understand whether 'saveAs' is an independent function or object constructor. I tried both the approaches as suggested in different stackoverflow and github posts, but didn't succeed.

Could you please help me mock 'saveAs' call and validate the parameters. Thanks.

**Comment by anonyco** [comment]
Please post this question @ stackoverflow, not in an issue tracker.

**Comment by eligrey** [comment]
As @anonyco said, this question belongs on StackOverflow.
