### ISSUE TITLE
does not trigger save_as under chrome on linux and chromebook

### ISSUE THREAD

**Issue by ensonic** [eligrey/FileSaver.js#390]
When trying the [demo](https://eligrey.com/demos/FileSaver.js/), it saves the files right away and not triggering save_as as promissed.

```
Google Chrome | 63.0.3239.90 (Official Build) beta (64-bit)
OS | Linux
JavaScript | V8 6.3.292.46
```

**Comment by stuartpb** [comment]
Can confirm that I'm seeing the same behavior on Chrome for Windows. There appears to have been a change to Chrome's handling of `download` links to only prompt if the user right-clicks and selects "Save link as..." or has "Choose where to put each download" enabled.

**Comment by Ruffio** [comment]
[2018-03-07_12h51_37.zip](https://github.com/eligrey/FileSaver.js/files/1789023/2018-03-07_12h51_37.zip)

The attached video shows that Google Chrome (on Windows) automatically saves the file, when the user clicks the 'Save' button on the Demo site. I guess that this is by (Google) design?

**Comment by sgehrman** [comment]
same problem.  Anyone have a fix?
