### ISSUE TITLE
Detatched DOM Nodes with FileSaver 

### ISSUE THREAD

**Issue by saurav1005** [eligrey/FileSaver.js#393]
We are experiencing a memory leak due to the detatched DOM node that seems to be caused by the File Save API.
Attaching the memory profiling screenshot for the same. Is anyone experiencing the same issue?
File Saver API version - 1.3.3

![file saver](https://user-images.githubusercontent.com/14871430/34507399-a6d3886c-f089-11e7-9128-134758859d40.png)

**Comment by eligrey** [comment]
What do you mean memory leak? It's intentionally instantiation of a single node. I can't imagine that a single node is causing memory problems for you.

**Comment by saurav1005** [comment]
Let me analyze post testing more flows and publish the retained size.

**Comment by Ruffio** [comment]
@saurav1005 anything new?

**Comment by saberjsd** [comment]
Hi, @saurav1005 
So, What is the real cause of the memory leak？
