### ISSUE TITLE
How to change the Name of the excel worksheet?

### ISSUE THREAD

**Issue by neppolia** [eligrey/FileSaver.js#395]
need suggestion to change the default name of the excel worksheet, i've tried assigning the parameter, but displayed as undefined.

**Comment by jimmywarting** [comment]
`saveAs(blob, filename)`

**Comment by neppolia** [comment]
i need to change the worksheet name (<x:Name>Name</x:Name>), any suggestions

**Comment by jimmywarting** [comment]
That is not relevant to filesaver and should be posted elsewhere. like stackoverflow

**Comment by neppolia** [comment]
yeah sure, thank you
