### ISSUE TITLE
[Electron] write to a folder that I don't have the permission

### ISSUE THREAD

**Issue by nhzandi** [eligrey/FileSaver.js#400]
I'm using this library with Electron JS. I know that Electron has it's own way of saving files, but as I may put the app on the web, I want something that works everywhere. 

When I try to save the file, a `Save As...` file dialog opens, that I can choose the destination folder and the name of file. But what happens when I try to save in a directory that I don't have permission, Like in the root directory on a Linux system?! It doesn't return any error and as expected no file is saved.

**Comment by Ruffio** [comment]
@nhzandi What is the issue? It is the different browsers that handles the save dialog with the user. You can't tell the dialog which folder to save the file in. That would be a security issue...

**Comment by nhzandi** [comment]
I don’t have any problem with the browsers, they work as you said. 
I’m using filesaver with electronjs to write a desktop app. So it gives me a `Save As...` dialog that I can choose what destination I want, even directories I don’t have write permission, but of course I can’t write to that folder, but I have no error feedback.

**Comment by Ruffio** [comment]
What happens if you just 'manually' try to save a file to a folder without permission in electronjs? I'm not sure that FileSaver is the right choice for you.

**Comment by nhzandi** [comment]
It has its own way of saving files with opening dialog, that gives error on trying to save to a folder without permission. But obviously it doesn't work on web pages. Maybe I should look for something else.

**Comment by jimmywarting** [comment]
This is pro
