### ISSUE TITLE
PDF blob is not getting downloaded in Iphone

### ISSUE THREAD

**Issue by rnagavel** [eligrey/FileSaver.js#403]
iphone doesn't seem to download pdf blob. 
```js
// Content is pdf in base64 format
const pdfBlob = base64ToBlob(content, 'application/pdf');
FileSaver.saveAs(pdfBlob , name);
```

It works in all the other devices such as android chrome/ windows desktop (Chrome, IE and Firefox). 
No error is seen in the browser log.

Anyone got a clue ?

**Comment by jimmywarting** [comment]
`content` should be a blob, not base64 string

**Comment by Ruffio** [comment]
@rnagavel has this issue been resolved? Can you please close it then.
