### ISSUE TITLE
[1.3.6+] Bower distribution is empty

### ISSUE THREAD

**Issue by boris-petrov** [eligrey/FileSaver.js#409]
When installing version 1.3.6 from Bower, the directory contains only `bower.json` and `LICENSE.md`.

**Comment by DeanHand** [comment]
Seems an obvious thing to say, but rolling back my bower package to 1.3.4 for now did the trick for me

**Comment by HoffsMH** [comment]
Could this be because bower.json contains 
```"version": "1.3.3",```
or because package.json contains
```  "version": "1.3.4",```

?

**Comment by Havunen** [comment]
This also happens when you manually install git 1.3.6 as dependency...

**Comment by boris-petrov** [comment]
@eligrey - that's for the bump! However, version `1.3.7` has the same problem. Thanks for he support!

**Comment by DavidHenri008** [comment]
@eligrey - Same behavior for new version 1.3.8, the src folder is missing.

**Comment by srad** [comment]
This is ridiculous, can someone fork and fix this?

**Comment by DeanHand** [comment]
@lenzenmi did you run a bower cache clean between installs? 1.3.4 is working fine for me still

**Comment by lenzenmi** [comment]
No, I just deleted the output folder between version switches. I'll take another look next week at work.

**Comment by enkil2003** [comment]
Is there any update on this? Im running the same issue FileSaver is not in bower folder

**Comment by MR-H0200** [comment]
File saver `1.3.8` still has issue.
to which version should i have to downgrade
