### ISSUE TITLE
npm does not have 1.3.6

### ISSUE THREAD

**Issue by chrahunt** [eligrey/FileSaver.js#410]
The package on [npm](https://www.npmjs.com/package/file-saver) still has 1.3.3, but 1.3.6 was released 3 days ago.

**Comment by jimmywarting** [comment]
fixed

**Comment by chrahunt** [comment]
It looks like the package.json needs to be updated with the correct version, currently it has 1.3.4. Also your build succeeded without any changes? Per #407 `src/FileSaver.js` has invalid syntax, babel was choking on it for me, but from the generated file up on npm I see:

```js
        exports.default = window.saveAs || function (view) {
```

but I'm not sure where `window` is coming from.
