### ISSUE TITLE
dist/FileSaver listed in package.json in FILES

### ISSUE THREAD

**Issue by ksnyde** [eligrey/FileSaver.js#416]
The `dist` directory is not included in the repo but is the entrypoint to the 1.3.x releases!

**Comment by preekmr** [comment]
dist directory appears only from v1.3.4.

**Comment by aikomastboom** [comment]
bower install broken for versions higher than 1.3.4 ( no FileSaver.js is present in the archive)

**Comment by schoofseggl** [comment]
I can confirm. The bower package is empty. I have used "file-saver": "^1.3.8" in bower.json. 

The result is a directory with only  License.md and bower.json.
