### ISSUE TITLE
Q: How do define the directory for txt file to be saved at?

### ISSUE THREAD

**Issue by HR** [eligrey/FileSaver.js#42]
Normally the .txt file save is saved in the same directory as the FileSaver.js in an webapp (if I'm correct) but how do you define the path for it to be saved(for moz)?

**Comment by odimou** [comment]
Hi, is it possible to open a browser dialog box, where user can select his directory to save? Something like downloadify. Or the best way to make it work with Downloadify. Thanks.

**Comment by ivan-bilan** [comment]
@odimou did you find a solution for that?

**Comment by ThomasXing** [comment]
a good idea
