### ISSUE TITLE
saveAs is not a function

### ISSUE THREAD

**Issue by stephencarr** [eligrey/FileSaver.js#421]
Looks like npm is still pulling 1.3.4 but for some reason `FileSaver.saveAs()` is causing an error describing `saveAs` as not being a function. It appears that FileSaver itself is now a function.

Current example:
```
import FileSaver from 'file-saver';
...
FileSaver.saveAs(new Blob('hello, world', {type: 'text/csv'}), 'Export.csv');
```

console output

```
__WEBPACK_IMPORTED_MODULE_10_file_saver___default.a.saveAs is not a function
```

**Comment by kmcmichael-twist** [comment]
Just hit this myself. I have to go back to v1.3.2 to this to work.

**Comment by preekmr** [comment]
Issue related to #414

**Comment by stephencarr** [comment]
We've been targeting ^1.3.4 for at least the past month and it's been working fine. Scratching my head as to what the actual breaking change was, but yeah bad versioning if it was an intentional change.

**Comment by defdata** [comment]
Wow that was a fun production problem to deal with this morning, can't believe I need to lock down patches...

**Comment by wordythebyrd** [comment]
1.3.7 patch isn't installing any library.  I've hardlocked to 1.3.4 for now.

**Comment by jimmywarting** [comment]
updated npm library, is it okey now?

**Comment by kliu99** [comment]
just upgraded to 1.3.7. works fine

**Comment by pradiptagure** [comment]
@kliu99
Can you give the full package.json file and how you are importing saveas. I am also facing same issue.

**Comment by songhejia** [comment]
I'm facing same issue too......

**Comment by WuglyakBolgoink** [comment]
v1.3.7 doesn't work! downgrade

**Comment by stephencarr** [comment]
Closing and linking to #414 for tracking of the issue.
