### ISSUE TITLE
saveAs doesnt download pdf/excel in iOS devices

### ISSUE THREAD

**Issue by Liahus1996** [eligrey/FileSaver.js#430]
I have been using FileSaver.js to download PDF/Excel attachments. While this approach works in all other devices , I am not able to download the attachment in iOS devices 10+.

```js
const wbout: string = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
saveAs(new Blob([wbout],{type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}), "My List" + '.xlsx');
```

I dont want to open the attachment in a new tab — rather, it should do its normal functionality, i.e. download the file.

**Comment by venneflyZ** [comment]
It can't do that. iOS doesn't have a file system to download something to.

> Due to restrictions in iOS saveAs opens in a new window instead of downloading, if you want this fixed please tell Apple how this bug is affecting you.

**Comment by jportella93** [comment]
Is there any alternative or workaround to this? Maybe another package?

**Comment by jimmywarting** [comment]
No there is no alternativ package if there where we would have fixed it already and the question have brought up many times. 

So there is nothing we can do except to wait for ios to fix it
and since there is nothing to do i will close this
