### ISSUE TITLE
remove BOM?

### ISSUE THREAD

**Issue by Pomax** [eligrey/FileSaver.js#432]
https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js#L69 notes that the auto_bom function "prepend[s] BOM for UTF-8 XML and text/* types (including HTML)", but UTF8-encoded documents don't need a byte ordering mark, since UTF8 does not consist of "ordered bytes" like UTF16/32, but is a byte-aligned bit sequence instead, with the same ordering on all systems.

**Comment by wadjeroudi** [comment]
True, there shouldn't be a BOM for utf-8 documents, but that's not a big deal because you can set the flag to no_autobom when saving.
```js
saveAs(blob, 'file.txt', true);

**Comment by Pomax** [comment]
flags should be reserved for overriding the expected default behaviour, so no BOM should be written unless explicitly told to do so, as per Unicode's recommendation.

**Comment by jdhines** [comment]
Just ran into this where we're designing a replacement system that creates a text file for a downstream process, and now that process is bombing on the file due to it reading it as utf-8-bom instead of utf-8.

**Comment by mvasilkov** [comment]
I second this, adding BOM should be opt-in.

**Comment by jimmywarting** [comment]
> as per Unicode's recommendation

On what ground? source?

**Comment by eligrey** [comment]
It's for browser charset sniffing because no browsers ever implemented support for the charset mime parameter in blobs.

If a blob being saved loads as a new tab instead of a download, it will not display properly unless the charset is sniffed through the BOM.

**Comment by eligrey** [comment]
> As a BOM for UTF-8 is formally both neither required nor recommended, writing one by default is essentially a bug because it contravenes the spec

The problem here is that this isn't a BOM for UTF-8, it's a UTF-8 BOM for ASCII→UTF- 8 coalescation.

Try the following code:

    location.href = URL.createObjectURL(new Blob(["①"], {type:"text/plain;charset=UTF-8"}));

The auto-BOM code is a workaround for a spec bug.

**Comment by Pomax** [comment]
As far as I'm aware, they are treated as "whatever the owning document specified as charset", so if you're running JS in the context of a document that was created off of a `<meta charset="utf-8">` then that's what your blob should be, too.

If there is _no_ charset defined, then yes letting people specify the BOM might make sense.

**Comment by eligrey** [comment]
I should probably change the behavior to only apply this mitigation on Windows user agents, and provide a global config option to disable the behavior unless opted-in.

**Comment by Pomax** [comment]
That feels way more like a "this works in some browsers but not others, don't write one by default, but let people know in the README.md that they need to check this" or even have the library change the default behaviour based on attempting to create a UTF8 blob and seeing what happens with that content by immediately loading it back in?

**Comment by jimmywarting** [comment]
If we automatically add BOM then we are changing the content of the source they are trying to save. a hash sum of the file wouldn't be the same as what you are downloading.

isn't the BOM only necessary when viewing it in a new tab?

**Comment by eligrey** [comment]
@jimmywarting Correct. Also thanks for the latest PR!

**Comment by jimmywarting** [comment]
I begun to thing that the noAutoBom should be reversed too.
kinda feel like it dose some unexpected things.

ppl might wonder "whata heck is BOM?" ignore it and just use the first two arguments.
a change like this should be a major version update
