### ISSUE TITLE
Chrome doesn't save all files if saveAs is invoked several times sequentially

### ISSUE THREAD

**Issue by dlxeon** [eligrey/FileSaver.js#435]
When saving multiple files using sequential saveAs invocations, Chrome 65 saves just 1 file. At the same time it works fine in Firefox and Edge. Code below reproduces issue:
```
saveAs(new Blob(["Hello 0"], {type: "text/plain"}), "hello0.txt");
saveAs(new Blob(["Hello 1"], {type: "text/plain"}), "hello1.txt");
saveAs(new Blob(["Hello 2"], {type: "text/plain"}), "hello2.txt");
```

If I update code to use zero setTimeout, it works most of time in Chrome, but sometimes it may skip files (especially if I quickly reload test page with F5).
```
saveAs(new Blob(["Hello 0"], {type: "text/plain"}), "hello0.txt");
setTimeout(() => {
	saveAs(new Blob(["Hello 1"], {type: "text/plain"}), "hello1.txt");
	setTimeout(() => {
		saveAs(new Blob(["Hello 2"], {type: "text/plain"}), "hello2.txt");
	});
});
```
Adding timeout value like 50ms solves problem completely. Both versions I checked (1.3.8 and 1.3.3) are providing such result with Chrome 65.

As a workaround, I am thinking maybe it is possible to have a callback from internal FileSaver.js "setTimeout" usage, that will be called when file is actually saved, so at least callers can chain saveAs calls more reliably.

**Comment by ghostCoder** [comment]
facing the same issue

**Comment by colmben** [comment]
Note this appears to be back in Chrome 68.

**Comment by vblagomir** [comment]
The same happens in Safari 12.0.2

**Comment by jimmywarting** [comment]
I remember that if you download a zip file it will automatically unzip it and throw the zip into the trash.
so one idea is to use something like jszip pack everything and only save that

**Comment by mrinalini-m** [comment]
A quick and dirty fix that worked for me is to add a setTimeout to each file being downloaded. 
`
const downloadAll = (arr) => {
  for (let i = 0; i < arr.length; i++) {
    setTimeout(() => {
      const name = `${i}.ext`
      saveAs(arr[i], name)
    }, i * 200)
  }
}
`
