### ISSUE TITLE
View Undefined in Chrome 65

### ISSUE THREAD

**Issue by pmkroeker** [eligrey/FileSaver.js#440]
I have been working on a library that uses FileSaver to download svg images. Everything was working fine until I updated my code base to using rollup. The rollup file now does not want to save the blobs I pass to FileSaver because the view in the function returns undefined. It there a way around this? What exactly is view in this context?

UPDATE:
If I copy paste the non-rollup-ed code into the location in the rollup file it works correctly

**Comment by pmkroeker** [comment]
I have tried the same procedure but using webpack instead of rollup and its working correctly.

**Comment by Ruffio** [comment]
This issue should be closed as it is a duplicate of https://github.com/eligrey/FileSaver.js/issues/438

**Comment by pmkroeker** [comment]
After reading that issue, I don't quite see how they are similar. I will close this issue though as its likely more of an issue with rollup than FileSaver
