### ISSUE TITLE
Blobs being saved to file with incorrect MimeTypes

### ISSUE THREAD

**Issue by datermine** [eligrey/FileSaver.js#442]
Hello! Thanks for the great lib! 

I have this line in my code:

`saveAs(new Blob([ExcelUtil.s2ab(wbout)], {type: "text/csv"}), filename);`

...which downloads a CSV file. Alas, it appears the mime is not correct:

```
$  file --mime-type table.csv
table.csv: text/plain
```

Am I doing something wrong? Is this expected?

Thanks,
George

**Comment by qaxi** [comment]
Hello,
the mime is not "saved" somewhere in the **table.csv** file. Unix utility application **file** is estimating file type (thus MIME type) form content of the file.
File format CSV is very hard to detect, so you can easily get safest close fallback and it is **text/plain** .

Better utility for MIME type detection is **mimetype** command. It makes more tests an can detect MIME better.

**See the difference**
`$ for f in file-*.csv
do
    echo -------------------------
    echo -- file $f content 
    echo -------------------------
    cat $f
    echo -------------------------
    echo RUNING file --mime $f
    file --mime $f
    echo -------------------------
    echo RUNING mimetype $f
    mimetype $f
done

## OUTPUT ##
-------------------------
-- file file-commas.csv content
val11,val12,val13
val21,val22,val23
val31,val32,val33
val41,val42,val43
-------------------------
RUNING file --mime file-commas.csv
file-commas.csv: text/plain; charset=us-ascii
-------------------------
RUNING mimetype file-commas.csv
file-commas.csv: text/csv
-------------------------
-- file file-semicolon.csv content
val11,val12,val13
val21,val22,val23
val31,val32,val33
val41,val42,val43
-------------------------
RUNING file --mime file-semicolon.csv
file-semicolon.csv: text/plain; charset=us-ascii
-------------------------
RUNING mimetype file-semicolon.csv
file-semicolon.csv: text/csv
`

Please look at RFC for more info https://tools.ietf.org/html/rfc7111#page-8 and https://tools.ietf.org/html/rfc7111#page-9 .

If you are sure, you are sending CSV file, it is ok to set **text/csv** on sending file.

**Comment by jimmywarting** [comment]
closing as it's not relevent to filesaver
as @qaxi has described
