### ISSUE TITLE
How to use it with Chrome Extension

### ISSUE THREAD

**Issue by Sourabh25** [eligrey/FileSaver.js#447]
Hi,

I am trying to install the FileSaver.js on my chrome extension. I am not able to do that. Could you please direct me to the list of steps need to install.
Just to let you know, I am also new to use npm.  

Thanks

**Comment by Ruffio** [comment]
The README (https://github.com/eligrey/FileSaver.js) shows different approaches how to use FileSaver. Please take a look there.

This issue should be closed.

**Comment by Ruffio** [comment]
Due to lack of response from originator in two months, this issue should be closed
