### ISSUE TITLE
Lib throws error when imported inside a service worker

### ISSUE THREAD

**Issue by rodgobbi** [eligrey/FileSaver.js#449]
Currently on the project that I'm working on, there's a build process for the service worker used in the application, and one of the files used by the service worker is importing the lib, although the lib is not used inside the service worker, it throws an error when executing the service worker script, which is:  

`TypeError: Cannot read property 'createElementNS' of undefined`

**Comment by rodgobbi** [comment]
Analyzing the code I can guess that the expression `typeof self !== "undefined" && self` is returning `true` and the self reference to the service worker, but the service worker context is different from the window.  
I can help with any implementation and testing if it's desired for the lib to work on this use case.

**Comment by jimmywarting** [comment]
Filesaver don't work in service workers. Why do include it there?

**Comment by rodgobbi** [comment]
It's mainly because it breaks the SW registration if a file used by the SW imports the lib, even if it's not being used inside the SW.
I understand, no explicit need to mind this issue, but anyone using the lib in a project which has a SW at the same project needs to be aware of this caveat.

**Comment by stsiarzhanau** [comment]
Hi! Currently our team is working on a big react-redux based project. We have the same error and it totally breaks our worker based calculations. Note, that we don't import 'file-saver' directly into worker script, it happens through the chain of other imports (about 15).  I'd appreciate any help in solving this issue. Thanks in advance.
