### ISSUE TITLE
Npm package contains old version of FileSaver.js

### ISSUE THREAD

**Issue by rdkleine** [eligrey/FileSaver.js#452]
The header of FileSaver.js in node_modules package:
`/* FileSaver.js
 * A saveAs() FileSaver implementation.
 * 1.3.2
 * 2016-06-16 18:25:19
 *
 * By Eli Grey, http://eligrey.com
 * License: MIT
 *   See https://github.com/eligrey/FileSaver.js/blob/master/LICENSE.md
 */`

Also file datestamp says: 10/5/2016 12:43

**Comment by pauln** [comment]
I can confirm that both v1.3.3 and v1.3.8 on npm actually contain v1.3.2, as described in this ticket.  @eligrey, is there any chance you can please push a new version to npm which contains an up-to-date copy of the code?
