### ISSUE TITLE
IE11 and Edge issue

### ISSUE THREAD

**Issue by 1mayur** [eligrey/FileSaver.js#455]
you have mentioned new File as an example for implementation however new File doesn't work with IE. Doesn't throw any error but doesn't save file either

**Comment by jimmywarting** [comment]
Still not Edge? seriously. Should maybe comment that in the code example or remove that code example all together. it's safer just to do saveAs(blob, filename)

**Comment by 1mayur** [comment]
We can just add a caution saying will not work on IE
