### ISSUE TITLE
I always get the Error: Object Expected

### ISSUE THREAD

**Issue by LucaKay** [eligrey/FileSaver.js#456]
Hey Guys

Im working with IE 11, and i really need to implement this filesaving function! its would be exactly the thing i need.. but now im already trying so many things, but i cant get it working.

it always tells me: "Object Expected", my code to implement and to call the function looks like this.. its just to test first, but no chance to get it working.
```html
<script language="javascript" src="http://xxx.zzz.net/mr/scripts/blob.js"></script>
<script>
  var blob = new Blob(["Hello, world!"], {type: "text/plain;charset=utf-8"});
  saveAs(blob, "hello world.txt");
</script>
```

can anybody help me? would really appreciate it!!

best regards
luca

**Comment by jimmywarting** [comment]
What da heck is mr/scripts/blob.js?

**Comment by Ruffio** [comment]
@LucaKay is Blob.js some kind of polyfill? I think that if you want some help/guidance then you have to show us the complete code. Try without the Blob.js
