### ISSUE TITLE
FileSave Return File Wrong Content File

### ISSUE THREAD

**Issue by vietdq1291** [eligrey/FileSaver.js#457]
I am trying to use fileSaver.js with angular 6, It return me File with content "[object Object]" is not content in that file
here is my Code

API code : 
![image](https://user-images.githubusercontent.com/38650722/44390083-a93e4100-a556-11e8-8130-f8ed1f66bfd6.png)

Component code:
![image](https://user-images.githubusercontent.com/38650722/44390148-cd018700-a556-11e8-91ff-fe79fd382ba6.png)

Service code:

![image](https://user-images.githubusercontent.com/38650722/44390213-f3272700-a556-11e8-9f68-a1709856f81f.png)

Help me Please!

**Comment by jimmywarting** [comment]
paste your code inside 3 backticket ` instead of pasting screen dumps

![skarmavbild 2018-09-21 kl 01 46 22](https://user-images.githubusercontent.com/1148376/45852443-2fa99680-bd40-11e8-84f5-d85cd0b6d323.png)

**Comment by Ruffio** [comment]
I would be a good idea to paste in your solution and then close this ticket. Thanks :-)

**Comment by vietdq1291** [comment]
Here is my solution 

  [HttpGet]
        [Route("DownloadFile")]
        public FileContentResult Download(string Path, string Name)
        {
            string strFileUrl = _hostingEnvironment.WebRootPath + Path;
            byte[] bytes = System.IO.File.ReadAllBytes(strFileUrl);
            return File(bytes,FileContentType.GetContentType(strFileUrl), Name);
        }

change my code backend
