### ISSUE TITLE
how to rename download file by open savaAs popup ??

### ISSUE THREAD

**Issue by acharotariya** [eligrey/FileSaver.js#458]
i'm using chrome version 61.0.3163.79 and download zip file content by FileSaver but chrome not open popup window to saveAs file..it's directly download.

```js
zip.file('shipping.csv', csvShipping)
zip.file('imprint_charges.csv', csvImprint)
zip.file('pricing.csv', csvPricing)
zip.file('images.csv', csvImage)
zip.file('productInfo.csv', csvProduct)
zip.generateAsync({ type: 'blob' }).then(function (content) {
  // see FileSaver.js
  FileSaver.saveAs(content, 'product-data.zip')
})
```

**Comment by pmkroeker** [comment]
This is a feature of the browser itself. [Article](https://forum.vivaldi.net/topic/14366/download-behavior). By default browsers cannot open the `save as` dialog. Chrome does have a Option in Settings that will cause the dialog to appear. You aren't able to force it open from the web.
