### ISSUE TITLE
Stream data to a file?

### ISSUE THREAD

**Issue by splutz** [eligrey/FileSaver.js#461]
Is it possible to stream bytes to a file client-side? Please see my pseudo code below, thanks

```
startDownload("file.txt") // browser download begins
// some time in the future ... 
appendBytes("file.txt", bytes) // browser renders some progress on download progress bar
// some time in the future
endDownload("file.txt") // browser renders the download as completed and clickable
```

**Comment by jimmywarting** [comment]
It's possible using [StreamSaver](https://github.com/jimmywarting/StreamSaver.js)

**Comment by jimmywarting** [comment]
Yes, but might work in edge now. Think they have service worker and readablestream

**Comment by jimmywarting** [comment]
Works in Opera too

**Comment by splutz** [comment]
@jimmywarting any plans to support firefox/safari in the near future?

**Comment by jimmywarting** [comment]
Nothing I can do to fix it. Just have to wait till they implement the missing things

**Comment by splutz** [comment]
@jimmywarting Thanks... Any idea how long that will take?

**Comment by jimmywarting** [comment]
it was silent from firefox for a while but I have gotten a few couple of mail from bugzilla that i'm subscribed on. that it's on the track

anyhow have a look at this: https://github.com/jimmywarting/StreamSaver.js/issues/57#issuecomment-409988053
