### ISSUE TITLE
[2.0.0-rc.1] Where is the changelog?

### ISSUE THREAD

**Issue by navarroaxel** [eligrey/FileSaver.js#466]
Hi!

Where could I can find the changelog for the v2.0.0-rc.1? There is no release on the github repo page.

**Comment by jimmywarting** [comment]
Good idea will probably add a changelog.md

**Comment by navarroaxel** [comment]
I think `CHANGELOG.md` standard name should be on upper case like node or npm uses.

**Comment by jimmywarting** [comment]
fixed
