### ISSUE TITLE
Compile with warnings

### ISSUE THREAD

**Issue by Aw3same** [eligrey/FileSaver.js#470]
I update to `2.0.0-rc.2`  and when I compile my angular project I receive this in console:

> WARNING in ./src/app/pages/sidenav/components/info-alteracion/components/list-documents/list-documents.component.ts 80:16-22 "export 'saveAs' was not found in 'file-saver'

My code 

```typescript
import { saveAs } from 'file-saver';
/*...*/
    this._http.getDocumento(this.id, id_doc, id_del).subscribe(
      (result: Blob) => {
        if ((result.type == 'application/pdf') || (result.type == 'text/html')) {
          let fileURL = window.URL.createObjectURL(result);
          window.open(fileURL);
        } else {
          saveAs(result, id_doc + '.zip');
        }
      },
      err => throwError(err)
    );
```

Any idea of how to fix it? Thanks in advance

**Comment by jimmywarting** [comment]
that pice of code is irrelevant. 
The code that is interesting is how you import the saveAs function in the top of your file

**Comment by jimmywarting** [comment]
btw, v2 supports saving url's now

saveAs('/asset/doc.pdf', 'doc.pdf')

**Comment by Aw3same** [comment]
I update the piece of code. Btw, I import using this : 

`import { saveAs } from 'file-saver';`

**Comment by jimmywarting** [comment]
You can remove the object destruction

**Comment by Aw3same** [comment]
I don't understand your response

**Comment by jimmywarting** [comment]
[mdn Object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring)

> You can remove the object destruction

means you should destruct the object and just do

```js
import saveAs from 'file-saver';
```

**Comment by Aw3same** [comment]
Thanks, issue solved!
