### ISSUE TITLE
2.0.0-rc.3 published as latest release to NPM?

### ISSUE THREAD

**Issue by jrr** [eligrey/FileSaver.js#472]
I noticed an update available to file-saver:
```
Package        Current Wanted Latest     Package Type URL
file-saver     1.3.8   1.3.8  2.0.0-rc.3 dependencies https://github.com/eligrey/FileSaver.js#readme
```
Did you mean to tag it latest?

**Comment by jimmywarting** [comment]
still experimenting with v2 so not quite ready yet

**Comment by bastienmoulia** [comment]
Can you tag it as `rc` ?

**Comment by jimmywarting** [comment]
do you mean as a release here: https://github.com/eligrey/FileSaver.js/tags?

**Comment by jrr** [comment]
I think it's the `tag` from the _npm publish_ step: https://docs.npmjs.com/cli/publish

**Comment by groothuyse** [comment]
It looks like you may have tagged 1.3.8 with the 1.3.3 file and hash? Pulling in version 1.3.8 now gives version 1.3.3 with a different hash.

**Comment by bastienmoulia** [comment]
Yes, https://docs.npmjs.com/getting-started/using-tags

**Comment by m4m4m4** [comment]
@jimmywarting we cannot download 1.3.8 since it has a wrong hash, if v.2 is still rc can you please fix the package in npm?

**Comment by Ruffio** [comment]
Since we are no longer in RC, this issue should be closed
