### ISSUE TITLE
Argument of type string is not assignable to parameter of type "Blob"

### ISSUE THREAD

**Issue by seasky1** [eligrey/FileSaver.js#473]
Calling the following code would return an error, "Argument of type string is not assignable to parameter of type "Blob"

FileSaver.saveAs("http://mywebsite.com/api/GetFileStream/59267", 'myfile.csv', { autoBOM: true });

I believe the latest version supports blob/url(string)/file if I am not mistaken.

thanks.

**Comment by jimmywarting** [comment]
Yeah, guess you are using some type definition repo that is not updated?

**Comment by seasky1** [comment]
You are correct.  Thanks.  I had to make the following adjustment in order to work.  I believe first call was to @types.  I am not sure why @types did not update the repo to latest.

//import { FileSaver } from 'file-saver';
import * as FileSaver from '../../../node_modules/file-saver';

**Comment by jimmywarting** [comment]
the url string is fairly new

**Comment by jimmywarting** [comment]
@seasky1 would you like to create a PR with a `d.ts` file?

**Comment by Ruffio** [comment]
Is there an issue here or was it a matter of implementation? It looks like it was resolved.

**Comment by Ruffio** [comment]
@seasky1 what is the status one this issue? Can it be closed?
