### ISSUE TITLE
module.exports throws error in src/FileSaver.js

### ISSUE THREAD

**Issue by 28raining** [eligrey/FileSaver.js#475]
I'm not a expert here, but this line inside src/FileSaver.js causes an error when the file is imported into Chrome.

module.exports = _global.saveAs = saveAs.saveAs = saveAs

Looking at Git blame, looks like this line is new. I can comment the line out and then the code works for me.

**Comment by jimmywarting** [comment]
do you use `import` or require?

**Comment by av01d** [comment]
Neither... I simply downloaded FileSaver.js from the dist folder, and included it like so:
`<script src="js/FileSaver.js"></script>`
Old school!

**Comment by alexisszabo** [comment]
Similarly, I am using "import saveAs from 'file-saver'", and I get the error:

ReferenceError: Can't find variable: module

Thrown on this line:

module.exports = _global.saveAs = saveAs.saveAs = saveAs;

I am testing in Safari 12.0 on Mac OS.

**Comment by cahyowhy** [comment]
same here....

**Comment by shmert** [comment]
I changed `module.exports = _global.saveAs = saveAs.saveAs = saveAs`
to
`window.saveAs = _global.saveAs = saveAs.saveAs = saveAs;`

**Comment by pmcelhaney** [comment]
This will probably fix it. 

```js 

_global.saveAs = saveAs.saveAs = saveAs;

if (type module !== 'undefined') {
   module.exports = saveAs;
}
```

**Comment by Ruffio** [comment]
@eligrey any comments on this one? Could it be the way to do it?

**Comment by jimmywarting** [comment]
rc4
