### ISSUE TITLE
won't trigger when pass to onClick in react

### ISSUE THREAD

**Issue by marklai1998** [eligrey/FileSaver.js#485]
I have the following function
```js
  download = () => {
    console.log('hi')
    var blob = new Blob(['Hello, world!'], { type: 'text/plain;charset=utf-8' })
    console.log(blob)
    FileSaver.saveAs(blob, 'hello world.txt')
  }
```

which passed to a button onClick function
The "hi" did trigger and the blob is correct
but the browser did nothing afterwards

I tried to put it at render(), which means it will trigger on load
and it did work, download a .txt

so the main problem is with the onClick??

**Comment by marklai1998** [comment]
so strange, I implemented it at code sandbox and it works
not sure if its a webpack problem

here is my package.json

`{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@babel/runtime": "^7.0.0",
    "classnames": "^2.2.6",
    "file-saver": "^2.0.0-rc.4",
    "immutable": "^4.0.0-rc.10",
    "ramda": "^0.25.0",
    "react": "^16.6.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dom": "^16.6.0",
    "react-helmet": "^5.2.0",
    "react-json-view": "^1.19.1",
    "react-redux": "^5.0.7",
    "react-redux-form": "^1.16.10",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@commitlint/cli": "^7.2.1",
    "@commitlint/config-conventional": "^7.1.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.0.0",
    "babel-jest": "^23.4.2",
    "babel-loader": "^8.0.1",
    "babel-plugin-ramda": "^1.6.3",
    "babel-plugin-react-css-modules": "^3.4.2",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "css-loader": "^1.0.0",
    "eslint": "^5.5.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-config-standard-jsx": "^6.0.2",
    "eslint-plugin-flowtype": "^3.0.0",
    "eslint-plugin-fp": "^2.3.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jest": "^21.26.1",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-ramda": "^2.5.1",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-standard": "^4.0.0",
    "file-loader": "^2.0.0",
    "flow-bin": "^0.84.0",
    "flow-typed": "^2.5.1",
    "html-webpack-plugin": "^3.0.0",
    "husky": "^1.1.2",
    "import-sort-cli": "^5.2.0",
    "import-sort-parser-babylon": "^5.2.0",
    "import-sort-style-module": "^5.0.0",
    "jest": "^23.5.0",
    "jest-each": "^23.5.0",
    "lint-staged": "^7.2.2",
    "prettier-eslint-cli": "^4.7.1",
    "style-loader": "^0.23.0",
    "stylelint": "^9.5.0",
    "stylelint-config-css-modules": "^1.3.0",
    "stylelint-config-standard": "^18.2.0",
    "webpack": "^4.23.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },
  "scripts": {
    "start": "webpack-dev-server",
    "build": "webpack --config webpack.config.js",
    "test": "jest",
    "flow": "flow",
    "lint:css": "stylelint 'src/**/*.css'",
    "lint:flow": "flow check"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/marklai1998/IVE-IA-Doc-Generator.git"
  },
  "author": "MarkLai",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/marklai1998/IVE-IA-Doc-Generator/issues"
  },
  "homepage": "https://github.com/marklai1998/IVE-Doc-IA-Generator#readme",
  "jest": {
    "verbose": true,
    "testURL": "http://localhost/",
    "moduleNameMapper": {
      "\\.(css)$": "<rootDir>/__mocks__/styleMock.js"
    }
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "lint-staged"
    }
  }
}
`

**Comment by marklai1998** [comment]
tried npm build
it works after build, so may be is the webpack-dev-server problem??

**Comment by Ruffio** [comment]
So this issue can be closed?
