### ISSUE TITLE
'dist' folder is missing in releases!

### ISSUE THREAD

**Issue by badass-icon** [eligrey/FileSaver.js#488]
Your package.config and bower.json files having references to missing 'dist' folder
```
  "main": "dist/FileSaver.js",
  "module": "src/FileSaver.js",
  "files": [
    "dist/FileSaver.js",
    "dist/FileSaver.min.js",
    "src/FileSaver.js"
  ],
```

**Comment by Ruffio** [comment]
Is this still an issue?

**Comment by eligrey** [comment]
@badass-icon is this still an issue for you?

**Comment by Ruffio** [comment]
This issue should be closed due to lack of response from originator
