### ISSUE TITLE
When data is string like url and filename is empty, get name from data if possible

### ISSUE THREAD

**Issue by KrakenTyio** [eligrey/FileSaver.js#490]
#351 In new version is allowed CORS?

If is allowed, should be possible get name from string data representation of url.

**Comment by jimmywarting** [comment]
Better would be to check if it has `content-disposition` attachment response header - if it dose, abort the request and just open the url and it will download it with the name in the header

if it dosen't then we could pull it of from the representation of the url

**Comment by hkaur12344** [comment]
I am trying to download media from S3 bucket and filesaver works fine in firefox ,but giving CORS error while downloading media in chrome browser.I am using file saver in angular 5. Is anyone getting this same issue??Your help will be much appreciated.

**Comment by Ruffio** [comment]
@KrakenTyio, can this issue be closed?

**Comment by Ruffio** [comment]
@KrakenTyio, can this issue be closed?

**Comment by p-himik** [comment]
If I'm using FileSaver to download a file from the same domain, this feature request is still valid given its title, isn't it?
