### ISSUE TITLE
Using require.js and FileSaver library in chrome extensions

### ISSUE THREAD

**Issue by var-che** [eligrey/FileSaver.js#493]
I am implementing a button from a content script that should save some text. I found FileSaver.js library that does just that, and in order to use it, I should have require.js to make an instance of it. Like this:

```js
require(['file-saver'], function (FileSaver) {
  console.log(FileSaver)
});
```

Simple enough. On their website, that works, but on my extension, I get this error in red letters:

`Uncaught Error: Script error for "file-saver"`

The code above was run from a content_script.js and here is how my manifest.json content_script object looks like:

```js
...
"content_scripts": [
    {
      "matches": ["https://www.youtube.com/*"],
      "css" : ["lib/jquery-ui.css", "lib/main.css"],
      "js": ["lib/jquery.min.js", "lib/jquery-ui.min.js", "lib/FileSaver.min.js", "lib/require.js",  "content_script/content_script.js"],
      "run_at": "document_end"
    }
  ],
...
```

As you can see, I have included both require and filesaver in the list.

What am I missing?

What I ended up doing is injecting the _FileSaver.min.js_ in the website, like this:

```js
var s = document.createElement('script');

s.id = "Yolo"
s.src = chrome.extension.getURL('lib/FileSaver.min.js');
s.onload = function() {

};
(document.head || document.documentElement).appendChild(s);


require(['file-saver'], function(FileSaver) {
  console.log('ey')
})
```

and this is what is presented in the console: 
![download](https://user-images.githubusercontent.com/1148376/51090070-a991df80-1776-11e9-9082-2bd19d1c3679.png)

**Comment by Ruffio** [comment]
In the picture it looks like you are trying to load 'https://www.youtube.com/file-saver.js' Is that the correct url?

**Comment by Ruffio** [comment]
@var-che what do you say?

> In the picture it looks like you are trying to load 'https://www.youtube.com/file-saver.js' Is that the correct url?

**Comment by Ruffio** [comment]
This issue should be closed due to lack of response (19 days) from originator...
