### ISSUE TITLE
don't work in ios 

### ISSUE THREAD

**Issue by saberfathallah** [eligrey/FileSaver.js#494]
Expected behaviour:
when click to button download  open pdf downloaded in another tab.
work in all browsers expected ios safari when request take more then 4 seconds the pdf downloaded is open in the current tab.
Demo
https://codesandbox.io/s/zwox4knzpp

**Comment by linwrezare** [comment]
Having the same issue here as well

**Comment by Ruffio** [comment]
As stated in the README, then iOS has an issue regarding this:
![image](https://user-images.githubusercontent.com/1877612/52118665-3f52b900-2617-11e9-87ca-56ca86332fb7.png)


I don't see it that it can be changed/fixed by FileSaver. This issue should be closed IMHO.

**Comment by jimmywarting** [comment]
^ What @Ruffio said!

also it might be helpful now that fileSaver (v2) can accept a link to download file directly without ajax

it will just set the url in the download attribute and click that directly.

you could perhaps just do this yourself

```html
<a href="url" download="filename.txt">download</a>
```

Still doe it dose not support sending headers, body or other Methods...
if you like to save something on user interaction but you don't have all data yet you might want to try streamsaver instead that can begin saving a file to the disc immediately.

Or you have to do something that
1) user clicks download - you show a download progress bar
2) download finish - user click save


I still like to argue that when you save something that comes from the server it's better to use server techniques to save the file rather then using filesaver that was built for saving files that are also generated on the client side

read this: https://github.com/eligrey/FileSaver.js/wiki/Saving-a-remote-file#using-http-header
