### ISSUE TITLE
File saver showing CORS issue in chrome

### ISSUE THREAD

**Issue by hkaur12344** [eligrey/FileSaver.js#495]
I am trying to download media from S3 bucket and filesaver works fine in firefox ,but giving CORS error while downloading media in chrome browser.I am using file saver in angular 5. Is anyone getting this same issue??Your help will be much appreciated.

**Comment by matiasmelendi** [comment]
Did you try giving your site permission to access your bucket's files?https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

**Comment by hkaur12344** [comment]
@matiasmelendi If i will enable CORS for my s3 bucket,will this help?

**Comment by jimmywarting** [comment]
Yes

**Comment by matiasmelendi** [comment]
It worked for me @hkaur12344 !

**Comment by hkaur12344** [comment]
@jimmywarting @matiasmelendi  i have configured the CORS setting in aws and it worked for audio and videos :) but not for images .Any suggestions??

**Comment by hkaur12344** [comment]
@jimmywarting  @matiasmelendi  i have enabled CORS configiuration for s3 bucket .Do i also need to configure cloudfront for the CORS,as my images are not downloading in chrome browser.

**Comment by matiasmelendi** [comment]
@hkaur12344 Hmm, could you post the exact error?

**Comment by hkaur12344** [comment]
@matiasmelendi  Access to XMLHttpRequest at 'AWS_S3_URL/14761544000704.jpg' from origin 'MY_WEBSITE_URL' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Yesterday it was working for images and today it is again giving above error.For vidoes and audio it is working fine. I saw that when the request is hit for video/Audio 'Access-Control-Allow-Origin' header is there but when downloading images no header was found and hence giving errors.

**Comment by matiasmelendi** [comment]
@hkaur12344 given that video &audio are working but not images, I'm wondering if these assets are in the same bucket. Also, Did you allow any origin to access your bucket on the s3 config?

**Comment by jimmywarting** [comment]
closing as this has nothing to do with filesaver

**Comment by Sulavr96** [comment]
I am facing the same issue. I have configured CORS in aws. The image is downloaded in browsers other than chrome. Chrome shows CORS error but the image is only downloaded when I open the chrome browser console.

**Comment by tsulatsitamim** [comment]
having same issue

but if I make request first with axios, it works

`
const link = 'some link';

const instance = Axios.create({
  transformRequest: [
    (data, headers) => {
      delete headers.common.Authorization
        return data
       },
  ],
});

await instance.get(link);

saveAs(link, 'test.docx');
`


if i remove `await instance.get(link)` part it show cors error

**Comment by ahmedeldeeb25** [comment]
@hkaur12344 I have the same issue, did you find a solution?

**Comment by ajayatgit** [comment]
Hi All, 

We were also facing similar issue, but at the end it was boiled down to incorrect creation of pre-signed URL of S3 bucket. 
I think many of us here would be doing similar thing. 

The S3 pre-signed url gets created for a particular type of request which can be be for GET, PUT, POST or HEAD.
In case you have created pre-signed URL for a GET request, you may face issue in case **corsEnabled(url)** function is getting triggered - https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js#L47, as this expect pre-signed URL for HEAD.

Adding you guys @ahmedeldeeb25  @hkaur12344 in case you were getting issue due to similar reason.

**Comment by madhava-varma1612** [comment]
Any Solution to avoid presigned issues

**Comment by OtacilioN** [comment]
Folks, the workaround that I found to this situation was:

- Create a lambda function that converts s3 image to base64
- Request this function at the client, convert base64 to blob than download

**Comment by yqkqknct** [comment]
For those who trying to make presigned url showing the desired filename, you can use content-disposition header.

For example (AWS S3),

```
new GetObjectCommand({
    Bucket: fileBucket,
    Key: key,
    ResponseContentDisposition: `attachment; filename="${filename}"`,
  });
```
