### ISSUE TITLE
global saveAs function is not kept properly when filesaver js is loaded twice

### ISSUE THREAD

**Issue by segovia** [eligrey/FileSaver.js#498]
In FileSaver.js, it seems that the line that starts with: `var saveAs = _global.saveAs ||` has the intention to keep the current saveAs function if it is already defined. Unfortunately that is not the case because after the || there is a ternary function which is missing partheses.

**Comment by nealfwilliams2** [comment]
@jimmywarting @segovia Sorry to bother, but is there an estimate for when this fix will be released?  Thanks!
