### ISSUE TITLE
Causes cypress tests to fail when running in cypress/base:8

### ISSUE THREAD

**Issue by lwakefield** [eligrey/FileSaver.js#501]
I suspect that this is related to https://github.com/eligrey/FileSaver.js/issues/406

Calling `saveFile` in a test being run by cypress on CircleCI seems to cause the job to hang indefinitely.

This was identified in a `cypress/base:8` docker image, but was also replicated with the `cypress/browsers:chrome*` images.

**Comment by jimmywarting** [comment]
I believe we won't do any duck typing for cypress that only developers use.
how would one go about testing any interaction outside the webview like request permission, native alert & promps dialogs as well as a file/folder picker?

can't you replace filesaver.js with a noop function or don't test that at all?

**Comment by lwakefield** [comment]
Yeah that makes sense. I suspect that sooner or later, someone else will encounter this issue so wanted to make sure there was a record of it somewhere.

I think this is probably better dealt with on Cypress' end - so I'll file an issue over there - otherwise I am happy to close this issue.
