### ISSUE TITLE
Unicode hyphen character encoding broken/changed in 2.0.0

### ISSUE THREAD

**Issue by ashlincascade** [eligrey/FileSaver.js#504]
Something to do with Unicode character encoding seems to have changed from v 1.3.8 to v2.0.0.

Running this snippet against `file-saver@1.3.8` produces a CSV file that, when opened in MS Excel, displays both Unicode hyphens correctly. `file-saver@2.0.0` produces a CSV file that, when opened in MS Excel, displays the second Unicode hyphen as `‚Äê`.

The first hyphen character is `-`, or Unicode HYPHEN-MINUS, decimal character code 45. https://www.fileformat.info/info/unicode/char/2d/index.htm

The second hyphen character is `‐`, or Unicode HYPHEN, decimal character code 8208.
https://www.fileformat.info/info/unicode/char/2010/index.htm

```js
var FileSaver = require('file-saver');
var hyphenCsv = new Blob([`"hypen","-","‐"`], {type: "text/csv;charset=utf-8"});
FileSaver.saveAs(hyphenCsv, "hyphen-test.csv");
```

Is there something we need to do differently to get this working on 2.0.0, or is it a bug in the implementation?

**Comment by jimmywarting** [comment]
Might be that we removed the auto BOM https://github.com/eligrey/FileSaver.js/issues/432
Reson being that we don't want to modify the data you are saving without explicitly say so.

```js
// this:
FileSaver.saveAs(hyphenCsv, "hyphen-test.csv", { autoBOM: true });

// or this might solve it 
var hyphenCsv = new Blob(
  [ String.fromCharCode(0xFEFF) + `"hypen","-","‐"` ], 
  { type: "text/csv;charset=utf-8" }
);
```

**Comment by ashlincascade** [comment]
Ah, gotcha.

Excel doesn't seem to like the file exported with `autoBOM: true`, but it's happy when we manually prepend the 0xFEFF BOM character.

Comparing the two exported files, the `autoBOM: true` file is 17 bytes and the BOM-prepended file is 20 bytes. I'm not sure the best way to inspect these files to be sure, but it seems as if the autoBOM option may not be adding the BOM as expected?

**Comment by ashlincascade** [comment]
I just looked through the source code and the it seems to be looking for a parameter called `autoBom`, not `autoBOM` as you quote here and in the documentation. However, even with `autoBom: true` the output is still 17 bytes and Excel displays the second hyphen incorrectly.
