### ISSUE TITLE
Is it possible to retrieve the file that was just saved?

### ISSUE THREAD

**Issue by oluomoniyi** [eligrey/FileSaver.js#505]
Is it possible to programmatically retrieve the file that filesaver just downloaded?

Basically I need to retrieve the word document just saved, but then send that to a word document editor I have setup.

**Comment by jimmywarting** [comment]
nope, it would be bad if javascript from any browser where able to get any information outside of it's own sandbox.

Only thing you can do is:

```js
var excel = new Blob(content)
saveAs(blob, filename) // save excel to disk

doSomethingElse(excel) // do other web-stuff with excel

function doSomethingElse (blob) {
  uploadToServer(blob)
  preview(blob, container)
}
```

**Comment by oluomoniyi** [comment]
Thanks a lot, solved it, I used fetch + File interface i.e

```
fetch(publicFileURL)
        .then(res =>
          res.blob().then(blob => {
              const file = new File([blob], "fileName", {
                type:
                  "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            });

           doSomethingWithFile(file)

          })
        )
        .catch(e => console.log(e));
```

With this metho

**Comment by jimmywarting** [comment]
👍 

fyi: with github's code markdown you can append the code language after the ` so it gets highlighted
ex: ```js
