### ISSUE TITLE
Latest version of Chrome iOS opens blank "about:" page

### ISSUE THREAD

**Issue by bsteeves** [eligrey/FileSaver.js#506]
Unable to download a file correctly in the latest version of Chrome iOS (71.0.3578.77). Instead of previewing the file a blank "about:" screen is shown. Works correctly on Safari and Firefox.

iOS version 12.1

Can reproduce the behaviour on the demo site: https://eligrey.com/demos/FileSaver.js/

**Comment by jimmywarting** [comment]
...the demo is quite old

**Comment by bsteeves** [comment]
It's not just the demo, I'm seeing it on my website that uses the latest version of FileSaver. Same behaviour as the demo site.

**Comment by Diceble** [comment]
@bsteeves it is true what you say. I stumble upon this issue too in my application

**Comment by jmichel84** [comment]
I have the same issue in chrome IOS only. It works on Chrome Desktop. I also works on IOS with safari, Firefox or Opera.

**Comment by blueyestar** [comment]
Same problem here on iOS+Chrome

**Comment by k1ch** [comment]
We have the same issue too.

**Comment by scottkidder** [comment]
Has anyone had any luck debugging this?

**Comment by scottkidder** [comment]
I made some progress here. Seems `typeof FileReader === 'function'` sometimes and Chrome IOS will not open objectUrls or data urls.

The only thing I have somewhat working was changing always changing to `data:attachment/file;` and not doing a popup, just doing `location = url`. This causes Chrome IOS to prompt the user to download the file, but the catch is the file is just named `document` and with no pdf extension (in this case) it's not usable :(

**Comment by aplaskota** [comment]
@scottkidder I don't know if I get you correctly, but assuming that you have working solution for this issue, could you share some code example?

**Comment by jmichel84** [comment]
This issue appeared on 2018-12-4 with Chrome IOS version 71.0.3578 and is resolved after updating to the latest version (72.0.3626 - 2019-1-29). Could someone else update Chrome from the App Store and confirm?

**Comment by scottkidder** [comment]
@jmichel84 Wow thanks for the heads up. Are you aware of any issue and/or release notes that mention this issue?

**Comment by scottkidder** [comment]
I can confirm this is fixed with latest Chrome

**Comment by bsteeves** [comment]
Same. File download is working as expected in the latest version of Chrome

**Comment by RezaRahmati** [comment]
> This issue appeared on 2018-12-4 with Chrome IOS version 71.0.3578 and is resolved after updating to the latest version (72.0.3626 - 2019-1-29). Could someone else update Chrome from the App Store and confirm?

I just checked with chrome 72.0.3626.101 and still same issue

**Comment by Artfloriani** [comment]
Tested on Chrome 73.0.3683.68 and this issue persists

**Comment by jparismorgan** [comment]
I have reproed this with Chrome 87.0.4280.77 on an iPhone XR running iOS 14.3-beta. When I use code-as instead of previewing the file a blank "about:" screen is shown. When I try without the pop-up, and with and without always changing to `data:attachment/file;`, Chrome iOS prompts to download the file, but the the file is just named document with no extension. I am passing a `Blob` with type `image/jpeg`.

It is formatted correctly and I'm able to download it using Safari iOS.
