### ISSUE TITLE
Cannot save files on Outlook Mac

### ISSUE THREAD

**Issue by markb-trustifi** [eligrey/FileSaver.js#509]
FileSaver works well on all browsers including Safari, but shows this popup in Outlook for Mac:

![31315907-fef5c60c-ac2a-11e7-996c-a64bf267a357](https://user-images.githubusercontent.com/29097494/50424987-0173af80-0877-11e9-9def-57f9459b8805.jpg)

OS: MacOS High Sierra 
ENV: Outlook Client 15.41 and 16.20 (v16 doesn't show popups at all)

Safari agent where it is working well:
`5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15`

Outlook internal Safari agent where it is failing:
`5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko)`

**Comment by SanketDG** [comment]
@markb-trustifi @eligrey Hi, is there any update regarding this, I have been facing the same problem as well.

**Comment by rajivshah3** [comment]
@markb-trustifi @SanketDG does #509 solve the issue for you? We're running into a similar issue in our app and it seems like this fixed it
