### ISSUE TITLE
XLSX.writeFile() is getting called 2 times

### ISSUE THREAD

**Issue by profile4vaibhav** [eligrey/FileSaver.js#514]
Hello,

I have written a below code using XLSX:

XLSX.writeFile(workbook, 'sample.xlsx');

Now this line is getting called 2 times.

Is there any specific reason for this?

**Comment by Ruffio** [comment]
Is XLSX a part of FileSaver.js? I can't find XLSX anywhere in th FileSaver.js code, so I think it is the wrong GitHub project that you are posting your issue...

**Comment by nicumaxian** [comment]
Got the same issue. rolled back to 1.3.1 and everything is working.

**Comment by Ruffio** [comment]
@nicumaxian Can you please point me to where XLSX is a part of FileSaver.js?

Looking in the code (https://github.com/eligrey/FileSaver.js/blob/master/dist/FileSaver.js) there are nothing that says either XLSX or a method called 'writeFile'. In FileSaver you use the method saveAs (https://github.com/eligrey/FileSaver.js/blob/master/dist/FileSaver.js)

This issue should be closed.

**Comment by profile4vaibhav** [comment]
FileSaver and XLSX are two different libraries, so the issue I have posted here is related to XLSX not with FileSaver. Because I am not using FileSaver's function,  I am using XLSX libraries function which is XLSX.writeFile(). That's why the issue shoudn't be close out.

**Comment by Ruffio** [comment]
So no code is provided to demonstrate the issue and another library is used which is causing the issue, but still the an issue is filed here? That doesn't make any sense.

Nowhere in the readme does it say that other libraries are supported: https://github.com/eligrey/FileSaver.js/

I suggest that an issue is filed at the other library.

This should be closed.
