### ISSUE TITLE
Can I download file with POST request?

### ISSUE THREAD

**Issue by TheColdVoid** [eligrey/FileSaver.js#516]
Can I download file with POST request?
Thanks for your answer

**Comment by Ruffio** [comment]
FileSaver.js is about having some data and then save them. What you are asking about is to download data by a POST request. POST requests are send to a server, FileSaver.js saves data from the browser to the client computer.

This issue should be closed.

**Comment by jimmywarting** [comment]
> FileSaver.js is about having some data and then save them  ...  FileSaver.js saves data from the browser to the client computer.

And with that in mind I hesitated implementing a simple way for anyone to download urls
but it seems like a common senario among many so I decided to add a simple way for regular GET request to be downloaded. I thought of using the fetch api so you could request either a url string or a Request Object.

```js
saveAs(new Request('/foo.txt', { method: 'post' }), 'foo.txt')
```

But it would become too many edge case senario to handle, best option is to use `download` attribute whenever possible. So a condition would have to be made for that - so i did. but first needed to check if it's avalible with a sync HEAD request - which you can't do with Request. also IE don't support fetch so a condition for fetch or xhr would also be needed. and I could not just pluck the url from Request object if it's a GET request as it might have included request headers as well.

then there is also cases where it can return 4xx 5xx or other error status codes
I would consider downloading a `/404.html` as a success... some might actually want to save non 200 responses. the only time i would consider not saving anything to the hard drive is on network or DNS error
like when you are not able to reach the server or network is down.

now ppl also want to extract the filename from url or use the attachment header filename 

So the reality is: **FileSaver.js is about saving data you have in the browser** - things that are generated on the client side like a canvas, camera, microphone, webtorrent etc. 

If things are coming from the server then there is a better way to **save files with [content-disposition](https://github.com/eligrey/FileSaver.js/wiki/Saving-a-remote-file#using-http-header) response header** not only will it give you better download support for the safari browser that have problems with saving blobs, saving much larger files that don't need to be buffer up in memory but you will also not need FileSaver.js. all doe you can't use ajax - you have to make a `<form>` submission to support POST request. but if you require request headers as well then you need to make a ajax request.

See how much complicated things becomes when server generated files becomes involved.
you need to handle your POST request yourself cuz we will not handle everything to make FileSaver more complex

```js
// download the post body as blob and then save it if you must
fetch(url, {otps}).then(res => res.blob()).then(blob => saveAs(blob, filename))
```
