### ISSUE TITLE
SaveAs does not work with Blobs in 2.0

### ISSUE THREAD

**Issue by roemhildtg** [eligrey/FileSaver.js#519]
The following code does not produce any file download results in chrome: In addition, no errors are given:

```
saveAs(blob, fileName);
```

See: 
https://github.com/bpampuch/pdfmake/issues/1599

**Comment by Ruffio** [comment]
Have you tried what it says in the README?

![image](https://user-images.githubusercontent.com/1877612/51500244-aa0d2480-1dcd-11e9-999a-ff2d2e27b7f2.png)

**Comment by roemhildtg** [comment]
True, worth a shot. But the readme also mentions using 

```
import {saveAs} from 'file-saver';
```

**Comment by Ruffio** [comment]
Perhaps pdfmake should update how it calls FileSaver?

**Comment by devrathnd** [comment]
Using file-saver in an angular 7 app but it isn't working when using saveAs. Amchart's export too doesn't work. saveAs doesn't throw any error and there is no file being downloaded too. But it works when using 1.3.8.

```javascript
const fileSaver: any = require('file-saver');
canvas.toBlob((blob: Blob) => {
  .saveAs(blob, filename);
}, filetype);
```

**Comment by dagda1** [comment]
@devrathnd depending on your tsconfig, it should be `import * as FileSaver from 'file-saver';` or `import FileSaver as 'file-saver'`.

It is a default export

**Comment by moghthalkushal** [comment]
I am facing the same issue , despite the fact i am using import * as FileSaver from 'file-saver' , i am saving blob that is a zip of all images.

FileSaver.saveAs(content, 'AllGraphs.zip');

**Comment by Alex1100** [comment]
This ticket should be closed since bpampuch/pdfmake#1599 has been closed.

**Comment by renilbabu03** [comment]
@devrathnd  : Were you able to solve this issue? For me its working fine in development but in production its not working. And there are no errors. Using Angular 7

**Comment by renilbabu03** [comment]
`import {saveAs} from "file-saver"; `

This saved my day.
