### ISSUE TITLE
How to add headers manually

### ISSUE THREAD

**Issue by Vinutha-BK** [eligrey/FileSaver.js#528]
Hi ,

This is good option. I am using in my project . Currently headers are same as the list fields.
`data = [{name:'Albert', userid:'albert@github.com'},{name:'Robert', userid:'robert@github.com'}]`
I want to have header names like 'Name' and 'User Id'
I am not getting how to pass headers manually.
```ts
function exportJsonToFile(data, fileType: any, name: string) {
    const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(data);
    const workbook: XLSX.WorkBook = {
        Sheets: { data: worksheet },
        SheetNames: ['data']
    };
    const excelBuffer: any = XLSX.write(workbook, {
        bookType: fileType,
        type: 'array'
    });
    const blob: Blob = new Blob([excelBuffer], {
        type: '.' + fileType
    });
    FileSaver.saveAs(blob, name + '.' + fileType);
}
```

**Comment by Ruffio** [comment]
FilerSaver is used to save content from the browser to the file system. So where is it that you want headers? Headers are used when performing requests to e.q. servers, but that is not in the scope of this project. All options are documented in the README.md: https://github.com/eligrey/FileSaver.js
XLSX is a different project. Questions of how ot use that should be asked at Stackoverflow or simular.

**Comment by jimmywarting** [comment]
out of this scope
