### ISSUE TITLE
can I save file in worker?

### ISSUE THREAD

**Issue by Y0QIN** [eligrey/FileSaver.js#529]

**Comment by Ruffio** [comment]
I havn't tried it, but I don't see why not. But try and let us hear your result :-)

**Comment by jimmywarting** [comment]
no, you can't do that from a WebWorker or sharedWebWorker. you have to send the blob to the main window and save it from there.
However you could save a blob from a service worker but wouldn't be able to use fileSaver
then you have to navigate (open a link) and respond with that blob and a `content-disposition` header kinda like what [streamsaver](https://github.com/jimmywarting/StreamSaver.js) is doing
