### ISSUE TITLE
saveAS used 3min while I create a file with 100M on firfox nightly.Maybe you have same suggestion?

### ISSUE THREAD

**Issue by Y0QIN** [eligrey/FileSaver.js#530]
saveAS used 3min while I creating a file with 100M on firfox nightly.Maybe you have same suggestion?

**Comment by Ruffio** [comment]
Please provide a jsbin or simular to demonstrate the issue.
saveAS support various file sizes, but files with that size should be saved directly from the server IMHO.

**Comment by Ruffio** [comment]
This issue should be closed due to lack of response from originator
