### ISSUE TITLE
JKS

### ISSUE THREAD

**Issue by MarceloBaeza** [eligrey/FileSaver.js#541]
Hello I need help please I was trying to pass the byte [] to do blob and download with saveAs a JKS file. I get the byte array with a web service. I verify the length and content are the same.
This is my code (the byte array is an example but it is valid):

```
var byteVar: any[] = [0, 0, 0, 2, 0, 0, 0, 20, 78, -41, 5, -106, 15, 20, -125, -99, -111, -32, 43, 21, 75, 124, 63, 8, 108, -47, -87, -106, 0, 0, 5, 97, 4, 0, 10, 75, 69, 89, 95, 77, 65, 83, 84, 69, 82, 0, 0, 1, 105, -17, 116, -21, 27, 0, 0, 0, 0, 0, 0, 0, 76, 0, 0, 0, 20, -81, 5, 53, 127, -2, 43, 91, -44, 37, -25, 9, -97, 17, 115, 30, -58, 91, -126, 93, 44, 0, 0, 6, 73, -66, 81, -128, 31, -42, -40, -118, 79, -59, -113, 6, 112, -35, -98, -39, 12, -3, -109, 17, 62, -11, -25, 11, 115, -94, -118, -49, -92, -109, -87, -14, 81, 44, -39, -63, -30, 100, 105, 0, 19, -23, -7, 115, -84, 96, 13, -95, 29, 0, -82, -44, -23, 52, -75, 99, -112, -68, -8, 110, 11, 0, -1, 51, -65, 47, 104, -15, -27, -61];
var blob: Blob = new Blob(byteVar);
saveAs(blob, "pinKeyStore.jks", false);
```
The file is downloaded, but I when try open this. 
The message is:
![Captura](https://user-images.githubusercontent.com/22486330/55741757-090d2d80-59fc-11e9-92de-8d7d1a3599c4.PNG)

**Comment by jimmywarting** [comment]
That byte array dose not look like a Uint8Array... looks more like a Int8array...

Either way you are constructing the blob with wrong kind of data.
the blob constructor takes a array of blobParts

- a blobPart can be either a ArrayBuffer, ArrayBufferView, Blob or DOMString
- a ArrayBufferView is either one of:
  - Int8Array,
  - Uint8Array,
  - Uint8ClampedArray,
  - Int16Array,
  - Uint16Array,
  - Int32Array,
  - Uint32Array,
  - Float32Array,
  - Float64Array or
  - DataView.

So perhaps what you should be doing is

```js
const bytes = new Int8Array([0, 0, 0, 2, 0, 0, 0, 20, 78, -41, 5, -106, 15, 20, -125, -99, -111, -32, 43, 21, 75, 124, 63, 8, 108, -47, -87, -106, 0, 0, 5, 97, 4, 0, 10, 75, 69, 89, 95, 77, 65, 83, 84, 69, 82, 0, 0, 1, 105, -17, 116, -21, 27, 0, 0, 0, 0, 0, 0, 0, 76, 0, 0, 0, 20, -81, 5, 53, 127, -2, 43, 91, -44, 37, -25, 9, -97, 17, 115, 30, -58, 91, -126, 93, 44, 0, 0, 6, 73, -66, 81, -128, 31, -42, -40, -118, 79, -59, -113, 6, 112, -35, -98, -39, 12, -3, -109, 17, 62, -11, -25, 11, 115, -94, -118, -49, -92, -109, -87, -14, 81, 44, -39, -63, -30, 100, 105, 0, 19, -23, -7, 115, -84, 96, 13, -95, 29, 0, -82, -44, -23, 52, -75, 99, -112, -68, -8, 110, 11, 0, -1, 51, -65, 47, 104, -15, -27, -61])
const blobParts = [bytes]
const blob = new Blob(blobParts)

saveAs(blob, 'pinKeyStore.jks', false)
```


https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob

**Comment by MarceloBaeza** [comment]
oh!!! You are right, Thanks so much

**Comment by jimmywarting** [comment]
Did i guess right about what kind of ArrayBufferView you used also? :P
