### ISSUE TITLE
Save file at Jupyter host

### ISSUE THREAD

**Issue by lcflorindo** [eligrey/FileSaver.js#545]
Hi, i'm using Jupyter notebook to host a html page (http://127.0.0.1:8888/view/app/model.html).
In there, I want to select an option from dropdown then pressing the button it saves the txt file.

The thing is that I already made it by source code and it's downloading to my pc, not inside Jupyter. I already saw some other issues, so should I give up trying this path?

**Comment by jimmywarting** [comment]
Maybe you should post this kind of question in StackOverflow
With what you have written Nor I or StackOverflow can't help you b/c you don't provide any code, the link is not accessible from anywhere. 

> The thing is that I already made it by source code and it's downloading to my pc

So if it's downloading what do you need FileSaver for?

> ...not inside Jupyter. 

what do you mean by that?

> I already saw some other issues, so should I give up trying this path?

what other issue are you talking about

- I don't know what Jupyter is

- this don't sound like FileSaver has an issue

**Comment by lcflorindo** [comment]
> So if it's downloading what do you need FileSaver for?

I need it to download the txt file by server side. Jupyter Notebook it's a web app for programming different languages of code, also can hosts it through de LAN/Internet.

my FileSaver code is this one:
` $("#save-btn").click(function() {
        var blob = new Blob([x], {type: "text/plain;charset=utf-8"});
        saveAs(blob, "model.txt");
    }); `

When I click a button in my page, it downloads to my computer a txt file containing the selection from a dropdown.

> what other issue are you talking about

I mean Issues from here, opened by other users. Some of them only talk about specify paths to download but not to change which side downloads the file (server or client).

**Comment by jimmywarting** [comment]
Well, if the file is coming from the server i usually recommend that you download the file using server side technology

https://github.com/eligrey/FileSaver.js/wiki/Saving-a-remote-file#using-http-header
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

basically add this response headers

Content-Type
Content-Length
Content-Disposition

then you open the link using a hidden iframe or navigating to the url or try to open it in a new tab

**Comment by lcflorindo** [comment]
> basically add this response headers

That's nice! Can solve the problem right away. But by the content from this links doesn't say were it goes... It's right after the function?

**Comment by jimmywarting** [comment]
> But by the content from this links doesn't say were it goes... It's right after the function?

The reason it dose not say that is b/c all servers are different, php, .net, node python go
you set the response header on the server, not on the client side

**Comment by jimmywarting** [comment]
Maybe this is relevant to you?

https://jupyter-kernel-gateway.readthedocs.io/en/latest/http-mode.html#setting-the-response-status-and-headers
