### ISSUE TITLE
I can save a 19GB file with 16GB RAM in Chrome, but why?

### ISSUE THREAD

**Issue by yaobinwen** [eligrey/FileSaver.js#553]
The README says I can turn to `StreamSaver.js` if I need to save large files bigger then the blob's size limitation or don't have enough RAM. Here is my environment:

- Ubuntu 14.04
- I'm using Chrome `Version 74.0.3729.108 (Official Build) (64-bit)`. So I think the maximal blob size is `2GB` according to the README.
- My computer has `16GB` of RAM.
- I'm using `FileSaver.js` `2.0.1` (from `yarn add file-saver` and confirmed this from `package.json`).

However, I tried to download a file (`.tar`) of `19GB` and succeeded. This seems to conflict with what the README file says. **Is there something I overlooked?** Or **did `FileSaver.js` start to support really large files?** I looked into the changelog but didn't find such changes.

I'm using a very simple React.js app which renders a button like this:

```html
<Button text={'Download 19G.tar'} onClick={download19Gtar} />
```

The `download19Gtar` function is like this:

```javascript
import { saveAs } from 'file-saver'

let download19Gtar = () => {
  saveAs(
    'http://localhost:8080/19G.tar',
    '19G.tar'
  )
}
```

The `http://localhost:8080` is a simple file server I started with [`http-server`](https://www.npmjs.com/package/http-server) with `--cors` enabled (`http-server /tmp/files -a localhost --cors`) because my React.js app is running on `localhost:3000`.

After I clicked the download button, I watched the memory consumption in the System Monitor but didn't observe any obvious rise of usage (which surprised me a little bit). It took several minutes before the `Save as` dialog popped up and another several minutes to save the file to my local file system, but everything worked well.

**Comment by jimmywarting** [comment]
**Sort answer**: You never create a blob so the data is not held in the memory and piped directly to harddrive using this:

```html
<a href="http://localhost:8080/19G.tar" download="19G.tar">download</a>
```

---

I got tired of ppl saving generated blob that came from the server. FileSaver was not built with that intention.
FileSaver where mostly built for data that you have on the client side. (like a picture from the `<canvas>` element or a stored blob in indexedDB)

...any how... we also use links with a download attribute with a filename and then click on that.
a blob-url is created with [URL.createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) and works mostly as any other link.

if that don't work we fallback to `msSaveOrOpenBlob(blob)`

Blob's where FileSavers only way of saving things earlier so ppl used to do things like:
```js
fetch(url)
  .then(r => r.blob())
  .then(save) // FileSaver creates a blobURL for you if its a blob
```

Which where a wast of memory by keeping the data in some variable and not doing this directly
```html
<a href="url" download="19G.tar">download</a>
```

I have told ppl numerus of times not to use FileSaver if the source is coming from the server and instead use content-disposition attachment header if they could. cuz that works much better in Safari and you wouldn't need FileSaver, or the download attribute, or the `msSaveOrOpenBlob`
You just have to open the link to 19gb.tar 

but ppl used to fetch data anyway and even fail to create/return the data as a blob
...so we just added support for urls in FileSaver

**Comment by jimmywarting** [comment]
Ups, forgot about that part where you have the file on a other origin...

well, getting a ajax response as blob and not as arrayBuffer or text temporarily stores the blob on the disk and not in the memory

**Comment by jimmywarting** [comment]
I would advise you do use content disposition header instead

**Comment by yaobinwen** [comment]
Ah, I see! I did see the "on the client-side" in README but didn't realize what that actually means until I read your comment (still new to front-end development). BTW, in the end I did use `Content-Disposition` to download the file.
