### ISSUE TITLE
newer chrome failed to execute 'createObjectURL'.

### ISSUE THREAD

**Issue by TzyHuan** [eligrey/FileSaver.js#559]
chrome already removed "createObjectURL" function from the current version.
MDN suggest replace "createObjectURL" by "src​Object"!!
I'm looking into source codes try to fix the problem, but html tag "\<a\>" not exist the property of "scr".
so I have no idea how to download files on newer chrome...

chrome:  74.0.3729.157 
Source: 
https://developers.google.com/web/updates/2018/10/chrome-71-deps-rems
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/srcObject

**Comment by jimmywarting** [comment]
It only means you can no longer create objectURL from mediastream
createObjectURL is still avalible and used for blob's

createObjectURL was never meant to accept a MediaStream, only blobs

**Comment by jetlej** [comment]
+1
