### ISSUE TITLE
Library uses obselete msSaveOrOpenBlob method

### ISSUE THREAD

**Issue by jamesbarrett95** [eligrey/FileSaver.js#564]
It has come to my attention that the msSave​OrOpen​Blob method[ is obsolete and shouldn't be used in production builds.](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveOrOpenBlob).

I noticed that this method is being used in ```FileSaver.js``` I'm unsure on the workaround for this as - I can't seem to find anything on the web.

I've posted a question on StackOverflow which I'm hoping will gain some traction:
https://stackoverflow.com/questions/56425664/how-do-i-download-pdfs-in-internet-explorer-11-safely

**Comment by jimmywarting** [comment]
the msSave​OrOpen​Blob is used as a fallback if `a[download]` isn't available
