### ISSUE TITLE
no save dialog shown on mobile (android and ios)

### ISSUE THREAD

**Issue by Lin84** [eligrey/FileSaver.js#565]
in SPA using vue and cordova:
    "cordova-ios": "~4.5.5",
    "cordova-android": "~6.4.0"

on desktop (chrome) is working as expected, user can save file 
but on mobile devices both IOS and Android  nothing happens, no response, no error

I tried with your example:
![image](https://user-images.githubusercontent.com/7355572/58876071-555bad80-86cd-11e9-97f2-062908eea750.png)

Question: 
sorry, maybe I am missing something but does this library support the saving file on mobile devices or I made a mistake somewhere?

**Comment by jimmywarting** [comment]
Officially we don't provide any support for cordova.
I would expect cordova has some core api to save things directly to the filesystem somehow. 

not sure that cordova even supports `a[download]`

**Comment by Lin84** [comment]
thx for sharing
