### ISSUE TITLE
How to know when the download begins and ends

### ISSUE THREAD

**Issue by carlosEdua** [eligrey/FileSaver.js#569]
hi, I want to make an animation, so when the download  begins the animation too, and the download ends and also the animation, but the function saveAs() is not a promise and returns void(or undefined), so, the only way to know if the download is ready is when  the file explorer appears.

how I can know when the download begins and ends??
I'm just downloading images

**Comment by jimmywarting** [comment]
It's impossible to figure out with FileSaver.
Saving a blob is pretty much instant.

However StreamSaver have some degree of figuring out different state of the download progress.

**Comment by jimmywarting** [comment]
Here is an example where desiredSize is lowered as you pause the download (only works with [transferable stream](https://www.chromestatus.com/features/5298733486964736))
https://jimmywarting.github.io/StreamSaver.js/examples/torrent.html

**Comment by xianshenglu** [comment]
You know, we can pass a url to `saveAs`. In that case, we might need a promise as return value.
