### ISSUE TITLE
Is it possbile to overwrite file?

### ISSUE THREAD

**Issue by FutureFireplace** [eligrey/FileSaver.js#572]
While doing this: 

```js
var file = new File(['Hello; world'], 'helloWorld.csv', {type: 'text/plain;charset=utf-8'})
saveAs(file)
var blob = new Blob(['Hello; world; 22'], {type: 'text/plain;charset=utf-8'})
saveAs(blob, 'helloWorld.csv')
```

- I get a result of two files being created. Is it possbile to overwrite an existing file instead?

**Comment by jimmywarting** [comment]
You can only overwrite the file if you manually set the file to the same name in browsers "save as" dialog. 

but Why save it multiple times?

**Comment by jimmywarting** [comment]
If you only appending stuff then you could StreamSaver to create a write stream...

**Comment by FutureFireplace** [comment]
Are yes, thx ... I guess I have been by Streams before (in C# at least). Do you know any examples - similar to his js example?

**Comment by jimmywarting** [comment]
Sorry, what? didn't understand fully.

There is a handfull of examples in the [example folder](https://github.com/jimmywarting/StreamSaver.js/tree/master/examples)

Depends kinda what your data looks like

**Comment by jimmywarting** [comment]
Judging by the data you gave as an example

```js
const { writable, readable } = new TextEncoderStream()
const writer = writable.getWriter()

readable.pipeTo(streamSaver.createWriteStream('out.txt'))

writer.write('Hello; world') // write a chunk
writer.write('; 22') // write a chunk
writer.close() // finalise the stream
```
