### ISSUE TITLE
Can't open same-window link to "chrome-extension:/...

### ISSUE THREAD

**Issue by jaemdessources** [eligrey/FileSaver.js#573]

**Comment by js-lover** [comment]
hello everybody
i build a chrome app and i have installed it but i got a problem:
when i click on a link it doesn't open and in the console i see this message:
Can't open same-window link to "chrome-extension://jodpcdookfiejfcdohkcfijabjjoamhp/html/myPage.html"; try target = "_blank"
i tried the suggestion but it didn't works what should i do ?
thanks already for your suggestions
