### ISSUE TITLE
Formatting lost - no new lines in Firefox and Edge, works as intended in Chrome and Opera

### ISSUE THREAD

**Issue by jgrichard** [eligrey/FileSaver.js#592]
I'm trying to save an array as a csv file but the formatting is lost in Firefox and Edge. In Chrome and Opera the file outputs as expected but in Firefox and Edge there are no new lines in the file.

Attached is the output from Chrome/Opera versus the output from Firefox/Edge.

The function I use to create the file:

```
var lineArray = [];
data.forEach(function (infoArray, index) {
    var line = infoArray.join(",");
    if (index === 0) {
        lineArray.push("data:text/csv;charset=utf-8,Data1,Data2,Data3,Data4,Data5,Data6,Data7,Data8,Data9\n" + line);
    } else {
        lineArray.push(line);
    }
});
var csvContent = lineArray.join("\n");
saveAs(csvContent, "OutputFile.csv");
```

The data array looks like:
```
data = [["1","2","3","4","5","6","7","8","9"], ["1","2","3","4","5","6","7","8","9"], ["1","2","3","4","5","6","7","8","9"], ...]
```

The correct output (Chrome/Opera):
![csv-right](https://user-images.githubusercontent.com/41802093/63352615-dbd07480-c337-11e9-83b9-5b4bf81303ee.PNG)
The incorrect output (Firefox/Edge):
![csv-wrong](https://user-images.githubusercontent.com/41802093/63352616-dbd07480-c337-11e9-97aa-df0aa03af67f.PNG)

I've tried adding a carriage return character "\r" before the new line character which did not fix the issue.

Any help is appreciated!

**Comment by jimmywarting** [comment]
try generate a blob instead of a dataurl

**Comment by jgrichard** [comment]
It worked!

For reference I used this to create the blob from the array (may not be the best implementation).

```
var blob = new Blob(["Data1,Data2,Data3,Data4,Data5,Data6,Data7,Data8,Timestamp,Timediff"], {type: "data:text/csv;charset=utf-8"});
            can_data.forEach(function (infoArray, index) {
                blob = new Blob([blob,"\n"+infoArray], {type: "data:text/csv;charset=utf-8"});
            });
            // var csvContent = lineArray.join("\r\n");
            saveAs(blob, "CAN9-" + moment().format('YYYY-MM-DD-HH-mm-SS') + ".csv");
```
