### ISSUE TITLE
Download multiple files warning

### ISSUE THREAD

**Issue by Polygetter** [eligrey/FileSaver.js#599]
When the user starts a second download with my Chrome extension, a warning pops up where the user must allow the site to download multiple files. Is it possible to avoid this warning?

**Comment by jimmywarting** [comment]
zip it and download everything at once?

**Comment by Polygetter** [comment]
Unfortunately that is not a solution.
This extension downloads crawled data from the site. If the user starts another download, it's because the site content changed. Basically there is only one file to download, but that file might change and thus require a redownload.

**Comment by Polygetter** [comment]
This is the code I'm using:
`   let resultBlob = new Blob([stringContent], {type: "application/xml"});
    saveAs(resultBlob, fileName);`

**Comment by jimmywarting** [comment]
- Then the only thing left to do is changing your own browser preference.

- You could try using [StreamSaver](https://github.com/jimmywarting/StreamSaver.js), it works somewhat differently then how FileSaver solves it, try this [demo](https://jimmywarting.github.io/StreamSaver.js/examples/fetch.html) first. it should have the same constraint as FileSaver but maybe not...

- Sometime later i would recommend you to use the [Native-filesystem API](https://github.com/WICG/native-filesystem/blob/master/EXPLAINER.md) but it ain't ready for use yet

**Comment by jimmywarting** [comment]
one possible issue is that you don't save the file on a (trusted) user interaction event
https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted

some things are blocked like popups when it's done with a setTimer or inital load

**Comment by jimmywarting** [comment]
I have had problem saving files with FileSaver & StreamSaver with an duration...
eg: clicking on a download button that fetches something with ajax, the ajax call takes more than 5 seconds, calls `saveAs(blob, 'name')` only to see it being blocked. if you however use streamsaver and call the `createWriteStream` immediately on a user interaction then the saving will start right away and you can later write to the file asynchronous
