### ISSUE TITLE
IOS as always...

### ISSUE THREAD

**Issue by DevJhns** [eligrey/FileSaver.js#618]
This is more conceptual question, so after IOS 13, Ipad IOS became IpadOS, so it is not IOS anymore, and it can download files from blobs with preview window like this:
https://user-images.githubusercontent.com/6698344/66068025-1f301c80-e54d-11e9-82eb-cbc5b33c8c3a.PNG
`var blob = new Blob(receiveBuffer, {type: 'any/mimetype'});`
`a.href = URL.createObjectURL(blob);`
`a.download = 'filename.ext';`
so this code works perfectly everywhere except Iphone,
but on image above u can see that download works on Iphone(I can get this result only on Ipad, on Iphone file opens in new tab)
How is it possible?
Does new Iphones support this download managment?
It is beta IOS or which version it can be? 
Any news on apple plans to make this download managment for other Iphones?

**Comment by OlympicLarry** [comment]
But does that code work on an iPad using Chrome on ios 13?

**Comment by camboui** [comment]
Hi, 

I've lost some time today with blob download on IOS. Like you, Safari was previewing it instead of downloading it with its file manager.
The trick is to remove the blob type : 
```
    const blob = new Blob([data]);
    saveAs(blob, fileName);
```
It shows the IOS download popup !
Hope it helps.

**Comment by DevJhns** [comment]
> Hi,
> 
> I've lost some time today with blob download on IOS. Like you, Safari was previewing it instead of downloading it with its file manager.
> The trick is to remove the blob type, Safari might think it can't preview it so it will download after asking for confirmation.
> 
> ```
>     const blob = new Blob([data]);
>     saveAs(blob, fileName);
> ```
> 
> Hope it helps.

Thx for reply!
My problem was with older iphone versions didn't support download due to some file managment issues.
