### ISSUE TITLE
FileSaver is not a function

### ISSUE THREAD

**Issue by Preduri** [eligrey/FileSaver.js#623]
Hello everybody,

I just downloaded FileSaver, I have version 2.0.2

In my HTML file, I use the "FileSaver.saveAs" function and during my tests on firexfox, the console tells me "FileSaver.saveAs is not a function". Anyone have the solution? :(

**Comment by jingyulong** [comment]
just use saveAs.

    <script src="../lib/FileSaver.min.js"></script>
    <script>
        document.getElementById("ExportToExcel").addEventListener("click", function() {
            var template = document.getElementById("container").innerHTML;
            var blob = new Blob(['\ufeff' + template], {
                type: "application/octet-stream;charset=utf-8"
            });
            saveAs(blob, "test.xlsx");
        });


    </script>

**Comment by ziaulrehman40** [comment]
Issue should be closed
