### ISSUE TITLE
FileSaver saves file with no type and wrong name (download) on Chrome

### ISSUE THREAD

**Issue by KobeNorris** [eligrey/FileSaver.js#628]
Every thing works fine when I am using Firefox. 

However, when I am using chrome browser to download the same file, chrome browser opened a new page with "downloading..." and the downloaded file is a no type file called "download". The content of the file is correct.

I have tried all demo provided by README.md, they all worked on Firefox and malfunctioned on Chrome with same problem.

Dose anyone faced the same issue like me?

![1](https://user-images.githubusercontent.com/51012594/74594062-ea1ef500-5029-11ea-8004-853df31af2a1.JPG)

**Comment by KobeNorris** [comment]
Problem solve by @E-train-Liu. Lastest update bug issue, see pull request. 🥇

**Comment by ignatandrei** [comment]
I have the same problem ( works on edge, does not on Chrome) . Where I find the fix ?

**Comment by aidenliew** [comment]
Hi. I also have the same issue and follow the post above and used the FileSaver.min.js in the same path but still faced the same issue. Can you help to provide some details on steps you do to solve the problem? i understand that you are just using the .js file but i just want to make sure i din't miss any thing. thank you

**Comment by macdigger** [comment]
guys, you can just manually update the unminified dist based on this pull request:
https://github.com/eligrey/FileSaver.js/pull/629/files

Just replace the browser detection line with a new one in that pull req and you'll be set.

**Comment by ignatandrei** [comment]
Works for me. However, this should be also compiled into the filesaver.min.js
