### ISSUE TITLE
SaveAs in chrome mobile no longer opens save dialog, opens in new tab

### ISSUE THREAD

**Issue by hurleyrc89** [eligrey/FileSaver.js#650]
iOs 13.4.1, Chrome 81.0.4044.124

SaveAs opens the blob in a new tab instead of prompting to save when saving pdf/image. When attempting to save a .zip nothing happens.

Works as expected in safari / chrome desktop 81.0.4044.138 / android chrome 81.0.4044.138

**Comment by krestaino** [comment]
@hurleyrc89 Did you figure out a solution? I'm having the same issue with iOS Chrome.

**Comment by hurleyrc89** [comment]
Think it was just an ios thing. I believe the devs have stated they can't
do anything and to let apple know the way they handle the download is less
than ideal.

**Comment by imrim12** [comment]
I'm having the same problem as i'm trying to download the image programmatically but instead it opens the image in new tab
The strange thing is it'll work for the same image in the second click, seem like a browser policy thing
p/s: I'm using Google Chrome
