### ISSUE TITLE
How do I get him to append writes instead of re-creating a document every time?

### ISSUE THREAD

**Issue by sexfio** [eligrey/FileSaver.js#657]
How do I get him to append writes instead of re-creating a TXT every time?
like flags:a+

**Comment by jimmywarting** [comment]
poorly written title/description - but luckily i understood you - for that you have to use either 

- https://github.com/jimmywarting/native-file-system-adapter
- https://github.com/jimmywarting/StreamSaver.js
- or https://github.com/WICG/native-file-system

all 3 of this can append data to a file handle

**Comment by jimmywarting** [comment]
not possible with filesaver
