### ISSUE TITLE
Download is disallowed in chrome 83

### ISSUE THREAD

**Issue by PradeepaSoundar** [eligrey/FileSaver.js#658]
After latest update from chrome (version 83), i'm not able to download any files. Same functionality works fine in other browsers. When ever i tried to download warning shown in chrome console

_Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See [https://www.chromestatus.com/feature/5706745674465280](https://www.chromestatus.com/feature/5706745674465280) for more details._

My Code snippet
```
const file = new Blob([response.data], { type: 'application/vnd.ms-excel' });
fileSaver.saveAs(file, 'analytics.xlsx');
```

I'm using file-saver@1.3.3, Updating to latest version will solve this issue?

Please let me know how to fix this issue?

**Comment by mmzysk** [comment]
Closed...what was the fix?
