### ISSUE TITLE
saveAs fails on Chrome 83+

### ISSUE THREAD

**Issue by murrple-1** [eligrey/FileSaver.js#666]
Duplicate of #658, which was closed without reason.

On Chrome, calling `saveAs([Blob], [filename: string]` fails, and the following message is output to the console at info level:

```
Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.
```

Relevant docs:
https://www.chromestatus.com/feature/5706745674465280

**Comment by ClydeDroid** [comment]
I am getting this message as well in Chrome. Firefox downloads still work fine.

**Comment by spanitz** [comment]
...as the message above indicates, this is fairly simple to fix: just add the 'allow-downloads' attribute to your CSP header:

Here's an example how this header may looks like:
`Content-Security-Policy: sandbox allow-downloads`

Here's an exmaple using express.js and helmet:
```js
app.use(helmet.csp({
  directives: {
    sandbox: ['allow-downloads', /*...*/],
    //... 
  }
}))

**Comment by murrple-1** [comment]
I can confirm that this seems to be the best (possibly only?) fix available

**Comment by mmzysk** [comment]
Could I do something like this in Angular?  Seems like we are having a similar issue.
