### ISSUE TITLE
crashes on node

### ISSUE THREAD

**Issue by vince1995** [eligrey/FileSaver.js#681]
I know that's a package for clients but I'm server side rendering my website which imports this package. With the latest version 2.0.4 (yeah, I mean that version which was released several minutes ago) my server crashes:

```
/home/git/my-package/node_modules/file-saver/dist/FileSaver.min.js:52
      a = /Macintosh/.test(navigator.userAgent) && /AppleWebKit/.test(navigator.userAgent) && !/Safari/.test(navigator.userAgent),
                           ^

ReferenceError: navigator is not defined
    at ../src/FileSaver.js:72:39
    at /home/git/my-package/node_modules/file-saver/dist/FileSaver.min.js:4:104
    at Object.<anonymous> (/home/git/my-package/node_modules/file-saver/dist/FileSaver.min.js:9:3)
```

**Comment by jimmywarting** [comment]
fixed (2.0.5)

**Comment by vince1995** [comment]
Tanks a lot. :)

**Comment by kaiyoma** [comment]
I don't think this is fixed. I'm still seeing this crash in 2.0.5.

**Comment by vince1995** [comment]
2.0.5 fixed it for me. What's the output?

**Comment by kaiyoma** [comment]
I filed a new issue here: https://github.com/eligrey/FileSaver.js/issues/685
