### ISSUE TITLE
saveAs fails with no given reason on Legacy Edge

### ISSUE THREAD

**Issue by Mark-A-Williams** [eligrey/FileSaver.js#684]
I'm working on an Angular 9 application, for which we are required to support IE11 and Legacy Edge until next summer. We're using `saveAs()` for our file download functionality, and have recently been finding that it simply doesn't work on Legacy Edge.

The implementation is a very simple click event on a button element which calls saveAs with a blob and filename as arguments - these are both being created correctly, but then no file is downloaded. There is no error of any kind in the console, and no warning given by the browser.

I also tried changing the filename to something simple as per a response on [Issue 584](https://github.com/eligrey/FileSaver.js/issues/584), but this didn't help. We've observed this issue for various file types including CSVs and PDFs. File sizes have been on the order of 10-20 MB at most.

My versions, for reference, are Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18362. Interestingly this works with no issues on IE11, and of course all more modern browsers. Any help would be much appreciated

**Comment by eligrey** [comment]
Does `navigator.msSaveBlob()` work for you in legacy Edge? If not, then this issue is likely related to Windows Group Policy.

**Comment by Mark-A-Williams** [comment]
Ah, so that does work. In that case it seems that a bit of code to detect if we're in legacy Edge and fall back to that if so will be sufficient, thanks! Out of interest however, do you expect legacy Edge to be supported? It's not quite clear on the readme whether it refers to old or new Edge, might be worth a clarification.

**Comment by ConfidantCommunications** [comment]
I'm having a similar issue with the latest Edge for iOS: 45.11.11

**Comment by jiteng-dev** [comment]
@ConfidantCommunications are you able to fix the issue latest Edge for iOS, I am facing same issue?

**Comment by ConfidantCommunications** [comment]
I just updated Edge for iOS. Still no solution on my end.
