### ISSUE TITLE
Encryption: does it/ will it get supported

### ISSUE THREAD

**Issue by rrrepos** [eligrey/FileSaver.js#694]
Hello:

Are there any plans to support password based encryption in this library? 

If so, I guess, there will have to be an accompanying feature of opening of a File too with a password.

Thanks

**Comment by TDay1** [comment]
I can't speak for the maintainer on this, but in my mind it would make more sense to use an [encryption library](https://gist.github.com/jo/8619441) to encrypt your data and then save it. So my answer to whether there are any plans to support password based encryption in this library is probably not.

**Comment by rrrepos** [comment]
Thanks @TDay1 . In fact, I am doing some encryption of sorts but was more wondering if there is value in having it at the file level (OS Level) with some AES type of encryption. So that even outside of the reader of that file type, the OS will not permit opening of the file. Something similar to PDF with password.

**Comment by jimmywarting** [comment]
File safer is only about saving blobs
Not modifying it in any way. For encryption you just use your own tools
