### ISSUE TITLE
How to batch download blobs? If download too many blobs, it will lose several images.

### ISSUE THREAD

**Issue by JiangWeian** [eligrey/FileSaver.js#697]
The code for the loop call is similar to:
```js
    viewportElement.querySelector('canvas').toBlob(blob => {
	  saveAs(blob, file);
	  console.info('blob size:' + blob.size);
	  resolve({ blob, file });
    });
```

**Comment by jimmywarting** [comment]
you need to either zip all files or use the new [File system access](https://github.com/wicg/file-system-access/)

**Comment by JiangWeian** [comment]
@jimmywarting , This is because the code ‘ viewportElement.querySelector ('canvas') 'or calling 'a element' to download files? Will a lot of calling 'a element' to download files cause some links to be lost?
