### ISSUE TITLE
Can I judge when the download is completed after calling saveAs()?

### ISSUE THREAD

**Issue by JiangWeian** [eligrey/FileSaver.js#699]

**Comment by TDay1** [comment]
I don't believe so, and it wouldn't be possible to implement using the standard web APIs. 
It might be possible to do this manually using some weird JS /iFrame  hackery, but as far as I know none of the mainstream browsers allow for this functionality outside of webextensions.

**Comment by jimmywarting** [comment]
- It is possible with the new experimental [file system access](https://wicg.github.io/file-system-access/) api (currently only available in chrome)
- It can also somewhat be possible with the help of service worker with a combination of downloading a ReadableStream and Content-Disposition attachment header to simulate how a server would trigger a download. you basically listen on the ReadableStreams pull request when the disk/network IO are are asking for more chunks of data - so you can kind of figure out if it's paused, if it did finish or if it was canceled. [StreamSaver](https://github.com/jimmywarting/StreamSaver.js) is one such tool to help out with this 

There is also https://github.com/jimmywarting/native-file-system-adapter wish i have build as a successor after StreamSaver to kind of polyfill the native file system access. it also comes with other supports for different kind of sandboxed file storages and it handles backpressure and pull events better than StreamSaver

Is filesaver.js ever going to support this? most likely not - it tries to be more simpler and only work with blob's and `a[download]`
