### ISSUE TITLE
Let user select the location of the download

### ISSUE THREAD

**Issue by robertosalazare** [eligrey/FileSaver.js#704]
is there a way to open the window that will let the user select the location where the file is going to be saved with FileSaver.js?

**Comment by jimmywarting** [comment]
Only somewhat by using the new [native file system](https://wicg.github.io/native-file-system/)

How: https://github.com/WICG/file-system-access/blob/ad05f5f8dc6398fa2a19453e497810168e4f3e58/SuggestedNameAndDir.md

with FileSaver - src you can't

**Comment by robertosalazare** [comment]
@jimmywarting Thank you for answering that fast!
