### ISSUE TITLE
saveAs fails on Firefox without any error

### ISSUE THREAD

**Issue by Xwilarg** [eligrey/FileSaver.js#726]
Hi,

I'm trying to download a zip file using FileSaver.js from an extension, it works fine on Chrome but on Firefox it fails without any error
My code is like that:
```ts
this.#zip.generateAsync({type: "blob"}, function(elem: any) {
    // [...]
})
.then(function(content: Blob) { // Zipping done
    self.currentProgress = 100;
    try {
        console.log("done zipping");
        console.log(self.downloadName + "." + self.useZip);
        console.log(content);
        FileSaver.saveAs(content, self.downloadName + "." + self.useZip);
        console.log("file downloaded");
    } catch (e) { console.error(e); }
});
```
The console output is the following:
![image](https://user-images.githubusercontent.com/20053454/133122317-628565a3-25ff-4268-b42b-38b2d79f3aaa.png)
But no file is downloaded

I'm on Firefox 92.0

**Comment by Beungoud** [comment]
Same problem here. 
Still doesn't work when reinstalling Firefox.
Works again when reinstalling an other instance of firefox side by side.

**Comment by Xwilarg** [comment]
Looks like this was fixed with one of the recent update of the library

**Comment by mmzysk** [comment]
@Xwilarg  do you know which update specifically? We are having this issue.

**Comment by Xwilarg** [comment]
I'm on the latest version (2.0.5)
Curiously the latest on GitHub release is 2.0.4 but the [npm page](https://www.npmjs.com/package/file-saver) have a 2.0.5 one
