### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by grassick** [eligrey/FileSaver.js#74]
Would you be able to do an npm publish to update the version on npmjs?

Thank you for this handy library!

**Comment by Turbo87** [comment]
@eligrey are you aware that this is leading and has led to a big chaos already? there are multiple versions of this library on npm now and it seems that not a single one of them is actually up-to-date... are you really suggesting that everyone should publish their own now?

**Comment by grassick** [comment]
@Turbo87  I have `filesaver.js` on npm. I use it regularly and am willing to update it if there is a stable version. I have a fork at https://github.com/mWater/FileSaver.js that I published with. Or, I will defer to you @eligrey if you wish to take over.

**Comment by Turbo87** [comment]
@grassick that version seems to have been published seven months ago and there have been several new commits since then. But I guess another problem is that there are no git tags in this repo that would define any versions...

**Comment by grassick** [comment]
Ok, latest commits merged and pushed to npm as `filesaver.js` version 0.2.0!

**Comment by pcwinters** [comment]
:-1:
