### ISSUE TITLE
Does this work in Chrome Packaged Apps?

### ISSUE THREAD

**Issue by carlelieser** [eligrey/FileSaver.js#79]
I am developing a text-editor for the chrome webstore and I have a problem with some of the code.

So i created a button in html: <button type="button" id="save">Save</button>
And then when it is clicked , it should open up a save dialogue to save the txt file, but instead (I went into the console) it shows me this: Uncaught TypeError: Property 'saveAs' of object [object Object] is not a function . This is so weird because it works fine on the website version but for some reason it doesn't work. Here's the jquery code:

```
$('#save').click(function () {
    var title = $('#document_name').val() + '.txt';//Get's the name of the document from an input box
    var textValue = $('textarea').val();//Get's the value of the textarea
    var upper = textValue.replace(/^[a-z]/, function (m) { //Turns first letter of every sentence into an upper case letter
        return m.toUpperCase();
    });
    var blob = new Blob([upper], { // Creates the file
        type: "text/plain;charset=utf-8"
    });
    saveAs(blob, title); // Supposedly save's it (this is the problem) 
});
```

App doesn't detect it as a function even though it is specified in FileSaver.js and FileSaver.js is linked to the html file. I have looked all over the web and cannot seem to find an answer, so I was hoping you could help, master.....

**Comment by Raiper34** [comment]
Same here :/ Is problem solved?

**Comment by carlelieser** [comment]
take a look at the chrome.fileSystem API, you dont need fileSaver.js to do what you want :)

**Comment by Raiper34** [comment]
but it is for chrome os only no? I have normal browser app, not app, only webpage :/

**Comment by carlelieser** [comment]
yeah sorry i thought you were talking about chome apps, my bad.

**Comment by keatklein** [comment]
Did you guys ever solve this one?  I am use FileSaver.js in my Chrome Extension and the issue was with my Manifest.json file.  I am using content scripts to include filesaver.js but what solved my problem was moving filesaver before popup.js.  Just had to change `[ "jquery-3.1.1.min.js",  "lodash.js", "popup.js", "FileSaver.min.js" ],` to `[ "jquery-3.1.1.min.js",  "lodash.js", "FileSaver.min.js", "popup.js" ],`

`"content_scripts": [
    {
      "matches": [ "https://login.salesforce.com/*", "https://na17.salesforce.com/*" ],
      "js": [ "jquery-3.1.1.min.js",  "lodash.js", "FileSaver.min.js", "popup.js" ],
      "run_at": "document_end"
    }
  ]`
