### ISSUE TITLE
导出为zip调用saveas方法时zip名称的时间是xx:xx:xx会转化为xx_xx_xx

### ISSUE THREAD

**Issue by qhl123456** [eligrey/FileSaver.js#804]
![0d791d2ac34b37186754facf8117b8e](https://github.com/eligrey/FileSaver.js/assets/74643840/a3913a44-1e7e-4428-8cf1-8f1076556c96)
![a1f67ef51e25ca269cd8dca362d2c02](https://github.com/eligrey/FileSaver.js/assets/74643840/e5c73680-f7ec-4365-9926-f5342e11daac)
![ebb066ee8255c683ae375ea3bf61bfb](https://github.com/eligrey/FileSaver.js/assets/74643840/a907d4f2-4dbf-4272-bbb6-22f90583ea43)

**Comment by hulang** [comment]
win下，文件，文件夹能带:，这个常识，你不知道吗？

**Comment by qhl123456** [comment]
> win下，文件，文件夹能带:，这个常识，你不知道吗？

感谢大佬，受教
